"""Outro A: bake the stand-in "last frame of the episode" into a TS data module.

Ep1's tag and button aren't built, so the stand-in is the LAST frame of the Act Four v4 animatic
(out/ep01/act4/animatic/act4-animatic-v4-picture.mp4, 960x540 = the 480x270 native frame at 2x), reduced to
480x270 and snapped to the master palette (studio/src/shared/pixel/palette.ts), so the pixel engine can use it
like any drawn frame (the bezel pull-back, the box-filtered thumbnail on Mas's monitor).

Run (repo root):
  audio/.venv-theme/bin/python studio/src/dev/outro/a/tools/standin.py
Reads only the animatic and palette.ts; writes studio/src/dev/outro/a/standin-data.ts and a PNG proof into
the scratch folder given by OUTRO_A_SCRATCH (default: the session scratch).
"""
import os  # noqa: E402  (phase 1: the project root is found at run time, docs/ORGANIZATION-PLAN.md §4)
import sys  # noqa: E402


def _repo():
    for start in (os.path.dirname(os.path.abspath(__file__)), os.getcwd()):
        d = start
        while True:
            if os.path.exists(os.path.join(d, '.mrmas-root')):
                return d
            if d == os.path.dirname(d):
                break
            d = os.path.dirname(d)
    sys.exit('MR. MAS: no .mrmas-root above this script or the cwd; set MRMAS_ROOT')


REPO = os.environ.get('MRMAS_ROOT') or _repo()
import base64
import os
import re
import subprocess
import sys

import numpy as np
from PIL import Image

ROOT = REPO
SRC = f'{ROOT}/out/ep01/act4/animatic/act4-animatic-v4-picture.mp4'
PAL_TS = f'{ROOT}/studio/src/shared/pixel/palette.ts'
OUT_TS = f'{ROOT}/studio/src/dev/outro/a/standin-data.ts'
SCRATCH = os.environ.get('OUTRO_A_SCRATCH',
                         '/tmp/claude-1000/-home-jgon-project-art-mrmas/a5e7723c-6ab4-4824-a1ed-8e367fdb82e5/scratchpad/outro-a')
FFD = f'{ROOT}/studio/node_modules/@remotion/compositor-linux-x64-gnu'


def palette():
    src = open(PAL_TS).read()
    body = src[src.index('const P = {'):src.index('} as const;')]
    names, cols = [], []
    for m in re.finditer(r'\b([A-Z][0-9])\s*:\s*0x([0-9a-fA-F]{6})', body):
        names.append(m.group(1))
        cols.append(int(m.group(2), 16))
    return names, cols


def main():
    os.makedirs(SCRATCH, exist_ok=True)
    png = os.path.join(SCRATCH, 'standin-src-960.png')
    env = dict(os.environ, LD_LIBRARY_PATH=FFD)
    # the last decoded frame (-update 1 keeps overwriting the one image until the stream ends)
    subprocess.run([f'{FFD}/ffmpeg', '-hide_banner', '-loglevel', 'error', '-y', '-sseof', '-0.5', '-i', SRC,
                    '-update', '1', png], check=True, env=env)
    im = np.asarray(Image.open(png).convert('RGB')).astype(np.float32)
    assert im.shape[:2] == (540, 960), im.shape
    names, cols = palette()
    pal = np.array([[(c >> 16) & 255, (c >> 8) & 255, c & 255] for c in cols], np.float32)
    # snap every source pixel to the palette, then take each 2x2 block's most common index
    idx = np.zeros(im.shape[:2], np.int64)
    err = np.zeros(im.shape[:2], np.float32)
    for y0 in range(0, im.shape[0], 60):          # in row chunks (keeps the distance table small)
        d = ((im[y0:y0 + 60, :, None, :] - pal[None, None, :, :]) ** 2).sum(-1)
        idx[y0:y0 + 60] = d.argmin(-1)
        err[y0:y0 + 60] = np.sqrt(d.min(-1))
    blocks = idx.reshape(270, 2, 480, 2).transpose(0, 2, 1, 3).reshape(270, 480, 4)
    out = np.zeros((270, 480), np.uint8)
    for y in range(270):
        for x in range(480):
            v, n = np.unique(blocks[y, x], return_counts=True)
            out[y, x] = v[n.argmax()]
    rgb = pal[out].astype(np.uint8)
    Image.fromarray(rgb).save(os.path.join(SCRATCH, 'standin-480.png'))
    b64 = base64.b64encode(out.tobytes()).decode()
    with open(OUT_TS, 'w') as fh:
        fh.write('// GENERATED by tools/standin.py (do not edit): the stand-in "episode last frame" for outro A,\n'
                 '// the last frame of out/ep01/act4/animatic/act4-animatic-v4-picture.mp4, 480x270, as indices into\n'
                 '// PAL_NAMES (master palette declaration order). Ep1\'s real button is not built yet.\n')
        fh.write(f'export const STANDIN_NAMES = {names!r};\n'.replace("'", '"'))
        fh.write(f"export const STANDIN_B64 = '{b64}';\n")
    print(f'palette {len(names)} colours; source snap error mean {err.mean():.1f}, p99 {np.percentile(err, 99):.1f}')
    print(f'wrote {OUT_TS} ({os.path.getsize(OUT_TS)} bytes)')


if __name__ == '__main__':
    sys.exit(main())
