// GENERATED by studio/src/episodes/ep02/pixel/tools/lock.py from (scaffold: no timeline for coldopen yet)
// (takes: none; plan: none). Do not hand-edit: re-run lock.py.
// Frames are segment frames (0 = the timeline's first beat; epIn = its episode frame). Shot-relative: lines[].s/e (first
// sound / after the last; s < 0 = it started earlier, carry = from an earlier shot, pre = a pre-lap under this shot),
// fs/fe (the take file), texts[].s/e, marks, spots[].k, onscreen[].s/e. mouth = [[frame from s, viseme]], words = [[w, f0, f1]].
// face = who shows a mouth in this framing ('lip' | 'room' | null). The layouts read this through ../types.ts.
/* eslint-disable */
import type {SegLock} from '../types';
export const LOCK: SegLock = {"seg":"coldopen","label":"COLDOPEN","fps":24,"frames":48,"epIn":0,"mix":null,"source":{"timeline":"(scaffold: no timeline for coldopen yet)","takes":[],"plan":null},"cast":{},"refs":{},"soundMarks":[],"seqs":[{"id":"COLDOPEN","chapter":"COLDOPEN","title":"","place":"","time":"","s":0,"e":48,"cue":"","side":""}],"rails":[],"subs":[],"v4Ids":{},"shots":[{"id":"pending","setup":"pending","beats":["pending"],"seq":"COLDOPEN","side":"MAS","badge":null,"whip":null,"tag":"CARD · no lock yet","cls":"GFX","framing":"CARD · no lock yet","move":"cut","s":0,"e":48,"plan":48,"v4":null,"verdict":"","does":"Ep2 v1 · coldopen: no lock yet. The base lock (audio/reel/ep02-v1/build_timeline.py) and tools/lock.py write data.ts.","sound":"","chars":[],"lines":[],"texts":[],"marks":{},"kind":"card","set":"void","room":"","style":"BASE","fx":[],"slate":false,"sideLabel":"","cues":[],"spots":[],"onscreen":[],"speak":[],"beatStarts":{"pending":0},"names":[],"fg":null,"cast":[],"scene":"pending","sceneS":0}],"scenes":[{"id":"pending","s":0,"e":48,"shots":["pending"]}]};
export default LOCK;
