#!/usr/bin/env python3
"""MR. MAS - style-range prototype E1-P3 (1.D, BELOW, ABOVE, AROUND): the timing lock.

  python3 src/dev/range/ep1-p3/tools/lock.py          (from studio/)  -> src/dev/range/ep1-p3/data.ts

Reads, read-only, the v5 stick reel (show/reel/ep01-act4-v5.json) and the v5 takes (audio/ep01/act4/dialogue/lines-v5.json)
and writes the clip's clock: p0 = the reel's S7.02 (reel 412.0 s, with the reel's 3 s title card), the shot starts on the
reel's own frame rounding (bed.py / schema.ts timeEpisode), every take's file start on the clip clock, its words (clip
seconds) and its recorded mouth cues (clip frames). Nothing here is heard or watched.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
STUDIO = os.path.abspath(os.path.join(HERE, '..', '..', '..', '..', '..'))
ROOT = os.path.dirname(STUDIO)
REEL = os.path.join(ROOT, 'show/reel/ep01-act4-v5.json')
LINES = os.path.join(ROOT, 'audio/ep01/act4/dialogue/lines-v5.json')
OUT = os.path.join(HERE, '..', 'data.ts')
FPS, TITLE = 24, 72
SHOTS = ['S7.02', 'S7.02b', 'S7.03', 'S7.05']
CLIP_F = 437

R = json.load(open(REEL))
L = {l['id']: l for l in json.load(open(LINES))}
starts, acc, prev = {}, 0.0, TITLE
for b in R['beats']:
    acc += b['reelDur']
    end = max(prev + 1, TITLE + round(acc * FPS))
    starts[b['id']] = (prev, end, b)
    prev = end
P0 = starts['S7.02'][0]
shots = []
takes = []
for sid in SHOTS:
    s, e, b = starts[sid]
    shots.append(dict(id=sid, s=s - P0, e=min(e - P0, CLIP_F), frame=b['frame']))
    for ln in b.get('lines', []):
        rec = L[ln['id']]
        on = (s - P0) / FPS + ln['t']                  # speech onset, clip seconds
        fstart = on - ln['in']                         # the file's first sample, clip seconds
        words = [[w['w'], round(fstart + w['t0'], 4), round(fstart + w['t1'], 4)] for w in rec['words']]
        mouth = [[round((fstart + m['t']) * FPS, 2), m['shape']] for m in rec.get('mouth', [])]
        takes.append(dict(id=ln['id'], who=ln['who'], shot=sid, text=ln['text'], audio=ln['audio'], fileStart=round(fstart, 4),
                          on=round(on, 4), end=round(on + ln['dur'], 4), words=words, mouth=mouth))

hdr = ('// GENERATED by tools/lock.py from show/reel/ep01-act4-v5.json + audio/ep01/act4/dialogue/lines-v5.json (read-only).\n'
       '// Do not hand-edit: re-run the lock. p = the clip frame (p0 = reel frame %d = reel %.3f s, the v5 reel with its 3 s card).\n'
       '/* eslint-disable */\n') % (P0, P0 / FPS)
body = [
    'export interface Take { id: string; who: string; shot: string; text: string; audio: string; fileStart: number; on: number; end: number; words: Array<[string, number, number]>; mouth: Array<[number, string]>; }',
    'export interface ShotRec { id: string; s: number; e: number; frame: string; }',
    f'export const REEL_P0 = {P0};',
    f'export const CLIP_F = {CLIP_F};',
    'export const SHOTS: ShotRec[] = ' + json.dumps(shots) + ';',
    'export const TAKES: Take[] = ' + json.dumps(takes) + ';',
]
open(OUT, 'w').write(hdr + '\n'.join(body) + '\n')
print('wrote', os.path.relpath(OUT, STUDIO), 'shots', [(x['id'], x['s'], x['e']) for x in shots])
for t in takes:
    print(t['id'], t['who'], 'file@%.3f' % t['fileStart'], [(w[0], round(w[1] * FPS, 1)) for w in t['words']][-6:])
