"""MR. MAS - style-range prototype E1-P3 (1.D): the clip's subtitle track (SRT), from the takes' own word clock.
  python3 src/dev/range/ep1-p3/tools/subs.py <out.srt>
Reads data.ts (GENERATED by lock.py from the v5 reel and the v5 lines; read-only here). The show's picture carries no
typed dialogue box over close coverage (pov-and-framing 4.7.3 rule 4, Act Four v4); "the subtitle track carries
accessibility". So this is that track, muxed into the mp4 as a soft (mov_text) stream, default on: a player shows it
in the band, where the cold read (sound off) felt a missing subtitle track. The picture is unchanged by it.
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(HERE, '..', 'data.ts')).read()
takes = json.loads(re.search(r'export const TAKES: Take\[\] = (\[.*\]);', src).group(1))
shots = json.loads(re.search(r'export const SHOTS: ShotRec\[\] = (\[.*?\]);', src).group(1))
cuts = sorted(s['s'] / 24 for s in shots) + [json.loads(re.search(r'export const CLIP_F = (\d+);', src).group(1)) / 24]


def words(tid):
    return next(t for t in takes if t['id'] == tid)['words']


def cue(ws, text, hold=0.35):
    """a cue from its first word's start to its last word's end + hold, never across a cut"""
    a, b = ws[0][1], ws[-1][2] + hold
    nxt = min(c for c in cuts if c > a + 0.01)
    return a, min(b, nxt), text


w5, w6, w7 = words('a5-30-05'), words('a5-30-06'), words('a5-30-07')
cues = [
    cue(w5, 'What happens to you if NopeAI disappears?'),
    cue(w6[0:4], "Oh, we'd be fine."),
    cue(w6[4:14], 'We have all the IP rights and all the capability.'),
    cue(w6[14:], 'We are below them, above them, around them.', hold=0.5),
    cue(w7, 'Hello.', hold=0.6),
]


def ts(t):
    ms = int(round(t * 1000))
    return f'{ms // 3600000:02d}:{ms // 60000 % 60:02d}:{ms // 1000 % 60:02d},{ms % 1000:03d}'


with open(sys.argv[1], 'w') as f:
    for i, (a, b, text) in enumerate(cues, 1):
        f.write(f'{i}\n{ts(a)} --> {ts(b)}\n{text}\n\n')
print(open(sys.argv[1]).read())
