// MR. MAS — Ep1 full v3, the `v3-art-b` pass (Acts Two, Three and the tag): one demo still per new asset state, the
// stills sheet's registry (tools/sheet.ts). Each demo paints the 480 x 203 picture area of a native frame the way the
// v3 shot would use the asset, so the sheet shows the asset in its framing, not on a blank. These are previews, not the
// v3 layouts: the per-segment shot passes (`v3-shots-<seg>`) own the shots. Keys are `ID@state`; the beat each still
// serves is in its note (the beat plan's ids: show/episodes/ep01/production/full-v3/beat-plan/*.json).
import {Buf, rect, bayer} from '../../../../shared/pixel/px';
import {PAL} from '../../../../shared/pixel/palette';
import {blitImg, Img} from '../../../../shared/pixel/figure';
import {text} from '../../../../shared/pixel/font';
import {putBustCut} from '../../../../shared/pixel/cast/civic-kit';
// Act Two
import * as WH from '../../../../shared/pixel/rooms/whitehouse';
import {drawBlocks, drawTripod, drawCeilingCam, drawBigFlame} from '../../../../shared/pixel/kits/wh-props';
import {sirrahBust, SIRRAH_BUST_DEFAULT, drawSirrahRoom, drawPointer, SIRRAH_POINTER_HAND} from '../../../../shared/pixel/cast/sirrah';
import {nedibBust, NEDIB_BUST_DEFAULT, drawNedibRoom} from '../../../../shared/pixel/cast/nedib';
import {radnusBust, RADNUS_BUST_DEFAULT} from '../../../../shared/pixel/cast/radnus-standin';
import {drawRadnus, RADNUS_DEFAULT} from '../../../../shared/pixel/cast/radnus';
import {marioPortraitImg, MARIO_PORTRAIT_REST} from '../../../../shared/pixel/cast/mario';
import {masPortrait, MAS_PORTRAIT_DEFAULT} from '../../../../shared/pixel/cast/mas';
import * as BB from '../../../../shared/pixel/rooms/bay-bridge';
import {drawRumptWindow, drawAnchor, drawSenator, drawGallery, drawSigner, drawTasyaStage} from '../../../../shared/pixel/cast/civic-extras';
import * as SN from '../../../../shared/pixel/rooms/senate';
import * as SP from '../../../../shared/pixel/kits/senate-props';
import {lahtBust, LAHT_BUST_DEFAULT, drawLahtRoom} from '../../../../shared/pixel/cast/lahtnemulb';
import {sucramBust, SUCRAM_BUST_DEFAULT, drawSucramRoom} from '../../../../shared/pixel/cast/sucram';
import * as TP from '../../../../shared/pixel/kits/tour-poster';
import * as RT from '../../../../shared/pixel/rooms/rooftop';
import * as RG from '../../../../shared/pixel/kits/register';
import {nesnejBust, NESNEJ_BUST_DEFAULT, drawNesnejRoom} from '../../../../shared/pixel/cast/nesnej';
// Act Three and the tag
import * as A3 from '../../../../shared/pixel/rooms/darkroom-act3';
import * as MON from '../../../../shared/pixel/kits/mas-monitor';
import {tidderPainter, TIDDER_POST, TIDDER_EDIT} from '../../../../shared/pixel/kits/tidder';
import {eoPainter} from '../../../../shared/pixel/kits/eo-signing';
import {lighthousePainter, devdayPainter, coldOpenPainter} from '../../../../shared/pixel/kits/monitor-items';
import {drawPhoneHigh, phoneMini, ORB_CIRCLE_LOOKS} from '../../../../shared/pixel/kits/phone-high';
import {drawToast, drawScanFan} from '../../../../shared/pixel/kits/orb-toast';
import {drawEmitCover} from '../../../../shared/pixel/kits/emit-cover';
import {drawFrontPageHigh} from '../../../../shared/pixel/kits/grey-lady';
import {DPLATE_LOOK} from '../../../../shared/pixel/rooms/darkroom-plate';

export interface AssetDemo {
  id: string;
  state?: string;
  /** the module the asset lives in (repo-relative from studio/src) */
  module: string;
  note?: string;
  /** what in this still is still a stand-in (empty = none) */
  standin?: string;
  draw: (fb: Buf) => void;
}
export const DEMOS: AssetDemo[] = [];
const D = (d: AssetDemo) => { DEMOS.push(d); };
const M = 'shared/pixel/';
/** a sheet backdrop for cast drawings: the show's night navy with a floor line */
const bench = (fb: Buf, c0 = PAL.N2, c1 = PAL.N1) => { for (let y = 0; y < 203; y++) for (let x = 0; x < 480; x++) fb.set(x, y, y < 150 ? (bayer(x, y) < 0.3 ? c1 : c0) : PAL.N1); rect(0, 150, 480, 1, fb.ink(PAL.N4)); };
const label = (fb: Buf, s: string, x: number, y: number) => text(fb, s, x, y, PAL.N6);
const bustAt = (fb: Buf, im: Img, x: number, y = 14, flip = false) => putBustCut(fb, im, x, y, 203, flip);

// =================================================================== ACT TWO · sc 13 THE WHITE HOUSE
const whM = M + 'rooms/whitehouse.ts';
D({id: 'ROOM-WH', state: 'wide-arrive', module: whM, note: '13.01 [W] the meeting room: the row faces SIRRAH at the head, her pointer on A', draw: (fb) => { WH.drawWHWide(fb, 0, {sirrah: {on: 'A'}}); }, standin: ''});
D({id: 'ROOM-WH', state: 'wide-pointer-I', module: whM, note: '13.02-13.04 in the wide: the pointer lands on I (the block lights 2 f)', draw: (fb) => { WH.drawWHWide(fb, 0, {sirrah: {on: 'I', mouth: 'open'}}); }, standin: ''});
D({id: 'ROOM-WH', state: 'wide-tripods', module: whM, note: '13.06 the photographer sets the third tripod (1 2 3 taped), back to us', draw: (fb) => { WH.drawWHWide(fb, 0, {tripods: 3, photographer: 'set', sirrah: {on: null}}); }, standin: ''});
D({id: 'ROOM-WH', state: 'wide-eyelines', module: whM, note: '13.08 four wrong eyelines: Tasya cam 3, Mario cam 2, Radnus the ceiling camera', draw: (fb) => { WH.drawWHWide(fb, 0, {tripods: 3, photographer: 'stand', look: {tasya: 'cam3', mario: 'cam2', radnus: 'ceiling'}, sirrah: {on: null}}); }, standin: ''});
D({id: 'ROOM-WH', state: 'wide-door', module: whM, note: '13.11 the door opens behind the row, NEDIB strides in mid-sentence; heads turning (each its own speed)', draw: (fb) => { WH.drawWHWide(fb, 6, {tripods: 3, door: 2, nedib: {t: 0.25}, look: {radnus: 'door', mario: 'door'}, sirrah: {on: null}, finger: 1}); }, standin: ''});
D({id: 'ROOM-WH', state: 'wide-flash', module: whM, note: '13.12 all three cameras fire on the turned heads (the 2-tone freeze + card go on top)', draw: (fb) => { WH.drawWHWide(fb, 0, {tripods: 3, door: 3, nedib: {t: 0.6}, look: {radnus: 'door', mario: 'door', tasya: 'door'}, flash: 1, finger: 2, flame: 1, sirrah: {on: null}}); }, standin: ''});
D({id: 'ROOM-WH', state: 'mcu-sirrah-A', module: whM + ' drawSirrahMCU', note: '13.02 [MCU] SIRRAH right third, the blocks at MCU size, the pointer on A', draw: (fb) => { WH.drawSirrahMCU(fb, 0, {on: 'A', sirrah: {mouth: 'E'}}); }});
D({id: 'ROOM-WH', state: 'mcu-sirrah-I', module: whM + ' drawSirrahMCU', note: '13.03-13.04 the pointer on I (the card freezes here)', draw: (fb) => { WH.drawSirrahMCU(fb, 0, {on: 'I', sirrah: {mouth: 'smile'}}); }});
D({id: 'ROOM-WH', state: '2s-radnus-mario', module: whM + ' drawWH2S', note: '13.05 [2S] Radnus writes it down; Mario\'s finger up; the scroll\'s end past the table', draw: (fb) => { WH.drawWH2S(fb, 0, {L: {img: radnusBust({...RADNUS_BUST_DEFAULT, arm: 'write', lid: 1})}, R: {img: marioPortraitImg({...MARIO_PORTRAIT_REST, finger: 2, mouth: 1})}, pad: true, scroll: 30}); }, standin: 'the RADNUS bust'});
D({id: 'ROOM-WH', state: 'row-pan-tasya', module: whM + ' drawClassRow', note: '13.07 [MCU] the pan starts on Tasya (cam 3) and Mario (cam 2), R -> L, whole px', draw: (fb) => { WH.drawClassRow(fb, 0); }, standin: 'the RADNUS bust'});
D({id: 'ROOM-WH', state: 'row-pan-mas', module: whM + ' drawClassRow', note: '13.07 settled on Mas at the row\'s end: the lens look (his one); Radnus on the ceiling cam', draw: (fb) => { WH.drawClassRow(fb, WH.WH_ROW.panMax); }, standin: 'the RADNUS bust'});
D({id: 'ROOM-WH', state: '2s-mas-radnus', module: whM + ' drawWH2S', note: '13.09 [2S] MAS + RADNUS, Radnus leaning across, the flame on his collar (held 16 s)', draw: (fb) => { WH.drawWH2S(fb, 0, {L: {img: masPortrait({...MAS_PORTRAIT_DEFAULT, light: 'warm', look: -1}), flip: true}, R: {img: radnusBust({...RADNUS_BUST_DEFAULT, arm: 'lean', mouth: 'E'}), dx: -60}, flame: {slot: 'R', size: 1}}); }, standin: 'the RADNUS bust'});
D({id: 'ROOM-WH', state: 'ots-nedib', module: whM + ' drawWHOTS', note: '13.13 [OTS] from behind Mario\'s raised finger onto NEDIB; the WHOLE scroll out (draft 6)', draw: (fb) => { WH.drawWHOTS(fb, 0, {nedib: {mouth: 'A', arm: 'baton'}, finger: 2, scroll: 4}); }});
D({id: 'ROOM-WH', state: 'ots-nedib-scroll2', module: whM + ' drawWHOTS', note: '13.13 earlier: finger half up, the scroll half out of his pocket (held steps)', draw: (fb) => { WH.drawWHOTS(fb, 0, {nedib: {mouth: 'E'}, finger: 1, scroll: 2}); }});
D({id: 'PROP-COLLAR-FLAME', state: 'size-1', module: whM + ' drawCollarFlame', note: '13.10 [ECU] the small flame on Radnus\'s collar', draw: (fb) => { WH.drawCollarFlame(fb, 0, {size: 1}); }, standin: ''});
D({id: 'PROP-COLLAR-FLAME', state: 'size-2-pat', module: whM + ' drawCollarFlame', note: '13.10 it grows one size; his hand pats at it (2 held drawings)', draw: (fb) => { WH.drawCollarFlame(fb, 3, {size: 2, pat: 1}); }, standin: ''});
D({id: 'PROP-CLASS-PHOTO', state: 'print', module: whM + ' drawClassPhoto', note: '13.14 [ECU] CLASS PHOTO #1: the flash frame printed; blocks I A; Mas at the lens; his hand holds it', draw: (fb) => { WH.drawClassPhoto(fb, 0, {}); }, standin: ''});
D({id: 'PROP-AI-BLOCKS', state: 'sizes', module: M + 'kits/wh-props.ts', note: 'the A and I blocks: MCU size (hit on I), room size AI and the restack IA', draw: (fb) => { bench(fb); drawBlocks(fb, 30, 150, 48, {hit: 'I'}); drawBlocks(fb, 220, 150, 18, {}); drawBlocks(fb, 300, 150, 18, {order: 'IA'}); drawTripod(fb, 400, 150, 1, {}); drawTripod(fb, 440, 150, 2, {flash: 1}); drawCeilingCam(fb, 460, 10, 0); label(fb, 'MCU  ·  ROOM AI  ·  ROOM IA (RESTACK)  ·  TRIPODS', 10, 170); }});
D({id: 'CAST-SIRRAH', state: 'bust', module: M + 'cast/sirrah.ts', note: 'SIRRAH: plum pantsuit, pearls, the CZAR? sticky note; pointer arm; mouths smile · E · A', draw: (fb) => { bench(fb, PAL.W2, PAL.W1); bustAt(fb, sirrahBust({...SIRRAH_BUST_DEFAULT}), 10); drawPointer(fb, 10 + SIRRAH_POINTER_HAND[0], 14 + SIRRAH_POINTER_HAND[1], 0, 150, 2); bustAt(fb, sirrahBust({...SIRRAH_BUST_DEFAULT, mouth: 'E', arm: 'down'}), 150); bustAt(fb, sirrahBust({...SIRRAH_BUST_DEFAULT, mouth: 'A', arm: 'down', lid: 1, brow: 1}), 300); }});
D({id: 'CAST-SIRRAH', state: 'room', module: M + 'cast/sirrah.ts', note: 'room sprite: pointer (laid to any target) · clasp · open mouth', draw: (fb) => { bench(fb, PAL.W2, PAL.W1); const h = drawSirrahRoom(fb, 80, 150, {legs: 'stand', arm: 'point', mouth: 'smile'}); drawPointer(fb, h[0], h[1], h[0] + 26, h[1] + 18, 1); drawSirrahRoom(fb, 200, 150, {legs: 'stand', arm: 'clasp', mouth: 'open'}); drawSirrahRoom(fb, 300, 150, {legs: 'stand', arm: 'down', mouth: 'rest'}, {flip: true}); }});
D({id: 'CAST-NEDIB', state: 'bust', module: M + 'cast/nedib.ts', note: 'NEDIB: the aviators up on his head, the fountain pen like a baton; sign; mouths', draw: (fb) => { bench(fb, PAL.W2, PAL.W1); bustAt(fb, nedibBust({...NEDIB_BUST_DEFAULT}), 20); bustAt(fb, nedibBust({...NEDIB_BUST_DEFAULT, mouth: 'A', arm: 'down'}), 170); bustAt(fb, nedibBust({...NEDIB_BUST_DEFAULT, mouth: 'E', arm: 'sign', lid: 1}), 320); }});
D({id: 'CAST-NEDIB', state: 'deepfakes', module: M + 'cast/nedib.ts', note: 'the DEEPFAKE NEDIBs: cut paper (a scissor-cut margin), a crude flat print, the wrong ties', draw: (fb) => { bench(fb, PAL.W2, PAL.W1); bustAt(fb, nedibBust({...NEDIB_BUST_DEFAULT, copy: 1, arm: 'clap0'}), 20); bustAt(fb, nedibBust({...NEDIB_BUST_DEFAULT}), 170); bustAt(fb, nedibBust({...NEDIB_BUST_DEFAULT, copy: 2, arm: 'clap1', mouth: 'A'}), 320); label(fb, 'COPY 1', 50, 190); label(fb, 'NEDIB', 205, 190); label(fb, 'COPY 2', 350, 190); }});
D({id: 'CAST-NEDIB', state: 'room', module: M + 'cast/nedib.ts', note: 'room sprite: the stride (4 drawings on 3s, pen up), stand + point, write, a copy', draw: (fb) => { bench(fb, PAL.W2, PAL.W1); (['w0', 'w1', 'w2', 'w3'] as const).forEach((l, i) => drawNedibRoom(fb, 40 + i * 50, 150, {legs: l, arm: 'baton', mouth: 'open', light: 'day'})); drawNedibRoom(fb, 280, 150, {legs: 'stand', arm: 'point', mouth: 'smile', light: 'day'}); drawNedibRoom(fb, 340, 150, {legs: 'stand', arm: 'write', mouth: 'rest', light: 'day'}); drawNedibRoom(fb, 420, 150, {legs: 'stand', arm: 'clap0', mouth: 'smile', light: 'day', copy: 1}); }});
D({id: 'CAST-RADNUS-STANDIN', state: 'bust-room', module: M + 'cast/radnus-standin.ts', note: 'the bust in art-a\'s colours (fold · pat · lean + up); beside it art-a\'s room sprite, used in the row', draw: (fb) => { bench(fb, PAL.W2, PAL.W1); bustAt(fb, radnusBust({...RADNUS_BUST_DEFAULT}), 0); bustAt(fb, radnusBust({...RADNUS_BUST_DEFAULT, arm: 'pat', mouth: 'E'}), 115); bustAt(fb, radnusBust({...RADNUS_BUST_DEFAULT, arm: 'lean', up: true}), 230); drawRadnus(fb, 390, 150, {...RADNUS_DEFAULT, arm: 'fold', fire: null}); drawRadnus(fb, 450, 150, {...RADNUS_DEFAULT, arm: 'fold', fire: null, mouth: 'open'}, {flip: true}); label(fb, 'BUST (STAND-IN)  ·  ROOM: ART-A cast/radnus.ts', 10, 190); }, standin: 'the bust (art-a built RADNUS at room scale only)'});

// =================================================================== sc 14 THE BRIDGE
const bbM = M + 'rooms/bay-bridge.ts';
D({id: 'ROOM-BRIDGE', state: 'ots-clip', module: bbM + ' drawBridgeOTS', note: '14.01 [OTS] over Mas\'s shoulder at the bullpen window: the anchor clip, the ALTERED AUDIO tag', draw: (fb) => { BB.drawBridgeOTS(fb, 0, {f: 0, mouth: 1, progress: 0.4}); }});
D({id: 'ROOM-BRIDGE', state: 'bay', module: bbM + ' drawBayWide', note: '14.02 [W] push 1: the bay, the lit skyline, the one dark tower with its one lit window', draw: (fb) => { BB.drawBayWide(fb, 0, {}); }});
D({id: 'ROOM-BRIDGE', state: 'lit-window', module: bbM + ' drawLitWindow', note: '14.03 [W] push 2: the lit window, RUMPT\'s silhouette with the phone (the clip on it), nodding', draw: (fb) => { BB.drawLitWindow(fb, 0, {nod: 1}); }});
D({id: 'ROOM-BRIDGE', state: 'repost-press', module: bbM + ' drawRepostECU', note: '14.04 [ECU] push 3: a thumb on the repost arrow under the same tag (hover -> press -> done)', draw: (fb) => { BB.drawRepostECU(fb, 0, {step: 'press'}); }});
D({id: 'ROOM-BRIDGE', state: 'repost-done', module: bbM + ' drawRepostECU', note: '14.04 click: REPOSTED', draw: (fb) => { BB.drawRepostECU(fb, 0, {step: 'done'}); }});
D({id: 'ROOM-BRIDGE', state: 'lit-window-hail', module: bbM + ' drawLitWindow', note: '14.05 a hailstone drops out of the lit window (glyph noise, no letters); the glow still on', draw: (fb) => { BB.drawLitWindow(fb, 0, {nod: 0, hail: 0.4}); }});
D({id: 'ROOM-BRIDGE', state: 'bay-plink-off', module: bbM + ' drawBayWide', note: '14.05 the plink in the bay; the phone\'s glow clicked off (the window\'s cold pixel gone)', draw: (fb) => { BB.drawBayWide(fb, 0, {plink: 6, glow: false}); }});
D({id: 'CAST-RUMPT-WINDOW', state: 'silhouette', module: M + 'cast/civic-extras.ts drawRumptWindow', note: 'RUMPT, silhouette only (props and pose): plain head, square shoulders, the long tie, the phone', draw: (fb) => { bench(fb, PAL.W5, PAL.W4); drawRumptWindow(fb, 20, 60, {nod: 0, glow: true, size: 3}); drawRumptWindow(fb, 120, 60, {nod: 1, glow: true, size: 3}); drawRumptWindow(fb, 220, 60, {nod: 0, glow: false, size: 3}); drawRumptWindow(fb, 330, 100, {nod: 0, glow: true}); drawRumptWindow(fb, 380, 100, {nod: 0, glow: false}); label(fb, 'GLOW · NOD · OFF (x3)      x1', 20, 170); }});
D({id: 'KIT-NEWSCLIP', state: 'anchor', module: bbM + ' drawNewsClip + cast/civic-extras.ts drawAnchor', note: 'the invented anchor clip: mouth shut / open (run a beat late), the grey tag', draw: (fb) => { bench(fb); BB.drawNewsClip(fb, 20, 20, 140, 100, {f: 0, mouth: 0}); BB.drawNewsClip(fb, 180, 20, 140, 100, {f: 0, mouth: 1}); BB.alteredTag(fb, 20, 128); drawAnchor(fb, 360, 40, {mouth: 1}); drawAnchor(fb, 400, 40, {mouth: 0, blink: true}); }});

// =================================================================== sc 15 THE SENATE
const snM = M + 'rooms/senate.ts';
D({id: 'ROOM-SENATE', state: 'wide', module: snM + ' drawSenateWide', note: '15.02 [W] the hearing room: the dais (the clone in the better chair), the gallery, the witness table', draw: (fb) => { SN.drawSenateWide(fb, 0, {chair: {arm: 'card'}}); }});
D({id: 'ROOM-SENATE', state: 'wide-lean-lit', module: snM + ' drawSenateWide', note: '15.10 the dais leans in; one microphone\'s red light comes on', draw: (fb) => { SN.drawSenateWide(fb, 0, {lean: true, lit: 'senB', senMouth: 'senB'}); }});
D({id: 'ROOM-SENATE', state: 'wide-wallet-gasp', module: snM + ' drawSenateWide', note: '15.13 Mas holds the open wallet up to the dais; the gallery gasps (one held drawing)', draw: (fb) => { SN.drawSenateWide(fb, 0, {mas: {wallet: true}, gasp: true, clone: {mouth: 'open'}}); }});
D({id: 'ROOM-SENATE', state: 'dais-sheet-in', module: snM + ' drawSenateDais', note: '15.16 [W] the dais: the sheet arrives from frame left into the clone\'s hand', draw: (fb) => { SN.drawSenateDais(fb, 0, {sheet: 2, lean: true}); }});
D({id: 'ROOM-SENATE', state: 'dais-sheet-up', module: snM + ' drawSenateDais', note: '15.16 they turn it over and hold its back up toward the witness table', draw: (fb) => { SN.drawSenateDais(fb, 0, {sheet: 3}); }});
D({id: 'ROOM-SENATE', state: 'dais-2s', module: snM + ' drawDais2S', note: '15.03 [2S] the chairman (matte) and THE CLONE (glossy), the better chair', draw: (fb) => { SN.drawDais2S(fb, 0, {clone: {arm: 'mic', mouth: 'E'}, chair: {arm: 'down', mouth: 'rest'}, lit: 'clone'}); }});
D({id: 'ROOM-SENATE', state: 'witness-2s', module: snM + ' drawWitness2S', note: '15.04-15.05 [2S] MAS + SUCRAM (typing, not looking up)', draw: (fb) => { SN.drawWitness2S(fb, 0, {sucram: {arm: 'phone', lid: 1, mouth: 'E'}}); }});
D({id: 'ROOM-SENATE', state: 'witness-2s-stamp', module: snM + ' drawWitness2S', note: '15.14 Sucram stamps, the moth dodging over the pad', draw: (fb) => { SN.drawWitness2S(fb, 5, {sucram: {arm: 'stamp', lid: 0, mouth: 'A', brow: -1}, moth: 'dodge'}); }});
D({id: 'ROOM-SENATE', state: 'ots-card', module: snM + ' drawSenateOTS', note: '15.07 [OTS] from behind Mas onto the dais: the chairman with his card, the clone at his hand', draw: (fb) => { SN.drawSenateOTS(fb, 0, {take: 0, chair: {mouth: 'E'}}); }});
D({id: 'ROOM-SENATE', state: 'ots-take', module: snM + ' drawSenateOTS', note: '15.07 the clone takes the next card out of his hand and reads it for him', draw: (fb) => { SN.drawSenateOTS(fb, 0, {take: 2, clone: {mouth: 'A'}}); }});
D({id: 'ROOM-SENATE', state: 'mcu-clone', module: snM + ' drawSenateMCU', note: '15.01 [MCU] the voice finds a mouth: THE CLONE at the mic, the 1-px highlight, the gloss', draw: (fb) => { SN.drawSenateMCU(fb, 0, {bust: lahtBust({...LAHT_BUST_DEFAULT, clone: true, arm: 'mic', mouth: 'O'}), third: 'R', bg: 'dais', mic: true, lit: true}); }});
D({id: 'ROOM-SENATE', state: 'mcu-chair', module: snM + ' drawSenateMCU', note: '15.06 [MCU] the chairman reading from a card', draw: (fb) => { SN.drawSenateMCU(fb, 0, {bust: lahtBust({...LAHT_BUST_DEFAULT, arm: 'card', mouth: 'E', lid: 1}), third: 'R', bg: 'dais', mic: true}); }});
D({id: 'ROOM-SENATE', state: 'mcu-sucram', module: snM + ' drawSenateMCU', note: '15.18 [MCU] SUCRAM stares at it (cut on the stare)', draw: (fb) => { SN.drawSenateMCU(fb, 0, {bust: sucramBust({...SUCRAM_BUST_DEFAULT, arm: 'down', lid: 0, brow: 1, mouth: 'rest'}), third: 'L', flip: true, bg: 'gallery'}); }});
D({id: 'PROP-WALLET', state: 'open-moth', module: M + 'kits/senate-props.ts drawWalletECU', note: '15.12 [ECU] one card, HEALTH INSURANCE; the moth out (3 drawings)', draw: (fb) => { SP.drawWalletECU(fb, 0, {open: 2, moth: 2}); }});
D({id: 'PROP-SHEET', state: 'high-stamp', module: M + 'kits/senate-props.ts drawSheetHigh', note: '15.15 [HIGH] PLEASE REGULATE ME, signed, sliding; Sucram\'s stamp comes down mid-slide', draw: (fb) => { SP.drawSheetHigh(fb, 0, {slide: 2, stamp: 'down'}); }});
D({id: 'PROP-SHEET', state: 'high-done', module: M + 'kits/senate-props.ts drawSheetHigh', note: '15.15 stamped: CALLED IT. (BEFORE LAUNCH.), on its way to frame right', draw: (fb) => { SP.drawSheetHigh(fb, 0, {slide: 3, stamp: 'done'}); }});
D({id: 'PROP-SHEET', state: 'back', module: M + 'kits/senate-props.ts drawSheetBack', note: '15.17 [ECU] the back, already stamped in the same red: CALLED IT. (BEFORE SUCRAM.)', draw: (fb) => { SP.drawSheetBack(fb, 0, {}); }});
D({id: 'CAST-LAHTNEMULB', state: 'bust', module: M + 'cast/lahtnemulb.ts', note: 'the chairman (matte) and THE CLONE (glossy: the hair\'s highlight, specular points)', draw: (fb) => { bench(fb, PAL.N3, PAL.N2); bustAt(fb, lahtBust({...LAHT_BUST_DEFAULT}), 10); bustAt(fb, lahtBust({...LAHT_BUST_DEFAULT, clone: true, arm: 'take', mouth: 'E'}), 130); bustAt(fb, lahtBust({...LAHT_BUST_DEFAULT, clone: true, arm: 'sheet', mouth: 'A'}), 250); bustAt(fb, lahtBust({...LAHT_BUST_DEFAULT, arm: 'mic', lid: 1}), 368); }});
D({id: 'CAST-LAHTNEMULB', state: 'room', module: M + 'cast/lahtnemulb.ts', note: 'room sprites (flipped: the dais faces left): card · down · lean · up (the sheet), chairman / clone', draw: (fb) => { bench(fb, PAL.N3, PAL.N2); drawLahtRoom(fb, 60, 150, {arm: 'card', mouth: 'rest', clone: false}, {flip: true}); drawLahtRoom(fb, 130, 150, {arm: 'down', mouth: 'open', clone: true}, {flip: true}); drawLahtRoom(fb, 200, 150, {arm: 'lean', mouth: 'rest', clone: true}, {flip: true}); drawLahtRoom(fb, 270, 150, {arm: 'up', mouth: 'open', clone: true}, {flip: true}); drawLahtRoom(fb, 340, 150, {arm: 'down', mouth: 'rest', clone: false, nod: 1}, {flip: true}); }});
D({id: 'CAST-SUCRAM', state: 'bust-room', module: M + 'cast/sucram.ts', note: 'SUCRAM: tweed blazer, open collar, round glasses; phone · stamp · slam; room sprites', draw: (fb) => { bench(fb, PAL.N3, PAL.N2); bustAt(fb, sucramBust({...SUCRAM_BUST_DEFAULT}), 0); bustAt(fb, sucramBust({...SUCRAM_BUST_DEFAULT, arm: 'stamp', lid: 0}), 112); bustAt(fb, sucramBust({...SUCRAM_BUST_DEFAULT, arm: 'slam', lid: 0, mouth: 'A'}), 224); drawSucramRoom(fb, 370, 150, {arm: 'phone', mouth: 'rest', lean: true}); drawSucramRoom(fb, 420, 150, {arm: 'stamp', mouth: 'open'}); drawSucramRoom(fb, 462, 150, {arm: 'slam', mouth: 'rest'}); }});
D({id: 'CAST-SENATORS', state: 'room-gallery', module: M + 'cast/civic-extras.ts', note: 'the senators (3 variants: sit, lean, up) and the gallery\'s tiled drawing, held and the gasp', draw: (fb) => { bench(fb, PAL.N3, PAL.N2); ([0, 1, 2] as const).forEach((v, i) => { drawSenator(fb, 40 + i * 44, 150, v, 'sit', {flip: true}); drawSenator(fb, 180 + i * 44, 150, v, i === 2 ? 'up' : 'lean', {flip: true, mouth: 'open'}); }); drawGallery(fb, 330, 480, 40, 3, {}); drawGallery(fb, 330, 480, 100, 2, {gasp: true}); }});

// =================================================================== sc 16 THE POSTER
const tpM = M + 'kits/tour-poster.ts';
D({id: 'KIT-TOUR-POSTER', state: 'strip-cancelled', module: tpM, note: '16.01 the one held poster: the review-quote strip, EU CANCELLED', draw: (fb) => { TP.drawTourPoster(fb, 0, {strip: true, cancelled: 5}); }});
D({id: 'KIT-TOUR-POSTER', state: 'post', module: tpM, note: '16.01 his post pops over it: "…no plans to leave"', draw: (fb) => { TP.drawTourPoster(fb, 0, {strip: true, cancelled: 5, post: 3}); }});
D({id: 'KIT-TOUR-POSTER', state: 'un-added', module: tpM, note: '16.01 UN-CANCELLED lands over it; the last slot stamps itself ADDED DUE TO POPULAR DEMAND', draw: (fb) => { TP.drawTourPoster(fb, 0, {strip: true, cancelled: 5, un: 4, added: 4}); }});
D({id: 'KIT-TOUR-POSTER', state: 'smile', module: tpM + ' drawPosterSmile', note: '16.01 (16.05 merged) the cut-in on the poster\'s photo: the one-pixel smile, held', draw: (fb) => { TP.drawPosterSmile(fb, 0); }});

// =================================================================== sc 17 THE ROOFTOP
const rtM = M + 'rooms/rooftop.ts';
const QUOTE = '"Mitigating the risk of extinction from AI should be a global priority…"';
D({id: 'ROOM-ROOFTOP', state: 'wide-signers', module: rtM + ' drawRooftopWide', note: '17.01 [W] the table under the sky, the statement typing across the top; the signers queue in', draw: (fb) => { RT.drawRooftopWide(fb, 0, {signers: [{v: 0, at: 'sign'}, {v: 1, at: 'queue0'}, {v: 2, at: 'queue1'}], mas: 'stand', mario: 'stand'}); RT.drawQuoteBox(fb, QUOTE); }});
D({id: 'ROOM-ROOFTOP', state: 'wide-register', module: rtM + ' drawRooftopWide', note: '17.03-17.04 the brass register rolls in on its own; NESNEJ behind it, arms spread', draw: (fb) => { RT.drawRooftopWide(fb, 0, {mas: 'reach', mario: 'write', register: 1, nesnej: {arm: 'spread'}}); }});
D({id: 'ROOM-ROOFTOP', state: 'wide-crack', module: rtM + ' drawRooftopWide', note: '17.11 the hairline crack runs L -> R (12 f); Nesnej and Mario have looked up', draw: (fb) => { RT.drawRooftopWide(fb, 0, {mas: 'stand', mario: 'stand', register: 1, nesnej: {arm: 'down'}, crack: 0.6, look: {nesnej: true, mario: true}}); }});
D({id: 'ROOM-ROOFTOP', state: '2s-sheet', module: rtM + ' drawRooftop2S', note: '17.02 [2S] Mario writes the footnote, the pen tight; Mas\'s hand out for it', draw: (fb) => { RT.drawRooftop2S(fb, 0, {hand: 2, write: 0, footnote: 3, mario: {finger: 2}}); }});
D({id: 'ROOM-ROOFTOP', state: '2s-turn', module: rtM + ' drawRooftop2S', note: '17.05 the pen still in Mario\'s hand, Mas\'s half out; they turn to the register (O.S. right)', draw: (fb) => { RT.drawRooftop2S(fb, 0, {hand: 1, turn: true, write: null, footnote: 4, mario: {mouth: 2}}); }});
D({id: 'ROOM-ROOFTOP', state: 'ots-nesnej', module: rtM + ' drawRooftopOTS', note: '17.06 [OTS] from behind Mario\'s finger onto NESNEJ at the register: "The more you buy…"', draw: (fb) => { RT.drawRooftopOTS(fb, 0, {nesnej: {mouth: 'A'}, finger: 2}); }});
D({id: 'PROP-REGISTER', state: 'key-ecu', module: M + 'kits/register.ts drawKeyECU', note: '17.07 [ECU] he presses one key (KA-CHING)', draw: (fb) => { RG.drawKeyECU(fb, 0, {press: 2}); }});
D({id: 'PROP-REGISTER', state: 'ledger', module: M + 'kits/register.ts ledgerPrint', note: '17.08 the LEDGER flash-print: INVIDIA · $1,000,000,000,000 (INTRADAY)', draw: (fb) => { RG.ledgerPrint(fb); }});
D({id: 'PROP-REGISTER', state: 'window', module: M + 'kits/register.ts drawRegisterWindow', note: '17.09 [INSERT] the figure holds in the register\'s window to read', draw: (fb) => { RG.drawRegisterWindow(fb, 0, {}); }});
D({id: 'PROP-REGISTER', state: 'purchase-order', module: M + 'kits/register.ts drawPurchaseOrder', note: '17.10 [INSERT] the pen in Mario\'s hand is now a purchase order: AI CHIPS · QTY: MORE', draw: (fb) => { RG.drawPurchaseOrder(fb, 0, {}); }});
D({id: 'PROP-GLASS-CRACK', state: 'run-0', module: rtM + ' drawGlassCrack', note: '17.12 [ECU] Mas\'s glass: the crack in the water; the water doesn\'t move', draw: (fb) => { RT.drawGlassCrack(fb, 0, {run: 0}); }});
D({id: 'PROP-GLASS-CRACK', state: 'run-3', module: rtM + ' drawGlassCrack', note: '17.12 the reflected crack runs on after the sky\'s has stopped, across his small reflection', draw: (fb) => { RT.drawGlassCrack(fb, 0, {run: 3}); }});
D({id: 'CAST-NESNEJ', state: 'bust-room', module: M + 'cast/nesnej.ts', note: 'NESNEJ (the roll-call design re-lit for the sun): spread · key; room sprites; the register', draw: (fb) => { bench(fb, PAL.F5, PAL.F4); bustAt(fb, nesnejBust({...NESNEJ_BUST_DEFAULT}), 0, 4); bustAt(fb, nesnejBust({...NESNEJ_BUST_DEFAULT, arm: 'key', mouth: 'O'}), 128, 4, true); drawNesnejRoom(fb, 300, 150, {arm: 'spread', mouth: 'grin'}); drawNesnejRoom(fb, 350, 150, {arm: 'key', mouth: 'open'}); RG.drawRegisterRoom(fb, 400, 150, {flags: true}); }});
D({id: 'CAST-SIGNERS', state: 'room', module: M + 'cast/civic-extras.ts drawSigner', note: 'the signers (unplated; v 0 holds a chess piece: the insider egg): stand · sign · walk', draw: (fb) => { bench(fb, PAL.F5, PAL.F4); ([0, 1, 2] as const).forEach((v, i) => { drawSigner(fb, 40 + i * 60, 150, v, 'stand', {flip: true}); drawSigner(fb, 240 + i * 60, 150, v, i === 1 ? 'walk' : 'sign', {flip: true, f: 3}); }); }});

// =================================================================== ACT THREE · the dark room
const a3M = M + 'rooms/darkroom-act3.ts';
D({id: 'ROOM-DARK-A3', state: 'box-slide', module: a3M + ' drawDarkA3', note: '18.01 [2S] the home room: the outline on the wall, empty; the slot slides out a box like a tray', draw: (fb) => { A3.drawDarkA3(fb, 0, {box: {pos: 2}, orb: null, mas: {arm: 'rest', look: 1}}); }});
D({id: 'ROOM-DARK-A3', state: 'box-landed', module: a3M + ' drawDarkA3', note: '18.01 the box on the desk: COINWORLD', draw: (fb) => { A3.drawDarkA3(fb, 0, {box: {pos: 4}, orb: null, mas: {arm: 'rest', look: 1}}); }});
D({id: 'PROP-COINWORLD', state: 'label', module: a3M + ' drawLabelECU', note: '18.02 [ECU] the label, legible as he reaches for the lid: FROM / SHIP TO', draw: (fb) => { A3.drawLabelECU(fb, 0, {hand: 1}); }});
D({id: 'ROOM-DARK-A3', state: 'orb-rise-1', module: a3M + ' drawDarkA3', note: '18.03 he lifts the lid; the Orb rises out of the foam, step 1 of 3', draw: (fb) => { A3.drawDarkA3(fb, 0, {box: {pos: 4, open: true, rise: 1}, orb: {at: 'box', look: [-0.2, -0.2], aperture: 0.2}, mas: {arm: 'rest', look: 1}}); }});
D({id: 'ROOM-DARK-A3', state: 'orb-rise-3', module: a3M + ' drawDarkA3', note: '18.03 at eye level, the lens finds him (3 drawings) and dilates', draw: (fb) => { A3.drawDarkA3(fb, 0, {box: {pos: 4, open: true, rise: 3}, orb: {at: 'box', look: [-0.95, -0.05], aperture: 0.8}, mas: {arm: 'rest', look: 1}}); }});
D({id: 'ROOM-DARK-A3', state: 'scan-mcu', module: a3M + ' drawScanMCU', note: '18.04 [MCU] the thin cyan cone across his face (the GLYPH tokens go inside its mask, 5 f)', draw: (fb) => { A3.drawScanMCU(fb, 0, {fan: {dir: 184, half: 5}}); }});
D({id: 'ROOM-DARK-A3', state: 'scan-toast', module: a3M + ' drawScanMCU', note: '18.05 the cone gone; the toast pops beside the Orb: verified: human', draw: (fb) => { A3.drawScanMCU(fb, 0, {mas: {mouth: 'E'}, toast: {s: 'verified: human', k: 3}}); }});
D({id: 'ROOM-DARK-A3', state: 'drift', module: a3M + ' drawDarkA3', note: '18.06 [2S] the Orb drifts toward the outline on the wallpaper (whole-px steps)', draw: (fb) => { A3.drawDarkA3(fb, 0, {box: {pos: 4, open: true, rise: 3}, orb: {at: [330, 68], look: [0.8, 0]}, mas: {arm: 'rest', look: 1}}); }});
D({id: 'ROOM-DARK-A3', state: 'home', module: a3M + ' drawDarkA3', note: '18.06 it settles exactly into the outline: "you can stay."', draw: (fb) => { A3.drawDarkA3(fb, 0, {orb: {at: 'home', look: [-0.9, 0.1]}, outline: 'filled', mas: {arm: 'rest', mouth: 'E', look: 1}}); }});
D({id: 'ROOM-DARK-A3', state: 'catching-up', module: a3M + ' drawDarkA3', note: '19.01 [2S] the iris flicks to the monitor (the toast is dropped in the beat plan)', draw: (fb) => { A3.drawDarkA3(fb, 0, {orb: {at: 'home', look: DPLATE_LOOK.grid}, outline: 'filled', mas: {}, plate: {screen: lighthousePainter({meter: true})}}); }});
D({id: 'UI-MONITOR', state: 'lighthouse', module: M + 'kits/monitor-items.ts lighthousePainter + kits/mas-monitor.ts', note: '19.11 [POV] MISANTHROPIC\'s lighthouse, its own sign; Mario on phone one, finger up', draw: (fb) => { MON.drawMonitorPOV(fb, 0, lighthousePainter({meter: false})); }});
D({id: 'ROOM-DARK-A3', state: 'orb-ots', module: a3M + ' drawOrbOTS', note: '19.12 [OTS] from behind the Orb: Mas, lit cyan, watching the lighthouse past him', draw: (fb) => { A3.drawOrbOTS(fb, 0, {screen: lighthousePainter({meter: true})}); }});
D({id: 'UI-MONITOR', state: 'second-phone', module: M + 'kits/monitor-items.ts lighthousePainter', note: '19.13 [POV] the second phone rings (NOZAMA · UP TO $4B); the rent meter spins', draw: (fb) => { MON.drawMonitorPOV(fb, 0, lighthousePainter({meter: true, ring2: 0})); }});
D({id: 'UI-TIDDER', state: 'ots-typing', module: M + 'kits/tidder.ts + kits/mas-monitor.ts drawMonitorOTS', note: '20.01 [OTS] over his shoulder: the TIDDER reply box, typed in source casing', draw: (fb) => { MON.drawMonitorOTS(fb, 0, tidderPainter({phase: 'typing', typed: TIDDER_POST.length})); }});
D({id: 'ROOM-DARK-A3', state: 'leds-off', module: a3M + ' drawDarkA3 (ledsOff)', note: '20.02 [2S] the rack\'s LEDs stop, all of them; the Orb doesn\'t move', draw: (fb) => { A3.drawDarkA3(fb, 0, {orb: {at: 'home', look: DPLATE_LOOK.face}, outline: 'filled', mas: {look: -1}, leds: 'off', plate: {screen: tidderPainter({phase: 'typing', typed: 99})}}); }});
D({id: 'UI-TIDDER', state: 'posted', module: M + 'kits/tidder.ts', note: '20.03 [POV] he posts: the counter spins (a blur), the first reply legible', draw: (fb) => { MON.drawMonitorPOV(fb, 7, tidderPainter({phase: 'posted', count: 1204, spin: true})); }});
D({id: 'ROOM-DARK-A3', state: 'call', module: a3M + ' drawDarkA3 + kits/phone-high.ts phoneMini', note: '20.04 / 20.06 [2S] the call: GERG on speaker on the desk; the Orb\'s long look at him', draw: (fb) => { A3.drawDarkA3(fb, 6, {orb: {at: 'home', look: DPLATE_LOOK.face}, outline: 'filled', mas: {arm: 'rest', look: -1, mouth: 'E'}, plate: {phone: 'up', phoneScreen: phoneMini('gerg'), screen: tidderPainter({phase: 'posted', count: 4120})}}); }});
D({id: 'UI-TIDDER', state: 'edit-tight', module: M + 'kits/tidder.ts', note: '20.05 [POV] the edit, framed tight on the middle, rewriting letter by letter', draw: (fb) => { MON.drawMonitorPOV(fb, 0, tidderPainter({phase: 'edit', editK: TIDDER_EDIT.length, tight: true})); }});
D({id: 'UI-EO', state: 'pov-copies', module: M + 'kits/eo-signing.ts', note: '21.02 [POV] NEDIB, pen raised, over an order off both ends of a very big desk; the copies; Neleh\'s egg', draw: (fb) => { MON.drawMonitorPOV(fb, 0, eoPainter({copies: 2, pen: 'raised', mouth: 'E', egg: true})); }});
D({id: 'UI-EO', state: 'pov-turn', module: M + 'kits/eo-signing.ts', note: '21.03 the real one turns to look at them: "When the hell did I say that?"; the stat row', draw: (fb) => { MON.drawMonitorPOV(fb, 0, eoPainter({copies: 2, pen: 'raised', turn: true, mouth: 'A', stat: 2, egg: true})); }});
D({id: 'ROOM-DARK-A3', state: 'three-nedibs', module: a3M + ' drawDarkA3 + kits/eo-signing.ts (mini)', note: '21.04 [2S·SCR] Mas, the Orb, three NEDIBs on the monitor; the iris on the one with the pen', draw: (fb) => { A3.drawDarkA3(fb, 0, {orb: {at: 'home', look: DPLATE_LOOK.grid}, outline: 'filled', mas: {look: -1, mouth: 'E'}, plate: {screen: eoPainter({copies: 2, pen: 'raised'})}}); }});
D({id: 'UI-EO', state: 'pov-sign', module: M + 'kits/eo-signing.ts', note: '21.05 [POV] he signs, in ink; the copies clap, and keep clapping', draw: (fb) => { MON.drawMonitorPOV(fb, 0, eoPainter({copies: 2, pen: 'sign', signK: 5, clap: true, egg: true})); }});
D({id: 'UI-DEVDAY', state: 'rise-tasya', module: M + 'kits/monitor-items.ts devdayPainter', note: '22.01 [POV] DevDay: the odometer up through the floor, 100,000,000 / WEEK; TASYA walks on', draw: (fb) => { MON.drawMonitorPOV(fb, 0, devdayPainter({rise: 3, tasya: 0.6})); }});
D({id: 'UI-DEVDAY', state: 'rise-1', module: M + 'kits/monitor-items.ts devdayPainter', note: '22.01 the odometer\'s first held step up; Tasya not yet on', draw: (fb) => { MON.drawMonitorPOV(fb, 0, devdayPainter({rise: 1, tasya: null, mouth: 'open'})); }});
D({id: 'UI-PHONE-HIGH', state: 'prompt-hover', module: M + 'kits/phone-high.ts', note: '22.02 [HIGH] How did the keynote go?; the thumb hovering over the reply strip (the new pose)', draw: (fb) => { drawPhoneHigh(fb, 0, {screen: 'prompt', thumb: 'hover'}); }});
D({id: 'UI-PHONE-HIGH', state: 'prompt-tap', module: M + 'kits/phone-high.ts', note: '22.02 then tapping: super', draw: (fb) => { drawPhoneHigh(fb, 0, {screen: 'prompt', thumb: 'tap'}); }});
D({id: 'ROOM-DARK-A3', state: 'phone-between', module: a3M + ' drawDarkA3', note: '22.03 [2S] Mas and the Orb, the phone between them; its iris lingers on the phone', draw: (fb) => { A3.drawDarkA3(fb, 0, {orb: {at: 'shoulder', look: DPLATE_LOOK.phone}, outline: true, mas: {arm: 'phone', head: 'down', mouth: 'E'}, plate: {phone: 'up', phoneScreen: phoneMini('prompt'), screen: devdayPainter({rise: 3, tasya: 1})}}); }});
D({id: 'UI-MONITOR', state: 'cold-open', module: M + 'kits/monitor-items.ts coldOpenPainter (rooms/apec-stage.ts: art-a\'s)', note: '23.01 [POV] the cold open\'s frame on the monitor: we\'ve caught up', draw: (fb) => { MON.drawMonitorPOV(fb, 0, coldOpenPainter()); }});
D({id: 'UI-PHONE-HIGH', state: 'reminder', module: M + 'kits/phone-high.ts', note: '23.02 [HIGH] Board sync · Fri 12:00, the four circles; the Orb\'s iris stops on the black square', draw: (fb) => { drawPhoneHigh(fb, 0, {screen: 'reminder', orb: ORB_CIRCLE_LOOKS[3]}); }});
D({id: 'ROOM-DARK-A3', state: 'reminder-dark', module: a3M + ' drawDarkA3', note: '23.03 [2S] the rail rolls to Friday; on the desk the reminder goes dark on its own', draw: (fb) => { A3.drawDarkA3(fb, 0, {orb: {at: 'shoulder', look: DPLATE_LOOK.phone}, outline: true, mas: {head: 'down'}, plate: {phone: 'up', phoneScreen: phoneMini('off'), screen: coldOpenPainter()}}); }});

// =================================================================== TAG
D({id: 'ROOM-DARK-A3', state: 'tag-arrive', module: a3M + ' drawDarkA3 + kits/mas-monitor.ts screenDim', note: '32.01 [2S] three marks in the wood now; the monitor dim, sound off, nothing to read', draw: (fb) => { A3.drawDarkA3(fb, 0, {orb: {at: 'shoulder', look: DPLATE_LOOK.mark3}, outline: true, mas: {}, plate: {tally: 3, screen: MON.screenDim}}); }});
D({id: 'PROP-EMIT', state: 'slot', module: a3M + ' drawSlotECU + kits/emit-cover.ts', note: '32.02 [INSERT] the rack slot ejects EMIT\'s year-end issue: CEO OF THE YEAR', draw: (fb) => { A3.drawSlotECU(fb, 0, {out: 3}); }});
D({id: 'PROP-EMIT', state: 'cover-mcu', module: a3M + ' drawCoverMCU', note: '32.03 [MCU] the cover held up beside his face: the same expression', draw: (fb) => { A3.drawCoverMCU(fb, 0, {}); }});
D({id: 'ROOM-DARK-A3', state: 'scan-twice', module: a3M + ' drawDarkA3 + kits/orb-toast.ts', note: '32.04 [2S] the fan re-sweeps the cover: re-scanning… (his own verdict came at once)', draw: (fb) => { A3.drawDarkA3(fb, 0, {orb: {at: 'shoulder', look: [-0.5, 0.2], scanning: true}, outline: true, mas: {}, plate: {tally: 3, screen: MON.screenDim}, cover: true, scan: {dir: 196, half: 9}, toasts: [{s: 'verified: human', k: 3, x: 92, y: 30}, {s: 're-scanning…', k: 3, x: 250, y: 44, kind: 'working'}]}); }});
D({id: 'PROP-EMIT', state: 'sizes', module: M + 'kits/emit-cover.ts', note: 'the cover: ecu · mcu · desk · wall (each its own layout)', draw: (fb) => { bench(fb); drawEmitCover(fb, 10, 4, 'ecu'); drawEmitCover(fb, 180, 30, 'mcu', {sheen: true}); drawEmitCover(fb, 310, 100, 'desk'); drawEmitCover(fb, 360, 110, 'wall'); }});
D({id: 'ROOM-TAG-WALL', state: 'pinned', module: a3M + ' drawBackWall', note: '32.07 [W] the back wall: the cover pinned up, the GUEST lanyard framed beside it', draw: (fb) => { A3.drawBackWall(fb, 0, {cover: true, frame: true, mas: 'reach', orb: true}); }});
D({id: 'ROOM-DARK-A3', state: 'thud-fall', module: a3M + ' drawDarkA3 + kits/grey-lady.ts drawPaperPlate', note: '33.01 [W] a newspaper drops flat onto the desk from above frame (held steps)', draw: (fb) => { A3.drawDarkA3(fb, 0, {orb: {at: 'shoulder'}, outline: true, mas: {}, plate: {tally: 3, screen: MON.screenDim}, paper: {phase: 'fall', k: 1}}); }});
D({id: 'ROOM-DARK-A3', state: 'thud', module: a3M + ' drawDarkA3', note: '33.01 THUD: flat on the desk (the room\'s 2 px shake and the hop are the shot\'s)', draw: (fb) => { A3.drawDarkA3(fb, 0, {orb: {at: 'shoulder'}, outline: true, mas: {}, plate: {tally: 3, screen: MON.screenDim}, paper: {phase: 'down', k: 0}}); }});
D({id: 'PROP-GREY-LADY', state: 'front-page', module: M + 'kits/grey-lady.ts drawFrontPageHigh', note: '33.02 [HIGH] a plain serif masthead, the columns, the clerk\'s stamp, held to read', draw: (fb) => { drawFrontPageHigh(fb, 0, {}); }});
D({id: 'ROOM-DARK-A3', state: 'profile-glass', module: a3M + ' drawProfileGlass', note: '33.04 [MCU·PF] Mas, his glass at his hand in frame, its water line flat: "noted."', draw: (fb) => { A3.drawProfileGlass(fb, 0, {mas: {mouth: 'rest'}}); }});
D({id: 'KIT-ORB-TOAST', state: 'toasts-fan', module: M + 'kits/orb-toast.ts', note: 'the Orb\'s toasts (verdict · working · note) and a scan fan on the sheet\'s backdrop', draw: (fb) => { bench(fb, PAL.N1, PAL.N0); drawScanFan(fb, 470, 20, 160, 10, {len: 400}); drawToast(fb, 20, 20, 'verified: human', 3); drawToast(fb, 20, 44, 're-scanning…', 3, {kind: 'working', f: 4}); drawToast(fb, 20, 68, 'catching up: 7 weeks', 3, {kind: 'note'}); drawToast(fb, 20, 96, 'verified: human', 0); label(fb, 'k 0 (2 px high, then settles)', 130, 98); }});
void blitImg; void drawBigFlame; void drawTasyaStage; void drawToast;
