// GENERATED by studio/src/episodes/ep02/pixel/tools/lock.py from studio/src/episodes/ep02/pixel/card/timeline.json
// (takes: none; plan: none). Do not hand-edit: re-run lock.py.
// Frames are segment frames (0 = the timeline's first beat; epIn = its episode frame). Shot-relative: lines[].s/e (first
// sound / after the last; s < 0 = it started earlier, carry = from an earlier shot, pre = a pre-lap under this shot),
// fs/fe (the take file), texts[].s/e, marks, spots[].k, onscreen[].s/e. mouth = [[frame from s, viseme]], words = [[w, f0, f1]].
// face = who shows a mouth in this framing ('lip' | 'room' | null). The layouts read this through ../types.ts.
/* eslint-disable */
import type {SegLock} from '../types';
export const LOCK: SegLock = {"seg":"card","label":"CARD","fps":24,"frames":48,"epIn":0,"mix":null,"source":{"timeline":"studio/src/episodes/ep02/pixel/card/timeline.json","takes":[],"plan":null},"cast":{},"refs":{},"soundMarks":[],"seqs":[{"id":"CARD","chapter":"CARD","title":"","place":"","time":"","s":0,"e":48,"cue":"","side":""}],"rails":[],"subs":[],"v4Ids":{},"shots":[{"id":"card.01","setup":"card.01","beats":["card.01"],"seq":"CARD","side":"MAS","badge":null,"whip":null,"tag":"CARD · the filename, typed on black","cls":"GFX","framing":"CARD · the filename, typed on black","move":"cut","s":0,"e":48,"plan":48,"v4":null,"verdict":"","does":"Black. A cursor; the filename types on quickly, ep1.1_her.wav, and the cursor blinks after it. Nothing else.","sound":"","chars":[],"lines":[],"texts":[],"marks":{},"kind":"card","set":"void","room":"card","style":"BASE","fx":[],"slate":false,"sideLabel":"","cues":[],"spots":[],"onscreen":[],"speak":[],"beatStarts":{"card.01":0},"names":[],"fg":null,"cast":[],"scene":"card","sceneS":0}],"scenes":[{"id":"card","s":0,"e":48,"shots":["card.01"]}]};
export default LOCK;
