"""Sample-set registry (lazy) + articulation maps.

Every set of the theme engine is here under the same name, plus the extra VSCO 2 CE folders the
SFX agent fetched (prefix 'sfx:'): real trombone falls, old-trombone shorts, marimba, xylophone,
flute staccato, bowed vibes, tenor-trombone vibrato, and a few unpitched woods and metals.

ART maps an instrument to its articulations (keyswitch-style): a Track built with
src=('art', 'vln') plays each note from the set named by note.x['art'] ('sus' by default).
"""
from functools import lru_cache

from .sampler import SampleSet

V = 'vsco2ce'
C = 'vcsl'

SETS = {
    # strings (VSCO 2 CE sections)
    'vln':       dict(pattern=f'{V}/Strings/Violin Section/susVib/*.wav', dyn_db=22),
    'vln_trem':  dict(pattern=f'{V}/Strings/Violin Section/Trem/*.wav', dyn_db=22),
    'vln_pizz':  dict(pattern=f'{V}/Strings/Violin Section/Pizz/*.wav', sustained=False, fine_tune=False, dyn_db=20),
    'vln_spic':  dict(pattern=f'{V}/Strings/Violin Section/Spic/*.wav', sustained=False, fine_tune=False, dyn_db=20),
    'vla':       dict(pattern=f'{V}/Strings/Viola Section/susvib/*.wav', dyn_db=22),
    'vla_trem':  dict(pattern=f'{V}/Strings/Viola Section/trem/*.wav', dyn_db=22),
    'vla_pizz':  dict(pattern=f'{V}/Strings/Viola Section/pizz/*.wav', sustained=False, fine_tune=False, dyn_db=20),
    'vla_spic':  dict(pattern=f'{V}/Strings/Viola Section/spic/*.wav', sustained=False, fine_tune=False, dyn_db=20),
    'vc':        dict(pattern=f'{V}/Strings/Cello Section/susvib/*.wav', dyn_db=22),
    'vc_trem':   dict(pattern=f'{V}/Strings/Cello Section/trem/*.wav', dyn_db=22),
    'vc_pizz':   dict(pattern=f'{V}/Strings/Cello Section/pizzT/*.wav', sustained=False, fine_tune=False, dyn_db=20),
    'vc_spic':   dict(pattern=f'{V}/Strings/Cello Section/spic/*.wav', sustained=False, fine_tune=False, dyn_db=20),
    'cb':        dict(pattern=f'{V}/Strings/Solo Contrabass/SusVib/*.wav', dyn_db=22),
    'cb_pizz':   dict(pattern=f'{V}/Strings/Solo Contrabass/Pizz/*.wav', sustained=False, fine_tune=False, dyn_db=18),
    'cb_spic':   dict(pattern=f'{V}/Strings/Solo Contrabass/Spic/*.wav', sustained=False, fine_tune=False, dyn_db=18),
    'svln':      dict(pattern=f'{V}/Strings/Solo Violin/Arco Vib/*.wav', dyn_names=True, dyn_db=20),
    'harp':      dict(pattern=f'{V}/Strings/Harp/*.wav', dyn_names=True, sustained=False, dyn_db=18,
                      max_stretch=4),       # the mp layer is ONE G1 and the f layer E1/D7/F7: never stretch them far
    # brass
    'tpt':       dict(pattern=f'{V}/Brass/Trumpet/sus/*.wav', dyn_db=20),
    'tpt_vib':   dict(pattern=f'{V}/Brass/Trumpet/susvib/*.wav', dyn_db=20),
    'tpt_stac':  dict(pattern=f'{V}/Brass/Trumpet/stac/*.wav', sustained=False, fine_tune=False, dyn_db=18),
    'tpt_harmon': dict(pattern=f'{V}/Brass/Trumpet/harmonM-sus/*.wav', dyn_db=18),
    'tpt_straight': dict(pattern=f'{V}/Brass/Trumpet/straightM-sus/*.wav', dyn_db=18),
    'hn':        dict(pattern=f'{V}/Brass/F Horn/sus/*.wav', dyn_db=22),
    'hn_stac':   dict(pattern=f'{V}/Brass/F Horn/stac/*.wav', sustained=False, fine_tune=False, dyn_db=18),
    'hn_mute':   dict(pattern=f'{V}/Brass/F Horn/mute/*.wav', dyn_db=18),
    'tbn':       dict(pattern=f'{V}/Brass/Tenor Trombone/sus/*.wav', dyn_db=22),
    'tbn_vib':   dict(pattern=f'{V}/Brass/Tenor Trombone/vib/*.wav', dyn_db=22),
    'tbn_stac':  dict(pattern=f'{V}/Brass/Tenor Trombone/stac/*.wav', sustained=False, fine_tune=False, dyn_db=18),
    'tbn_fall':  dict(pattern='sfx:Brass/OldTrombone/Fall/*.wav', vel_re=None, sustained=False, fine_tune=False,
                      dyn_db=16),
    'tbn_short': dict(pattern='sfx:Brass/OldTrombone/Short/*.wav', sustained=False, fine_tune=False, dyn_db=18),
    'tuba':      dict(pattern=f'{V}/Brass/Tuba/sus/*.wav', dyn_db=22),
    'tuba_stac': dict(pattern=f'{V}/Brass/Tuba/stac/*.wav', sustained=False, fine_tune=False, dyn_db=18),
    # winds / reeds
    'cl':        dict(pattern=f'{V}/Woodwinds/Clarinet/susLong/*.wav', dyn_db=20),
    'cl_stac':   dict(pattern=f'{V}/Woodwinds/Clarinet/stac/*.wav', sustained=False, fine_tune=False, dyn_db=18),
    'fl':        dict(pattern=f'{V}/Woodwinds/Flute/susvib/*.wav', dyn_db=18),
    'fl_nv':     dict(pattern=f'{V}/Woodwinds/Flute/susNV/*.wav', dyn_db=18),
    'fl_stac':   dict(pattern='sfx:Woodwinds/Flute/stac/*.wav', sustained=False, fine_tune=False, dyn_db=18),
    'bsn':       dict(pattern=f'{V}/Woodwinds/Bassoon/sus/*.wav', dyn_db=20),
    'tsax':      dict(pattern=f'{C}/Aerophones/Reed Aerophones/Tenor Saxophone/Non-Vibrato/*.wav', vel_re=r'_vl(\d+)', dyn_db=20),
    'tsax_vib':  dict(pattern=f'{C}/Aerophones/Reed Aerophones/Tenor Saxophone/Vibrato/*.wav', vel_re=None, dyn_db=20),
    'tsax_stac': dict(pattern=f'{C}/Aerophones/Reed Aerophones/Tenor Saxophone/Staccato/*.wav', vel_re=r'_vl(\d+)', sustained=False, fine_tune=False, dyn_db=18),
    # mallets / bells
    'glock':     dict(pattern=f'{V}/Percussion/Glock/*.wav', vel_re=None, sustained=False, octave_fix=12, fine_tune=False, cents_override=12.0, dyn_db=18),
    'vibes':     dict(pattern=f'{C}/Idiophones/Struck Idiophones/Vibraphone/Soft Mallets/*.wav', vel_re=r'_v(\d+)', sustained=False, dyn_db=20),
    'vibes_hard': dict(pattern=f'{C}/Idiophones/Struck Idiophones/Vibraphone/Hard Mallets/*.wav', vel_re=r'_v(\d+)', sustained=False, dyn_db=20),
    'vibes_bowed': dict(pattern=f'{C}/Idiophones/Struck Idiophones/Vibraphone/Bowed/*.wav', vel_re=None, dyn_db=16),
    'chimes':    dict(pattern=f'{C}/Idiophones/Struck Idiophones/Tubular Bells 1/*.wav', dyn_names=True, sustained=False, octave_fix=12, fine_tune=False, dyn_db=18),
    'marimba':   dict(pattern='sfx:Percussion/Marimba/*.wav', vel_re=None, sustained=False, dyn_db=20),
    'xylo':      dict(pattern='sfx:Percussion/Xylo/*.wav', vel_re=None, sustained=False, fine_tune=False, dyn_db=18),
}

UNPITCHED = {
    'timp':       dict(pattern=f'{V}/Percussion/Timpani/Timpani*_Hit_*.wav', exclude=r'Timpani5', vel_re=r'_v(\d+)', sustained=False, dyn_db=24),
    'crash':      dict(pattern=f'{V}/Percussion/cymbal-crash1_*.wav', dyn_names=True, sustained=False, dyn_db=20),
    'suscym':     dict(pattern=f'{V}/Percussion/susCymb1-hit_*.wav', vel_re=r'-v(\d+)|_v(\d+)', sustained=False, dyn_db=20),
    'suscym_stick': dict(pattern=f'{V}/Percussion/susCymb1-hitstick*.wav', vel_re=r'_v(\d+)', sustained=False, dyn_db=20),
    'bdrum':      dict(pattern=f'{V}/Percussion/BDrumNewhit_*.wav', vel_re=r'_v(\d+)', sustained=False, dyn_db=26),
    'snare':      dict(pattern=f'{V}/Percussion/Snare2-HitSN_*.wav', vel_re=r'_v(\d+)', sustained=False, dyn_db=24),
    'snare_taps': dict(pattern=f'{V}/Percussion/Snare2-taps_*.wav', vel_re=r'_v(\d+)', sustained=False, dyn_db=20),
    'gong':       dict(pattern=f'{V}/Percussion/gongHit_*.wav', dyn_names=True, sustained=False, dyn_db=20),
    'hat':        dict(pattern=f'{C}/Idiophones/Struck Idiophones/Hi-Hat Cymbal/HiHat_HitC_*.wav', vel_re=r'_v(\d+)', sustained=False, dyn_db=20),
    'hat_foot':   dict(pattern=f'{C}/Idiophones/Struck Idiophones/Hi-Hat Cymbal/HiHat_Close_*.wav', vel_re=None, sustained=False, dyn_db=18),
    'ride2':      dict(pattern=f'{C}/Idiophones/Struck Idiophones/Suspended Cymbal 2/susCymb2_hit_stick_*.wav', dyn_names=True, sustained=False, dyn_db=18),
    'cym_swell':  dict(pattern=f'{C}/Idiophones/Struck Idiophones/Suspended Cymbal 2/susCymb2_cresc_*.wav', vel_re=None, sustained=True, dyn_db=10),
    # extra woods / metals from the SFX pack
    'claves':     dict(pattern='sfx:VSCO 1 Percussion/varWood/claves_mp.wav', vel_re=None, sustained=False, dyn_db=18),
    'woodclick':  dict(pattern='sfx:VSCO 1 Percussion/varWood/wood_click_*.wav', vel_re=None, sustained=False, dyn_db=18),
    'cabasa':     dict(pattern='sfx:VSCO 1 Percussion/varMetal/various/cabasa_*.wav', vel_re=None, sustained=False, dyn_db=18),
    'rimshot':    dict(pattern='sfx:VSCO 1 Percussion/drums/snare/drum1/snare1_rimshot_mf.wav', vel_re=None, sustained=False, dyn_db=18),
    'bdrum_muted': dict(pattern='sfx:VSCO 1 Percussion/drums/bass/bdrum_muted_*.wav', vel_re=None, sustained=False, dyn_db=22),
}

# articulation maps (keyswitches).  'sus' is the default; 'leg' uses the sustain set with the legato
# crossfade from articulations.legato().
ART = {
    'vln':  {'sus': 'vln', 'leg': 'vln', 'trem': 'vln_trem', 'pizz': 'vln_pizz', 'spic': 'vln_spic'},
    'vla':  {'sus': 'vla', 'leg': 'vla', 'trem': 'vla_trem', 'pizz': 'vla_pizz', 'spic': 'vla_spic'},
    'vc':   {'sus': 'vc', 'leg': 'vc', 'trem': 'vc_trem', 'pizz': 'vc_pizz', 'spic': 'vc_spic'},
    'cb':   {'sus': 'cb', 'leg': 'cb', 'pizz': 'cb_pizz', 'spic': 'cb_spic'},
    'svln': {'sus': 'svln', 'leg': 'svln'},
    'tpt':  {'sus': 'tpt', 'leg': 'tpt', 'vib': 'tpt_vib', 'stab': 'tpt_stac', 'stac': 'tpt_stac',
             'harmon': 'tpt_harmon', 'straight': 'tpt_straight'},
    'hn':   {'sus': 'hn', 'leg': 'hn', 'stab': 'hn_stac', 'stac': 'hn_stac', 'mute': 'hn_mute'},
    'tbn':  {'sus': 'tbn', 'leg': 'tbn', 'vib': 'tbn_vib', 'stab': 'tbn_stac', 'stac': 'tbn_stac',
             'fall': 'tbn_fall', 'short': 'tbn_short'},
    'tuba': {'sus': 'tuba', 'leg': 'tuba', 'stab': 'tuba_stac', 'stac': 'tuba_stac'},
    'cl':   {'sus': 'cl', 'leg': 'cl', 'stac': 'cl_stac', 'stab': 'cl_stac'},
    'fl':   {'sus': 'fl', 'leg': 'fl', 'nv': 'fl_nv', 'stac': 'fl_stac', 'stab': 'fl_stac'},
    'tsax': {'sus': 'tsax', 'leg': 'tsax', 'vib': 'tsax_vib', 'stac': 'tsax_stac', 'stab': 'tsax_stac'},
    'vibes': {'sus': 'vibes', 'hard': 'vibes_hard', 'bowed': 'vibes_bowed'},
}

# per-articulation render defaults (a note's own x[...] always wins)
ART_DEFAULTS = {
    'sus':   dict(rel=0.35),
    'leg':   dict(rel=0.35),
    'vib':   dict(rel=0.35),
    'trem':  dict(rel=0.30),
    'pizz':  dict(rel=0.20, latency_ms=6.0),
    'spic':  dict(rel=0.12),
    'stab':  dict(rel=0.10),
    'stac':  dict(rel=0.12),
    'short': dict(rel=0.12),
    'fall':  dict(rel=0.10),
    'harmon': dict(rel=0.35, latency_ms=10.0),
    'straight': dict(rel=0.35),
    'mute':  dict(rel=0.35),
    'nv':    dict(rel=0.35),
    'hard':  dict(rel=1.4),
    'bowed': dict(rel=0.8),
}

# credits per sample source (the cue sheet lists the ones a track actually used)
CREDITS = {
    'vsco2ce': 'Orchestral samples: VSCO 2 CE by Versilian Studios (CC0 1.0)',
    'vcsl': 'VCSL by Versilian Studios (CC0 1.0)',
    'sfx:': 'Orchestral samples: VSCO 2 CE by Versilian Studios (CC0 1.0)',
    'salamander': 'Salamander Grand Piano by Alexander Holm (CC BY 3.0) -- ATTRIBUTION REQUIRED',
    'upright_kw': 'Upright Piano KW by FreePats (CC0 1.0; credit anyway)',
    'generaluser': 'GeneralUser GS by S. Christian Collins (free for any music use)',
}


def credit_for_set(name: str) -> str:
    spec = SETS.get(name) or UNPITCHED.get(name) or {}
    pat = spec.get('pattern', '')
    if pat.startswith('sfx:') or pat.startswith(V):
        return CREDITS['vsco2ce']
    if pat.startswith(C):
        return CREDITS['vcsl']
    return ''


@lru_cache(maxsize=None)
def get(name: str) -> SampleSet:
    if name == 'timp':
        return timpani()
    if name in SETS:
        kw = dict(SETS[name])
        if name in TUNING:
            kw.setdefault('tuning', TUNING[name])
        return SampleSet(name, **kw)
    if name in UNPITCHED:
        kw = dict(UNPITCHED[name])
        return SampleSet(name, pitched=False, **kw)
    raise KeyError(f'unknown sample set {name!r} (see engine/library.py SETS / UNPITCHED)')


def art_set(inst: str, art: str | None) -> str:
    """Resolve (instrument, articulation) -> sample-set name."""
    amap = ART[inst]
    a = art or 'sus'
    if a not in amap:
        raise KeyError(f'{inst} has no articulation {a!r}; has {sorted(amap)}')
    return amap[a]


@lru_cache(maxsize=None)
def timpani() -> SampleSet:
    """Timpani files carry no note names: detect each drum's pitch and treat as pitched."""
    import numpy as np
    from .sampler import load_wav, trim_lead, detect_f0
    s = SampleSet('timp', pitched=False, **UNPITCHED['timp'])
    for e in s.entries:
        x = trim_lead(load_wav(e['path']))
        seg = x[:, int(0.05 * 48000):int(0.9 * 48000)]
        f0 = detect_f0(seg, 55, 260)
        e['pitch'] = float(69 + 12 * np.log2(f0 / 440.0))
        e['cents'] = 0.0
    import re as _re
    groups = {}
    for e in s.entries:
        k = _re.search(r'Timpani(\d)', e['path']).group(1)
        groups.setdefault(k, []).append(e['pitch'])
    for e in s.entries:
        k = _re.search(r'Timpani(\d)', e['path']).group(1)
        e['pitch'] = float(np.median(groups[k]))
    s.pitched = True
    return s


# ====================================================================== per-sample tuning (fix 2, 2026-09-26)
# MEASURED deviation of each sample from the pitch it is mapped to, in cents (negative = the recording is flat),
# by engine/tuning.py (harmonic-comb fundamental over the body of the note; see its docstring).  SampleSet
# subtracts it when it transposes, so the note sounds at the written pitch; the sample files are untouched.
# These sets were mistuned in batch 1: the harp (octave-wrong automatic estimates, so B1-D2, G1 and B5-F7 were
# never corrected), the clarinet (its 'F#5' sample is an F5: -1 semitone; the staccato set was never
# fine-tuned and reads 20-45 cents flat below D5) and every pizzicato set (never fine-tuned; up to 42 cents).
# Re-measure:  ../.venv-theme/bin/python -m engine.tuning --block      Check:  ... -m engine.tuning --verify
# Ensemble pizzicato is a chorus of players, so its centre carries about +-5 cents of measurement uncertainty.
TUNING = {
    'harp': {
        'KSHarp_E1_f.wav': -22.0,
        'KSHarp_G1_mp.wav': -26.0,
        'KSHarp_B1_mf.wav': -16.3,
        'KSHarp_D2_mf.wav': -4.2,
        'KSHarp_F2_mf.wav': -7.3,
        'KSHarp_A2_mf.wav': -3.8,
        'KSHarp_C3_mf.wav': -2.8,
        'KSHarp_E3_mf.wav': -4.5,
        'KSHarp_G3_mf.wav': -8.5,
        'KSHarp_B3_mf.wav': -12.9,
        'KSHarp_D4_mf.wav': -12.3,
        'KSHarp_F4_mf.wav': -1.0,
        'KSHarp_A4_mf.wav': -9.2,
        'KSHarp_C5_mf.wav': -11.4,
        'KSHarp_E5_mf.wav': -11.4,
        'KSHarp_G5_mf.wav': -5.7,
        'KSHarp_B5_mf.wav': -8.4,
        'KSHarp_D6_mf.wav': -8.0,
        'KSHarp_F6_mf.wav': -5.7,
        'KSHarp_A6_mf.wav': -19.0,
        'KSHarp_B6_mf.wav': -10.8,
        'KSHarp_D7_f.wav': -8.1,
        'KSHarp_F7_f.wav': -30.7,
    },
    'cl': {
        'DCClar_susLong_D2_v1_rr1_sum.wav': +1.2,
        'DCClar_susLong_D2_v2_rr1_sum.wav': +3.6,
        'DCClar_susLong_D2_v3_rr1_sum.wav': +4.3,
        'DCClar_susLong_F2_v1_rr1_sum.wav': +2.3,
        'DCClar_susLong_F2_v2_rr1_sum.wav': +1.5,
        'DCClar_susLong_F2_v3_rr1_sum.wav': +2.6,
        'DCClar_susLong_A#2_v1_rr1_sum.wav': +4.4,
        'DCClar_susLong_A#2_v2_rr1_sum.wav': +0.8,
        'DCClar_susLong_A#2_v3_rr1_sum.wav': +1.3,
        'DCClar_susLong_D3_v1_rr1_sum.wav': +5.1,
        'DCClar_susLong_D3_v2_rr1_sum.wav': +2.3,
        'DCClar_susLong_D3_v3_rr1_sum.wav': +3.0,
        'DCClar_susLong_F3_v1_rr1_sum.wav': +1.1,
        'DCClar_susLong_F3_v2_rr1_sum.wav': +5.6,
        'DCClar_susLong_F3_v3_rr1_sum.wav': +1.1,
        'DCClar_susLong_A#3_v1_rr1_sum.wav': +4.7,
        'DCClar_susLong_A#3_v2_rr1_sum.wav': +2.6,
        'DCClar_susLong_A#3_v3_rr1_sum.wav': +2.1,
        'DCClar_susLong_D4_v1_rr1_sum.wav': +3.3,
        'DCClar_susLong_D4_v2_rr1_sum.wav': +2.7,
        'DCClar_susLong_D4_v3_rr1_sum.wav': +2.9,
        'DCClar_susLong_F4_v1_rr1_sum.wav': +1.9,
        'DCClar_susLong_F4_v2_rr1_sum.wav': +4.6,
        'DCClar_susLong_F4_v3_rr1_sum.wav': +1.8,
        'DCClar_susLong_A#4_v1_rr1_sum.wav': +5.2,
        'DCClar_susLong_A#4_v2_rr1_sum.wav': +3.7,
        'DCClar_susLong_A#4_v3_rr1_sum.wav': +3.1,
        'DCClar_susLong_D5_v1_rr1_sum.wav': +3.4,
        'DCClar_susLong_D5_v2_rr1_sum.wav': +6.3,
        'DCClar_susLong_D5_v3_rr1_sum.wav': +0.1,
        'DCClar_susLong_F#5_v1_rr1_sum.wav': -99.5,
        'DCClar_susLong_F#5_v2_rr1_sum.wav': -98.7,
        'DCClar_susLong_F#5_v3_rr1_sum.wav': -102.8,
    },
    'cl_stac': {
        'DCClar_stac_D2_v1_rr1_sum.wav': -30.7,
        'DCClar_stac_D2_v1_rr2_sum.wav': -31.0,
        'DCClar_stac_D2_v2_rr1_sum.wav': -30.6,
        'DCClar_stac_D2_v2_rr2_sum.wav': -33.3,
        'DCClar_stac_D2_v3_rr1_sum.wav': -23.6,
        'DCClar_stac_D2_v3_rr2_sum.wav': -23.5,
        'DCClar_stac_F2_v1_rr1_sum.wav': +8.3,
        'DCClar_stac_F2_v1_rr2_sum.wav': +10.0,
        'DCClar_stac_F2_v2_rr1_sum.wav': -31.0,
        'DCClar_stac_F2_v2_rr2_sum.wav': -23.2,
        'DCClar_stac_F2_v3_rr1_sum.wav': -22.6,
        'DCClar_stac_F2_v3_rr2_sum.wav': -23.2,
        'DCClar_stac_A#2_v1_rr1_sum.wav': -30.6,
        'DCClar_stac_A#2_v1_rr2_sum.wav': -32.7,
        'DCClar_stac_A#2_v2_rr1_sum.wav': -44.6,
        'DCClar_stac_A#2_v2_rr2_sum.wav': -41.5,
        'DCClar_stac_A#2_v3_rr1_sum.wav': -34.0,
        'DCClar_stac_A#2_v3_rr2_sum.wav': -34.7,
        'DCClar_stac_D3_v1_rr1_sum.wav': -29.2,
        'DCClar_stac_D3_v1_rr2_sum.wav': -29.4,
        'DCClar_stac_D3_v2_rr1_sum.wav': -35.6,
        'DCClar_stac_D3_v2_rr2_sum.wav': -35.7,
        'DCClar_stac_D3_v3_rr1_sum.wav': -33.0,
        'DCClar_stac_D3_v3_rr2_sum.wav': -33.9,
        'DCClar_stac_F3_v1_rr1_sum.wav': -31.7,
        'DCClar_stac_F3_v1_rr2_sum.wav': -22.3,
        'DCClar_stac_F3_v2_rr1_sum.wav': -31.5,
        'DCClar_stac_F3_v2_rr2_sum.wav': -28.0,
        'DCClar_stac_F3_v3_rr1_sum.wav': -26.5,
        'DCClar_stac_F3_v3_rr2_sum.wav': -25.1,
        'DCClar_stac_A#3_v1_rr1_sum.wav': -7.7,
        'DCClar_stac_A#3_v1_rr2_sum.wav': -6.7,
        'DCClar_stac_A#3_v2_rr1_sum.wav': -14.2,
        'DCClar_stac_A#3_v2_rr2_sum.wav': -8.5,
        'DCClar_stac_A#3_v3_rr1_sum.wav': -9.9,
        'DCClar_stac_A#3_v3_rr2_sum.wav': -13.7,
        'DCClar_stac_D4_v1_rr1_sum.wav': -18.1,
        'DCClar_stac_D4_v1_rr2_sum.wav': -21.8,
        'DCClar_stac_D4_v2_rr1_sum.wav': -22.9,
        'DCClar_stac_D4_v2_rr2_sum.wav': -19.0,
        'DCClar_stac_D4_v3_rr1_sum.wav': -16.8,
        'DCClar_stac_D4_v3_rr2_sum.wav': -14.2,
        'DCClar_stac_F4_v1_rr1_sum.wav': -17.1,
        'DCClar_stac_F4_v1_rr2_sum.wav': -21.6,
        'DCClar_stac_F4_v2_rr1_sum.wav': -22.5,
        'DCClar_stac_F4_v2_rr2_sum.wav': -22.7,
        'DCClar_stac_F4_v3_rr1_sum.wav': -14.6,
        'DCClar_stac_F4_v3_rr2_sum.wav': -9.4,
        'DCClar_stac_A#4_v1_rr1_sum.wav': -17.6,
        'DCClar_stac_A#4_v1_rr2_sum.wav': -21.7,
        'DCClar_stac_A#4_v2_rr1_sum.wav': -2.9,
        'DCClar_stac_A#4_v2_rr2_sum.wav': -3.3,
        'DCClar_stac_A#4_v3_rr1_sum.wav': +3.6,
        'DCClar_stac_A#4_v3_rr2_sum.wav': +4.9,
        'DCClar_stac_D5_v2_rr1_sum.wav': -1.6,
        'DCClar_stac_D5_v2_rr2_sum.wav': -9.6,
        'DCClar_stac_D5_v3_rr1_sum.wav': -12.4,
        'DCClar_stac_D5_v3_rr2_sum.wav': -8.5,
        'DCClar_stac_F5_v1_rr1_sum.wav': -3.6,
        'DCClar_stac_F5_v1_rr2_sum.wav': -7.7,
        'DCClar_stac_F5_v2_rr1_sum.wav': -4.0,
        'DCClar_stac_F5_v2_rr2_sum.wav': -5.8,
        'DCClar_stac_F5_v3_rr1_sum.wav': +5.5,
        'DCClar_stac_F5_v3_rr2_sum.wav': +0.6,
    },
    'vln_pizz': {
        'VlnEns_Pizz_G2_v1_rr1.wav': +1.7,
        'VlnEns_Pizz_G2_v1_rr2.wav': -3.4,
        'VlnEns_Pizz_G2_v2_rr1.wav': -4.4,
        'VlnEns_Pizz_G2_v2_rr2.wav': -2.3,
        'VlnEns_Pizz_A2_v1_rr1.wav': -0.2,
        'VlnEns_Pizz_A2_v1_rr2.wav': -5.9,
        'VlnEns_Pizz_A2_v2_rr1.wav': -7.1,
        'VlnEns_Pizz_A2_v2_rr2.wav': -8.7,
        'VlnEns_Pizz_B2_v1_rr1.wav': -3.8,
        'VlnEns_Pizz_B2_v1_rr2.wav': -26.0,
        'VlnEns_Pizz_B2_v2_rr1.wav': -6.4,
        'VlnEns_Pizz_B2_v2_rr2.wav': -15.0,
        'VlnEns_Pizz_D3_v1_rr1.wav': +1.5,
        'VlnEns_Pizz_D3_v1_rr2.wav': +2.9,
        'VlnEns_Pizz_D3_v2_rr1.wav': -7.2,
        'VlnEns_Pizz_D3_v2_rr2.wav': -8.2,
        'VlnEns_Pizz_F#3_v1_rr1.wav': -7.8,
        'VlnEns_Pizz_F#3_v1_rr2.wav': -12.2,
        'VlnEns_Pizz_F#3_v2_rr1.wav': +0.2,
        'VlnEns_Pizz_F#3_v2_rr2.wav': -4.4,
        'VlnEns_Pizz_A3_v1_rr1.wav': +0.8,
        'VlnEns_Pizz_A3_v1_rr2.wav': -5.5,
        'VlnEns_Pizz_A3_v2_rr1.wav': -1.6,
        'VlnEns_Pizz_A3_v2_rr2.wav': +5.6,
        'VlnEns_Pizz_C4_v1_rr1.wav': +4.9,
        'VlnEns_Pizz_C4_v1_rr2.wav': +14.5,
        'VlnEns_Pizz_C4_v2_rr1.wav': +12.8,
        'VlnEns_Pizz_C4_v2_rr2.wav': +4.1,
        'VlnEns_Pizz_E4_v1_rr1.wav': -12.3,
        'VlnEns_Pizz_E4_v1_rr2.wav': -5.3,
        'VlnEns_Pizz_E4_v2_rr1.wav': -5.0,
        'VlnEns_Pizz_E4_v2_rr2.wav': -6.7,
        'VlnEns_Pizz_G4_v1_rr1.wav': -4.1,
        'VlnEns_Pizz_G4_v1_rr2.wav': -2.9,
        'VlnEns_Pizz_G4_v2_rr1.wav': +8.4,
        'VlnEns_Pizz_G4_v2_rr2.wav': +4.6,
        'VlnEns_Pizz_B4_v1_rr1.wav': -11.8,
        'VlnEns_Pizz_B4_v1_rr2.wav': +2.8,
        'VlnEns_Pizz_B4_v2_rr1.wav': -3.0,
        'VlnEns_Pizz_B4_v2_rr2.wav': -3.5,
        'VlnEns_Pizz_D5_v1_rr1.wav': +3.0,
        'VlnEns_Pizz_D5_v1_rr2.wav': +6.7,
        'VlnEns_Pizz_D5_v2_rr1.wav': -9.8,
        'VlnEns_Pizz_D5_v2_rr2.wav': +13.7,
    },
    'vla_pizz': {
        'ViolaEns_pizz_C2_v1_rr1.wav': +13.9,
        'ViolaEns_pizz_C2_v1_rr2.wav': -2.2,
        'ViolaEns_pizz_C2_v2_rr1.wav': -4.0,
        'ViolaEns_pizz_C2_v2_rr2.wav': -3.1,
        'ViolaEns_pizz_E2_v1_rr1.wav': +4.7,
        'ViolaEns_pizz_E2_v1_rr2.wav': +11.0,
        'ViolaEns_pizz_E2_v2_rr1.wav': -2.7,
        'ViolaEns_pizz_E2_v2_rr2.wav': -8.4,
        'ViolaEns_pizz_G2_v1_rr1.wav': -11.4,
        'ViolaEns_pizz_G2_v1_rr2.wav': -6.0,
        'ViolaEns_pizz_G2_v2_rr1.wav': -0.7,
        'ViolaEns_pizz_G2_v2_rr2.wav': +4.6,
        'ViolaEns_pizz_B2_v1_rr1.wav': -17.0,
        'ViolaEns_pizz_B2_v1_rr2.wav': -2.5,
        'ViolaEns_pizz_B2_v2_rr1.wav': -15.0,
        'ViolaEns_pizz_B2_v2_rr2.wav': -3.4,
        'ViolaEns_pizz_D3_v1_rr1.wav': -11.6,
        'ViolaEns_pizz_D3_v1_rr2.wav': -18.8,
        'ViolaEns_pizz_D3_v2_rr1.wav': -5.3,
        'ViolaEns_pizz_D3_v2_rr2.wav': -9.2,
        'ViolaEns_pizz_F3_v1_rr1.wav': +3.1,
        'ViolaEns_pizz_F3_v1_rr2.wav': +0.9,
        'ViolaEns_pizz_F3_v2_rr1.wav': -5.3,
        'ViolaEns_pizz_F3_v2_rr2.wav': +8.7,
        'ViolaEns_pizz_A3_v1_rr1.wav': +14.9,
        'ViolaEns_pizz_A3_v1_rr2.wav': +10.7,
        'ViolaEns_pizz_A3_v2_rr1.wav': -0.9,
        'ViolaEns_pizz_A3_v2_rr2.wav': -2.6,
        'ViolaEns_pizz_C4_v1_rr1.wav': +0.4,
        'ViolaEns_pizz_C4_v1_rr2.wav': -4.5,
        'ViolaEns_pizz_C4_v2_rr1.wav': -8.6,
        'ViolaEns_pizz_C4_v2_rr2.wav': -10.9,
        'ViolaEns_pizz_E4_v1_rr1.wav': +8.1,
        'ViolaEns_pizz_E4_v1_rr2.wav': -1.0,
        'ViolaEns_pizz_E4_v2_rr1.wav': -0.1,
        'ViolaEns_pizz_E4_v2_rr2.wav': -9.1,
        'ViolaEns_pizz_G4_v1_rr1.wav': +7.0,
        'ViolaEns_pizz_G4_v1_rr2.wav': -4.4,
        'ViolaEns_pizz_G4_v2_rr1.wav': -9.0,
        'ViolaEns_pizz_G4_v2_rr2.wav': +20.9,
        'ViolaEns_pizz_B4_v1_rr1.wav': +3.0,
        'ViolaEns_pizz_B4_v1_rr2.wav': +6.6,
        'ViolaEns_pizz_B4_v2_rr1.wav': -6.3,
        'ViolaEns_pizz_B4_v2_rr2.wav': -10.6,
        'ViolaEns_pizz_D5_v1_rr1.wav': -21.8,
        'ViolaEns_pizz_D5_v1_rr2.wav': -4.7,
    },
    'vc_pizz': {
        'pizzT_C1_v1_RR1.wav': +3.0,
        'pizzT_C1_v1_RR2.wav': -2.0,
        'pizzT_C1_v2_RR1.wav': -3.4,
        'pizzT_C1_v2_RR2.wav': -1.5,
        'pizzT_E1_v1_RR1.wav': -5.8,
        'pizzT_E1_v1_RR2.wav': +2.1,
        'pizzT_E1_v2_RR1.wav': +1.6,
        'pizzT_E1_v2_RR2.wav': +6.0,
        'pizzT_G1_v1_RR1.wav': -1.1,
        'pizzT_G1_v1_RR2.wav': -8.6,
        'pizzT_G1_v2_RR1.wav': -1.1,
        'pizzT_G1_v2_RR2.wav': -1.1,
        'pizzT_B1_v1_RR1.wav': -10.9,
        'pizzT_B1_v1_RR2.wav': -2.5,
        'pizzT_B1_v2_RR1.wav': -9.6,
        'pizzT_B1_v2_RR2.wav': -8.3,
        'pizzT_D2_v1_RR1.wav': -2.2,
        'pizzT_D2_v1_RR2.wav': -0.6,
        'pizzT_D2_v2_RR1.wav': +0.5,
        'pizzT_D2_v2_RR2.wav': +3.4,
        'pizzT_F2_v1_RR1.wav': +7.1,
        'pizzT_F2_v1_RR2.wav': +10.9,
        'pizzT_F2_v2_RR1.wav': +4.5,
        'pizzT_F2_v2_RR2.wav': +16.1,
        'pizzT_A2_v1_RR1.wav': +4.7,
        'pizzT_A2_v1_RR2.wav': +0.5,
        'pizzT_A2_v2_RR1.wav': +4.9,
        'pizzT_A2_v2_RR2.wav': +2.4,
        'pizzT_C3_v1_RR1.wav': +2.0,
        'pizzT_C3_v1_RR2.wav': +0.6,
        'pizzT_C3_v2_RR1.wav': +1.4,
        'pizzT_C3_v2_RR2.wav': -0.3,
        'pizzT_E3_v1_RR1.wav': -3.5,
        'pizzT_E3_v1_RR2.wav': +1.0,
        'pizzT_E3_v2_RR1.wav': +4.5,
        'pizzT_E3_v2_RR2.wav': -2.1,
        'pizzT_G3_v1_RR1.wav': -7.1,
        'pizzT_G3_v1_RR2.wav': +0.4,
        'pizzT_G3_v2_RR1.wav': +2.4,
        'pizzT_G3_v2_RR2.wav': +3.3,
        'pizzT_B3_v1_RR1.wav': -2.6,
        'pizzT_B3_v1_RR2.wav': -0.3,
        'pizzT_B3_v2_RR1.wav': +2.3,
        'pizzT_B3_v2_RR2.wav': +0.8,
        'pizzT_D4_v1_RR1.wav': -4.7,
        'pizzT_D4_v1_RR2.wav': -12.7,
        'pizzT_D4_v2_RR1.wav': -6.7,
        'pizzT_D4_v2_RR2.wav': +2.0,
        'pizzT_F4_v1_RR1.wav': +22.9,
        'pizzT_F4_v1_RR2.wav': +19.9,
        'pizzT_F4_v2_RR1.wav': -3.6,
        'pizzT_F4_v2_RR2.wav': +11.8,
    },
    'cb_pizz': {
        'BKCtbss_Pizz_E0_v1_rr1.wav': -2.0,
        'BKCtbss_Pizz_E0_v1_rr2.wav': -4.2,
        'BKCtbss_Pizz_E0_v3_rr1.wav': -0.0,
        'BKCtbss_Pizz_E0_v3_rr2.wav': -0.2,
        'BKCtbss_Pizz_F#0_v1_rr1.wav': -17.1,
        'BKCtbss_Pizz_F#0_v1_rr2.wav': -15.4,
        'BKCtbss_Pizz_F#0_v3_rr1.wav': -9.5,
        'BKCtbss_Pizz_F#0_v3_rr2.wav': -8.6,
        'BKCtbss_Pizz_G0_v1_rr1.wav': -30.7,
        'BKCtbss_Pizz_G0_v1_rr2.wav': -31.8,
        'BKCtbss_Pizz_G0_v3_rr1.wav': -0.7,
        'BKCtbss_Pizz_G0_v3_rr2.wav': -0.3,
        'BKCtbss_Pizz_A#0_v1_rr1.wav': +6.6,
        'BKCtbss_Pizz_A#0_v1_rr2.wav': +7.3,
        'BKCtbss_Pizz_A#0_v3_rr1.wav': +7.6,
        'BKCtbss_Pizz_A#0_v3_rr2.wav': +9.3,
        'BKCtbss_Pizz_C1_v1_rr1.wav': +4.5,
        'BKCtbss_Pizz_C1_v1_rr2.wav': -16.1,
        'BKCtbss_Pizz_C1_v3_rr1.wav': +0.4,
        'BKCtbss_Pizz_C1_v3_rr2.wav': -1.7,
        'BKCtbss_Pizz_D1_v1_rr1.wav': +6.1,
        'BKCtbss_Pizz_D1_v1_rr2.wav': +0.8,
        'BKCtbss_Pizz_E1_v1_rr1.wav': -8.5,
        'BKCtbss_Pizz_E1_v1_rr2.wav': +8.2,
        'BKCtbss_Pizz_E1_v3_rr1.wav': -0.7,
        'BKCtbss_Pizz_E1_v3_rr2.wav': -1.0,
        'BKCtbss_Pizz_F#1_v1_rr1.wav': -13.3,
        'BKCtbss_Pizz_F#1_v1_rr2.wav': -11.3,
        'BKCtbss_Pizz_G#1_v1_rr1.wav': -41.7,
        'BKCtbss_Pizz_G#1_v1_rr2.wav': +6.0,
        'BKCtbss_Pizz_A1_v1_rr1.wav': +41.4,
        'BKCtbss_Pizz_A1_v1_rr2.wav': +33.9,
        'BKCtbss_Pizz_C#2_v1_rr1.wav': +5.1,
        'BKCtbss_Pizz_C#2_v1_rr2.wav': +9.1,
        'BKCtbss_Pizz_E2_v1_rr1.wav': +1.7,
        'BKCtbss_Pizz_E2_v1_rr2.wav': +0.5,
        'BKCtbss_Pizz_G#2_v1_rr1.wav': -9.0,
        'BKCtbss_Pizz_G#2_v1_rr2.wav': -2.5,
        'BKCtbss_Pizz_B2_v1_rr1.wav': -12.9,
        'BKCtbss_Pizz_B2_v1_rr2.wav': -1.4,
    },
    # ---------------------------------------------------------------- fix 2b (2026-09-26)
    # The brass and bass shorts, the tremolo sections and the solo violin, measured by tuning.METHOD ('short': a
    # stability-weighted frame track over the note's body; 'held': a time-weighted spectrum of the first ~2 s).
    # harmonic_f0 on a fixed window read a brass crack, the spiccato's bow noise or a section's stray partial as the
    # pitch (hn_stac C1_v1_rr2 +204 c, cb_spic E0_v3_rr1 -250 c, vc_trem E1_v1 -56 c: all really within 5 c).
    # What these correct: tuba_stac A#0_v2_rr3 is played 95 c flat (an A for a B-flat), F1_v1_rr1 -60 c, A#1 v1
    # -8 to -56 c, D#1_v2_rr3 +23 c; tpt_stac F2_v2 -31 / -23 c; hn_stac G1_v1_rr2 -59 c, C1_v2 -31 / -17 c;
    # cb_spic G#1 +15 / +18 c; vc_trem B2_v2 +25 c; svln C4_p +23 c, A4_f +15 c, E5_f +13 c.  The trem and solo-violin
    # sets were fine-tuned before by the HPS estimate, up to 45 c wrong (vc_trem B1_v1 +44.9, measured +1.7).
    # Sections and gliding takes (a glide of 60-150 c through the note) carry +-5-10 c of uncertainty
    # (engine/README.md, sample tuning, fix 2b).  Not corrected: vibes_hard and xylo (inharmonic bars).
    'tuba_stac': {
        'Tuba3_stac_A#0_v1_rr1_Sum.wav': +6.2,
        'Tuba3_stac_A#0_v1_rr2_Sum.wav': -3.1,
        'Tuba3_stac_A#0_v1_rr3_Sum.wav': -2.8,
        'Tuba3_stac_A#0_v1_rr4_Sum.wav': -8.4,
        'Tuba3_stac_A#0_v2_rr1_Sum.wav': -1.8,
        'Tuba3_stac_A#0_v2_rr2_Sum.wav': -15.8,
        'Tuba3_stac_A#0_v2_rr3_Sum.wav': -95.0,
        'Tuba3_stac_A#0_v2_rr4_Sum.wav': -1.1,
        'Tuba3_stac_D#1_v1_rr1_Sum.wav': +7.5,
        'Tuba3_stac_D#1_v1_rr2_Sum.wav': +11.0,
        'Tuba3_stac_D#1_v1_rr3_Sum.wav': -0.7,
        'Tuba3_stac_D#1_v1_rr4_Sum.wav': -0.8,
        'Tuba3_stac_D#1_v2_rr1_Sum.wav': +2.0,
        'Tuba3_stac_D#1_v2_rr2_Sum.wav': +7.7,
        'Tuba3_stac_D#1_v2_rr3_Sum.wav': +23.0,
        'Tuba3_stac_D#1_v2_rr4_Sum.wav': +4.1,
        'Tuba3_stac_F1_v1_rr1_Sum.wav': -60.3,
        'Tuba3_stac_F1_v1_rr2_Sum.wav': -13.6,
        'Tuba3_stac_F1_v1_rr3_Sum.wav': -17.4,
        'Tuba3_stac_F1_v1_rr4_Sum.wav': -9.2,
        'Tuba3_stac_F1_v2_rr1_Sum.wav': +2.7,
        'Tuba3_stac_F1_v2_rr2_Sum.wav': +2.2,
        'Tuba3_stac_F1_v2_rr3_Sum.wav': +16.8,
        'Tuba3_stac_F1_v2_rr4_Sum.wav': +8.6,
        'Tuba3_stac_A#1_v1_rr1_Sum.wav': -56.3,
        'Tuba3_stac_A#1_v1_rr2_Sum.wav': -34.5,
        'Tuba3_stac_A#1_v1_rr3_Sum.wav': -24.7,
        'Tuba3_stac_A#1_v1_rr4_Sum.wav': -8.3,
        'Tuba3_stac_A#1_v2_rr1_Sum.wav': -11.9,
        'Tuba3_stac_A#1_v2_rr2_Sum.wav': +1.7,
        'Tuba3_stac_A#1_v2_rr3_Sum.wav': -5.2,
        'Tuba3_stac_A#1_v2_rr4_Sum.wav': -5.6,
        'Tuba3_stac_D2_v1_rr1_Sum.wav': -15.5,
        'Tuba3_stac_D2_v1_rr2_Sum.wav': -1.6,
        'Tuba3_stac_D2_v1_rr3_Sum.wav': -11.9,
        'Tuba3_stac_D2_v1_rr4_Sum.wav': -6.7,
        'Tuba3_stac_D2_v2_rr1_Sum.wav': -10.2,
        'Tuba3_stac_D2_v2_rr2_Sum.wav': -2.3,
        'Tuba3_stac_D2_v2_rr3_Sum.wav': -13.8,
        'Tuba3_stac_D2_v2_rr4_Sum.wav': -1.2,
        'Tuba3_stac_F2_v1_rr1_Sum.wav': -30.0,
        'Tuba3_stac_F2_v1_rr2_Sum.wav': -19.9,
        'Tuba3_stac_F2_v1_rr3_Sum.wav': -18.8,
        'Tuba3_stac_F2_v1_rr4_Sum.wav': -16.6,
        'Tuba3_stac_F2_v2_rr1_Sum.wav': +0.0,
        'Tuba3_stac_F2_v2_rr2_Sum.wav': -18.0,
        'Tuba3_stac_F2_v2_rr3_Sum.wav': -10.4,
        'Tuba3_stac_F2_v2_rr4_Sum.wav': -7.3,
        'Tuba3_stac_A#2_v1_rr1_Sum.wav': -18.3,
        'Tuba3_stac_A#2_v1_rr2_Sum.wav': -12.0,
        'Tuba3_stac_A#2_v1_rr3_Sum.wav': -8.5,
        'Tuba3_stac_A#2_v1_rr4_Sum.wav': -17.0,
        'Tuba3_stac_A#2_v2_rr1_Sum.wav': -9.7,
        'Tuba3_stac_A#2_v2_rr2_Sum.wav': -3.3,
        'Tuba3_stac_A#2_v2_rr3_Sum.wav': +0.2,
        'Tuba3_stac_A#2_v2_rr4_Sum.wav': -8.6,
        'Tuba3_stac_D3_v1_rr1_Sum.wav': +0.3,
        'Tuba3_stac_D3_v1_rr2_Sum.wav': +4.2,
        'Tuba3_stac_D3_v1_rr3_Sum.wav': +0.8,
        'Tuba3_stac_D3_v1_rr4_Sum.wav': +4.1,
        'Tuba3_stac_D3_v2_rr1_Sum.wav': -3.1,
        'Tuba3_stac_D3_v2_rr2_Sum.wav': +31.8,
        'Tuba3_stac_D3_v2_rr3_Sum.wav': +1.4,
        'Tuba3_stac_D3_v2_rr4_Sum.wav': -0.6,
    },
    'tpt_stac': {
        'Sum_SHTrumpet_stac_F2_v1_rr1.wav': +11.1,
        'Sum_SHTrumpet_stac_F2_v1_rr2.wav': +9.8,
        'Sum_SHTrumpet_stac_F2_v2_rr1.wav': -30.7,
        'Sum_SHTrumpet_stac_F2_v2_rr2.wav': -22.7,
        'Sum_SHTrumpet_stac_F2_v3_rr1.wav': -1.1,
        'Sum_SHTrumpet_stac_F2_v3_rr2.wav': +6.7,
        'Sum_SHTrumpet_stac_A2_v1_rr1.wav': -5.2,
        'Sum_SHTrumpet_stac_A2_v1_rr2.wav': -0.4,
        'Sum_SHTrumpet_stac_A2_v2_rr1.wav': +3.1,
        'Sum_SHTrumpet_stac_A2_v2_rr2.wav': -6.3,
        'Sum_SHTrumpet_stac_A2_v3_rr1.wav': +9.6,
        'Sum_SHTrumpet_stac_A2_v3_rr2.wav': -0.2,
        'Sum_SHTrumpet_stac_C3_v1_rr1.wav': -3.2,
        'Sum_SHTrumpet_stac_C3_v1_rr2.wav': +6.8,
        'Sum_SHTrumpet_stac_C3_v2_rr1.wav': +15.0,
        'Sum_SHTrumpet_stac_C3_v2_rr2.wav': +11.8,
        'Sum_SHTrumpet_stac_C3_v3_rr1.wav': +6.5,
        'Sum_SHTrumpet_stac_C3_v3_rr2.wav': +3.1,
        'Sum_SHTrumpet_stac_D#3_v1_rr1.wav': +2.6,
        'Sum_SHTrumpet_stac_D#3_v1_rr2.wav': -1.5,
        'Sum_SHTrumpet_stac_D#3_v2_rr1.wav': +1.3,
        'Sum_SHTrumpet_stac_D#3_v2_rr2.wav': -6.9,
        'Sum_SHTrumpet_stac_D#3_v3_rr1.wav': +1.2,
        'Sum_SHTrumpet_stac_D#3_v3_rr2.wav': -2.1,
        'Sum_SHTrumpet_stac_F3_v1_rr1.wav': -3.4,
        'Sum_SHTrumpet_stac_F3_v1_rr2.wav': -9.5,
        'Sum_SHTrumpet_stac_F3_v2_rr1.wav': +1.7,
        'Sum_SHTrumpet_stac_F3_v2_rr2.wav': +2.1,
        'Sum_SHTrumpet_stac_F3_v3_rr1.wav': -1.4,
        'Sum_SHTrumpet_stac_F3_v3_rr2.wav': +0.2,
        'Sum_SHTrumpet_stac_G3_v1_rr1.wav': +0.2,
        'Sum_SHTrumpet_stac_G3_v1_rr2.wav': -1.2,
        'Sum_SHTrumpet_stac_G3_v2_rr1.wav': -6.4,
        'Sum_SHTrumpet_stac_G3_v2_rr2.wav': -2.9,
        'Sum_SHTrumpet_stac_G3_v3_rr1.wav': -1.0,
        'Sum_SHTrumpet_stac_G3_v3_rr2.wav': +3.4,
        'Sum_SHTrumpet_stac_A#3_v1_rr1.wav': -2.9,
        'Sum_SHTrumpet_stac_A#3_v1_rr2.wav': +1.3,
        'Sum_SHTrumpet_stac_A#3_v2_rr1.wav': -2.4,
        'Sum_SHTrumpet_stac_A#3_v2_rr2.wav': +2.1,
        'Sum_SHTrumpet_stac_A#3_v3_rr1.wav': -2.0,
        'Sum_SHTrumpet_stac_A#3_v3_rr2.wav': +10.8,
        'Sum_SHTrumpet_stac_D4_v1_rr1.wav': +2.9,
        'Sum_SHTrumpet_stac_D4_v1_rr2.wav': -6.2,
        'Sum_SHTrumpet_stac_D4_v2_rr1.wav': -2.3,
        'Sum_SHTrumpet_stac_D4_v2_rr2.wav': +1.1,
        'Sum_SHTrumpet_stac_D4_v3_rr1.wav': -7.0,
        'Sum_SHTrumpet_stac_D4_v3_rr2.wav': +4.1,
        'Sum_SHTrumpet_stac_F4_v1_rr1.wav': +6.5,
        'Sum_SHTrumpet_stac_F4_v1_rr2.wav': +5.0,
        'Sum_SHTrumpet_stac_F4_v2_rr1.wav': +7.2,
        'Sum_SHTrumpet_stac_F4_v2_rr2.wav': -1.3,
        'Sum_SHTrumpet_stac_F4_v3_rr1.wav': -4.7,
        'Sum_SHTrumpet_stac_F4_v3_rr2.wav': +3.1,
        'Sum_SHTrumpet_stac_A4_v1_rr1.wav': -1.2,
        'Sum_SHTrumpet_stac_A4_v1_rr2.wav': +0.2,
        'Sum_SHTrumpet_stac_A4_v2_rr1.wav': +0.8,
        'Sum_SHTrumpet_stac_A4_v2_rr2.wav': +6.7,
        'Sum_SHTrumpet_stac_A4_v3_rr1.wav': -12.8,
        'Sum_SHTrumpet_stac_A4_v3_rr2.wav': +4.4,
        'Sum_SHTrumpet_stac_C5_v1_rr1.wav': -1.2,
        'Sum_SHTrumpet_stac_C5_v1_rr2.wav': -5.8,
        'Sum_SHTrumpet_stac_C5_v2_rr1.wav': -10.5,
        'Sum_SHTrumpet_stac_C5_v2_rr2.wav': -4.4,
        'Sum_SHTrumpet_stac_C5_v3_rr1.wav': -4.1,
        'Sum_SHTrumpet_stac_C5_v3_rr2.wav': -2.2,
    },
    'hn_stac': {
        'MOHorn_stac_A0_v1_rr1.wav': -7.5,
        'MOHorn_stac_A0_v1_rr2.wav': -4.6,
        'MOHorn_stac_C1_v1_rr1.wav': +2.5,
        'MOHorn_stac_C1_v1_rr2.wav': +3.7,
        'MOHorn_stac_C1_v2_rr1.wav': -31.2,
        'MOHorn_stac_C1_v2_rr2.wav': -17.2,
        'MOHorn_stac_D#1_v1_rr1.wav': +2.2,
        'MOHorn_stac_D#1_v1_rr2.wav': +5.0,
        'MOHorn_stac_D#1_v2_rr1.wav': +0.7,
        'MOHorn_stac_D#1_v2_rr2.wav': -0.5,
        'MOHorn_stac_G1_v1_rr1.wav': +9.7,
        'MOHorn_stac_G1_v1_rr2.wav': -58.8,
        'MOHorn_stac_G1_v2_rr1.wav': -2.8,
        'MOHorn_stac_G1_v2_rr2.wav': -1.8,
        'MOHorn_stac_A#1_v1_rr1.wav': +1.0,
        'MOHorn_stac_A#1_v2_rr1.wav': +1.2,
        'MOHorn_stac_A#1_v2_rr2.wav': +1.7,
        'MOHorn_stac_A#1_v3_rr1.wav': +1.3,
        'MOHorn_stac_A#1_v3_rr2.wav': +4.9,
        'MOHorn_stac_D2_v1_rr1.wav': -3.4,
        'MOHorn_stac_D2_v1_rr2.wav': -1.4,
        'MOHorn_stac_D2_v2_rr1.wav': -2.2,
        'MOHorn_stac_D2_v2_rr2.wav': -1.7,
        'MOHorn_stac_D2_v3_rr1.wav': +0.3,
        'MOHorn_stac_D2_v3_rr2.wav': -2.1,
        'MOHorn_stac_F2_v1_rr1.wav': +0.9,
        'MOHorn_stac_F2_v1_rr2.wav': +2.2,
        'MOHorn_stac_F2_v2_rr1.wav': -1.8,
        'MOHorn_stac_F2_v2_rr2.wav': +0.7,
        'MOHorn_stac_F2_v3_rr1.wav': +2.0,
        'MOHorn_stac_F2_v3_rr2.wav': +2.1,
        'MOHorn_stac_A2_v1_rr1.wav': -4.2,
        'MOHorn_stac_A2_v1_rr2.wav': -4.5,
        'MOHorn_stac_A2_v2_rr1.wav': -2.2,
        'MOHorn_stac_A2_v2_rr2.wav': -9.3,
        'MOHorn_stac_A2_v3_rr1.wav': -1.7,
        'MOHorn_stac_A2_v3_rr2.wav': -2.9,
        'MOHorn_stac_C3_v1_rr1.wav': +1.5,
        'MOHorn_stac_C3_v1_rr2.wav': -3.2,
        'MOHorn_stac_C3_v2_rr1.wav': -0.0,
        'MOHorn_stac_C3_v2_rr2.wav': +2.4,
        'MOHorn_stac_C3_v3_rr1.wav': +2.3,
        'MOHorn_stac_C3_v3_rr2.wav': -2.3,
        'MOHorn_stac_D4_v1_rr1.wav': -0.9,
        'MOHorn_stac_D4_v1_rr2.wav': -0.2,
        'MOHorn_stac_D4_v2_rr1.wav': +1.5,
        'MOHorn_stac_D4_v2_rr2.wav': +1.1,
        'MOHorn_stac_D4_v3_rr1.wav': -0.9,
        'MOHorn_stac_D4_v3_rr2.wav': -0.3,
        'MOHorn_stac_F4_v1_rr1.wav': -0.6,
        'MOHorn_stac_F4_v1_rr2.wav': -2.9,
        'MOHorn_stac_F4_v2_rr1.wav': -0.7,
        'MOHorn_stac_F4_v2_rr2.wav': -0.5,
        'MOHorn_stac_F4_v3_rr1.wav': +1.1,
    },
    'cb_spic': {
        'BKCtbss_Spic_E0_v1_rr1.wav': -9.5,
        'BKCtbss_Spic_E0_v1_rr2.wav': +0.2,
        'BKCtbss_Spic_E0_v3_rr1.wav': +3.6,
        'BKCtbss_Spic_E0_v3_rr2.wav': -0.2,
        'BKCtbss_Spic_F#0_v1_rr1.wav': -24.5,
        'BKCtbss_Spic_F#0_v1_rr2.wav': -1.4,
        'BKCtbss_Spic_F#0_v3_rr1.wav': -2.9,
        'BKCtbss_Spic_F#0_v3_rr2.wav': +3.4,
        'BKCtbss_Spic_G0_v1_rr1.wav': +5.2,
        'BKCtbss_Spic_G0_v1_rr2.wav': +6.6,
        'BKCtbss_Spic_G0_v3_rr1.wav': +0.1,
        'BKCtbss_Spic_G0_v3_rr2.wav': +1.8,
        'BKCtbss_Spic_A#0_v1_rr1.wav': +4.6,
        'BKCtbss_Spic_A#0_v1_rr2.wav': +16.1,
        'BKCtbss_Spic_A#0_v3_rr1.wav': +7.7,
        'BKCtbss_Spic_A#0_v3_rr2.wav': +3.7,
        'BKCtbss_Spic_C1_v1_rr1.wav': +3.5,
        'BKCtbss_Spic_C1_v1_rr2.wav': +8.6,
        'BKCtbss_Spic_C1_v3_rr1.wav': +0.7,
        'BKCtbss_Spic_C1_v3_rr2.wav': +7.8,
        'BKCtbss_Spic_D1_v1_rr1.wav': -0.0,
        'BKCtbss_Spic_D1_v1_rr2.wav': +2.8,
        'BKCtbss_Spic_D1_v3_rr1.wav': -6.4,
        'BKCtbss_Spic_D1_v3_rr2.wav': -1.3,
        'BKCtbss_Spic_E1_v1_rr1.wav': -9.0,
        'BKCtbss_Spic_E1_v1_rr2.wav': +2.2,
        'BKCtbss_Spic_E1_v3_rr1.wav': +0.2,
        'BKCtbss_Spic_E1_v3_rr2.wav': +1.2,
        'BKCtbss_Spic_F#1_v1_rr1.wav': +3.2,
        'BKCtbss_Spic_F#1_v1_rr2.wav': -0.3,
        'BKCtbss_Spic_G#1_v1_rr1.wav': +15.1,
        'BKCtbss_Spic_G#1_v1_rr2.wav': +17.7,
        'BKCtbss_Spic_A1_v1_rr1.wav': +2.7,
        'BKCtbss_Spic_A1_v1_rr2.wav': -6.5,
        'BKCtbss_Spic_C#2_v1_rr1.wav': +9.5,
        'BKCtbss_Spic_C#2_v1_rr2.wav': +7.2,
        'BKCtbss_Spic_E2_v1_rr1.wav': -7.7,
        'BKCtbss_Spic_E2_v1_rr2.wav': +3.8,
        'BKCtbss_Spic_G#2_v1_rr1.wav': -1.3,
        'BKCtbss_Spic_G#2_v1_rr2.wav': +4.2,
        'BKCtbss_Spic_B2_v1_rr1.wav': +1.1,
        'BKCtbss_Spic_B2_v1_rr2.wav': -1.2,
    },
    'vla_trem': {
        'Violas_trem_C2_v1_rr1.wav': -9.9,
        'Violas_trem_C2_v2_rr1.wav': -3.9,
        'Violas_trem_E2_v1_rr1.wav': -2.1,
        'Violas_trem_E2_v2_rr1.wav': +3.0,
        'Violas_trem_G2_v1_rr1.wav': -6.0,
        'Violas_trem_G2_v2_rr1.wav': -3.6,
        'Violas_trem_B2_v1_rr1.wav': +1.9,
        'Violas_trem_B2_v2_rr1.wav': -0.9,
        'Violas_trem_D3_v1_rr1.wav': -0.5,
        'Violas_trem_D3_v2_rr1.wav': -0.2,
        'Violas_trem_F3_v1_rr1.wav': -3.8,
        'Violas_trem_F3_v2_rr1.wav': +1.0,
        'Violas_trem_A3_v1_rr1.wav': -1.4,
        'Violas_trem_A3_v2_rr1.wav': +3.0,
        'Violas_trem_C4_v1_rr1.wav': +1.6,
        'Violas_trem_C4_v2_rr1.wav': -1.0,
        'Violas_trem_E4_v1_rr1.wav': +2.6,
        'Violas_trem_E4_v2_rr1.wav': +1.0,
        'Violas_trem_G4_v1_rr1.wav': +1.4,
        'Violas_trem_G4_v2_rr1.wav': +1.0,
        'Violas_trem_B4_v1_rr1.wav': -1.9,
        'Violas_trem_B4_v2_rr1.wav': +0.9,
        'Violas_trem_D5_v1_rr1.wav': +5.2,
        'Violas_trem_D5_v2_rr1.wav': -0.3,
    },
    'vc_trem': {
        'trem_C1_v2_1.wav': -4.6,
        'trem_E1_v1_1.wav': +3.8,
        'trem_E1_v2_1.wav': -4.3,
        'trem_G1_v1_1.wav': -0.9,
        'trem_G1_v2_1.wav': +1.9,
        'trem_B1_v1_1.wav': +1.7,
        'trem_D2_v1_1.wav': -9.3,
        'trem_D2_v2_1.wav': -13.4,
        'trem_F2_v1_1.wav': -3.1,
        'trem_F2_v2_1.wav': +8.0,
        'trem_A2_v1_1.wav': +0.0,
        'trem_A2_v2_1.wav': -4.8,
        'trem_B2_v2_1.wav': +25.0,
        'trem_C3_v1_1.wav': -0.4,
        'trem_C3_v2_1.wav': -0.0,
        'trem_E3_v1_1.wav': +0.8,
        'trem_E3_v2_1.wav': +3.5,
        'trem_G3_v1_1.wav': -0.8,
        'trem_G3_v2_1.wav': -3.4,
        'trem_B3_v1_1.wav': -1.0,
        'trem_B3_v2_1.wav': -1.0,
        'trem_D4_v1_1.wav': +1.0,
        'trem_D4_v2_1.wav': -5.0,
        'trem_F4_v1_1.wav': +6.0,
        'trem_F4_v2_1.wav': -0.2,
    },
    'svln': {
        'LLVln_ArcoVib_G3_p.wav': -3.1,
        'LLVln_ArcoVib_G3_f.wav': -0.9,
        'LLVln_ArcoVib_A3_p.wav': +1.2,
        'LLVln_ArcoVib_A3_f.wav': -1.4,
        'LLVln_ArcoVib_C4_p.wav': +22.6,
        'LLVln_ArcoVib_C4_f.wav': -0.6,
        'LLVln_ArcoVib_E4_p.wav': +4.4,
        'LLVln_ArcoVib_E4_f.wav': +1.4,
        'LLVln_ArcoVib_G4_p.wav': -4.7,
        'LLVln_ArcoVib_G4_f.wav': +2.9,
        'LLVln_ArcoVib_A4_p.wav': +0.6,
        'LLVln_ArcoVib_A4_f.wav': +14.8,
        'LLVln_ArcoVib_C5_p.wav': -1.9,
        'LLVln_ArcoVib_C5_f.wav': +2.2,
        'LLVln_ArcoVib_E5_p.wav': +4.8,
        'LLVln_ArcoVib_E5_f.wav': +12.7,
        'LLVln_ArcoVib_G5_p.wav': +2.6,
        'LLVln_ArcoVib_G5_f.wav': +5.0,
        'LLVln_ArcoVib_A5_p.wav': +0.3,
        'LLVln_ArcoVib_A5_f.wav': +0.6,
        'LLVln_ArcoVib_C6_p.wav': -5.1,
        'LLVln_ArcoVib_C6_f.wav': -9.7,
        'LLVln_ArcoVib_E6_p.wav': +8.1,
        'LLVln_ArcoVib_E6_f.wav': +9.0,
        'LLVln_ArcoVib_G6_p.wav': +4.5,
        'LLVln_ArcoVib_G6_f.wav': +9.1,
        'LLVln_ArcoVib_A6_p.wav': -1.7,
        'LLVln_ArcoVib_A6_f.wav': +11.3,
        'LLVln_ArcoVib_C7_p.wav': +2.5,
        'LLVln_ArcoVib_C7_f.wav': -6.0,
    },
}
