// MR. MAS — Ep1 Act Four · the animatic v5: one layout per shot of timing lock v5 (INF-SHOTS5; the a4p5-lock pass).
// Lock v5 (data-v5.ts, generated by tools/lock_v5.py from the APPROVED stick timeline) plays the act as 83 shots. Every
// shot has a layout here, of one of three kinds (the verdicts are art-needs-v5 §3's, carried in the lock as sh.verdict):
//   R  reuse: THE EDITOR's v4 layout (shots4.ts) run through the `v4()` adapter, re-clocked on the v5 shot: its lines
//      (renamed back to the v4 ids the layout looks up, lock V4_IDS), its in-world texts and its story marks all come from
//      lock v5. Nothing in shots4.ts changes, so v4 stays renderable.
//   C  change: the v4 composition re-dressed with the v5 art (the art-v5 modules in shared/pixel: posts, the board's side
//      of the call, the letter, the pointer, the speakerphone, the hourglass insert, Terb's sheet...), re-built here where
//      the v4 layout could not take the new piece from outside.
//   N  new: a composition of the new v5 modules (Neleh's desk, the board head, the board screen, the unpacked bullpen...)
//      in the framing `art-v5/demos.ts` gives each one.
// A layout that throws, or a shot with no layout, draws the STICK FALLBACK (stickFallback: drawn stick figures on a plain
// set in the side's light, never a text label), is flagged in DRAW5_FAILED and reports `fallback` so the host's margin
// can mark it. Every layout carries `st` (what it is built from) and `standin` (it still holds a stand-in) for the margin
// and the shot list.
// Rules kept (studio/PIXEL_GUIDE.md, art-needs-v5 §5): native 480 x 270, master palette, whole-pixel moves, held drawings,
// nothing scaled but a screen's own pixels, no mirrored frames with lettering (S4.04 now uses Neleh's own right-shoulder
// drawing), Mas in the left third. The GLYPH dissolve stays at the Cancel click (S1.09 returns its layers); J1 is not
// drawn here: a host that plays J1 replaces frames t 1..59 after CANCEL_CLICK and ignores S1.09's layers there
// (art-v5/j1/pixel.ts j1PixelFrame; J1_PIXEL_OPTS keeps his tile's neon on the same guardrail clock).
// Mouths (INF-LIPSYNC5): every mouth comes from lipsync5.ts (mouth5 / roomMouth5 / boardMouths5 / silentMouth5, and
// v4Track5 for the adapter); the layouts here only pass them on in their `mouth:` fields. The lock's `face` decides who
// shows a mouth in a framing (art-needs-v5 §1.2), not the take's lip_sync flag: a line whose face is null draws 'rest'.
// `k` is shot-relative, `f` the v5 act frame; v4 layouts get the v4 act frame of the same shot position (f4 = v4 shot
// start + k) so their act-clocked loops and sequence clocks (the avalanche's S6 clock) run exactly as they did in v4.
import {Buf, rect, clamp} from '../../../../shared/pixel/px';
import {PAL, stepColor} from '../../../../shared/pixel/palette';
import {inPalette} from '../../../../shared/pixel/palettes';
import type {GlyphLayer} from '../../../../shared/pixel/glyph';
import type {Viseme} from '../../../../shared/pixel/cast/talk';
import {blitImg} from '../../../../shared/pixel/figure';
import {
  callChrome, drawTile, TileRect, captureTile, tileDrop, slideTiles, dialogButton, drawPointer, tilePlate, dropY,
} from '../../../../shared/pixel/kits/callgrid';
import {planPile, withBlueHeart, drawPile, pileTopAt, pileHeartAt, PileHeart, reactionBurst, heartCounter, drawHeart, BLUE} from '../../../../shared/pixel/kits/avalanche';
import {spinner} from '../../../../shared/pixel/kits/callgrid';
import {BLUEPRINT_PRINT} from '../../../../shared/pixel/kits/blueprint';
// ---- the v5 art (art-built-v5.md §1)
import {drawPost, POSTS, POSTERS, drawAvatar9, PostSpec, PostWho} from '../../../../shared/pixel/kits/post-card';
import {drawPhoneInsert29} from '../../../../shared/pixel/kits/inserts-mas';
import {drawNelehDeskOTS, drawNelehBezel, drawNelehDeskWall, NDESK} from '../../../../shared/pixel/rooms/neleh-desk';
import {drawNelehShoulderR} from '../../../../shared/pixel/cast/neleh-ots';
import {drawBoardCall, drawTileSoft, BOARD_NOTICE} from '../../../../shared/pixel/kits/call-boardside';
import {drawBlogDraft, BLOG} from '../../../../shared/pixel/kits/blog-draft';
import {drawStaffLetter, LETTER_SCROLL_MAX, letterLayout} from '../../../../shared/pixel/kits/staff-letter';
import {bpNeleh, bpTipIn, bpVoice, inkOver, sweep, bpBracket, BpNelehPose} from '../../../../shared/pixel/kits/bp-pointer';
import {drawBoardHead2S, drawBoardHeadM} from '../../../../shared/pixel/rooms/boardroom-head';
import type {FolderState} from '../../../../shared/pixel/kits/folder';
import {drawChatPanel} from '../../../../shared/pixel/kits/chat-panel';
import {drawCalmOffTerms2S, drawOtherYrralM} from '../../../../shared/pixel/rooms/calmoff-terms';
import {drawLobbyFeed, FEED_W, FEED_H, LobbyFeedPhase} from '../../../../shared/pixel/kits/lobby-feed';
import {drawBoardScreenOTS, drawBoardScreen2S} from '../../../../shared/pixel/rooms/board-screen';
import {alyiLook, drawAlyiDoorPhone} from '../../../../shared/pixel/cast/alyi-v5';
import {drawSlateDoorOpen, slateDoorSign, SLATE_GAP, keyTurnAt} from '../../../../shared/pixel/rooms/slate-desks';
import {masTurnedAway, drawVaultMid, gergHandOnVault, VAULT_MID} from '../../../../shared/pixel/cast/mas-turnaway';
import {drawBullpenUnpack} from '../../../../shared/pixel/rooms/bullpen-unpack';
import {drawHourglassXL, hgxFlip, HGX, HGX_HIGH, HGX_GRAINS} from '../../../../shared/pixel/kits/hourglass-insert';
import {woodGrain} from '../../../../shared/pixel/kits/props';
import {tasyaPhonePortrait} from '../../../../shared/pixel/cast/tasya-phone';
import {macrosoftBadge, badgesOnDeskRoom, BADGES_ROOM_AT} from '../../../../shared/pixel/kits/macrosoft-badge';
import {drawEmployeeStanding, EMP_STAND_WHO} from '../../../../shared/pixel/cast/employee-stand';
import {drawNudgeJoin} from '../../../../shared/pixel/kits/join-corner';
import {drawSpeakerphoneMCU} from '../../../../shared/pixel/kits/speakerphone';
// ---- the v4 kit this pass composes with (unchanged modules)
import {drawBoardPlate, drawBoardPlateTable, drawBoardPlateFront} from '../../../../shared/pixel/rooms/boardroom-plate';
import type {BoardPlateOpts} from '../../../../shared/pixel/rooms/boardroom-plate';
import {drawDarkPlate, drawDarkPlateDesk, drawDarkPlateFront, DPLATE, DPLATE_LOOK} from '../../../../shared/pixel/rooms/darkroom-plate';
import type {DarkPlateOpts} from '../../../../shared/pixel/rooms/darkroom-plate';
import {drawDark2S} from '../../../../shared/pixel/rooms/twoshots';
import {FIRES_CALMOFF} from '../../../../shared/pixel/rooms/twoshots';
import {drawBullpen} from '../../../../shared/pixel/rooms/bullpen';
import {drawLighthouse} from '../../../../shared/pixel/rooms/lighthouse';
import {LOBBY} from '../../../../shared/pixel/rooms/lobby';
import {BR, drawTableInsert, TABLE_INSERT, FIRES_SC30} from '../../../../shared/pixel/rooms/boardroom';
import {terbWalkAt} from '../../../../shared/pixel/cast/terb';
import {drawMasStand, MAS_STAND_DEFAULT, masWalkAt} from '../../../../shared/pixel/cast/mas-stand';
import {drawShutDoorInsert} from '../../../../shared/pixel/kits/inserts-props';
import {masPortrait, MAS_PORTRAIT_DEFAULT} from '../../../../shared/pixel/cast/mas';
import type {MasPortraitState} from '../../../../shared/pixel/cast/mas';
import {nelehPortrait, NELEH_PORTRAIT_DEFAULT, withFootnoteStyle} from '../../../../shared/pixel/cast/neleh';
import type {FootnoteStyle} from '../../../../shared/pixel/cast/neleh';
import {alyiReflection} from '../../../../shared/pixel/cast/alyi-speak';
import {ttemmePortrait, TTEMME_PORTRAIT_DEFAULT, drawChatOverlay} from '../../../../shared/pixel/cast/ttemme';
import {drawAdelinaRoom, ADELINA_ROOM_DEFAULT} from '../../../../shared/pixel/cast/adelina';
import type {AdelinaArm} from '../../../../shared/pixel/cast/adelina';
import {marioImg, MARIO_BASE, MARIO_FOOT} from '../../../../shared/pixel/cast/mario';
import type {MarioArm} from '../../../../shared/pixel/cast/mario';
import {gergGlow} from '../../../../shared/pixel/cast/gerg-speak';
import {drawGergMediumPOV} from '../../../../shared/pixel/cast/gerg-medium';
import {drawGergTileWide} from '../../../../shared/pixel/cast/swaps-act4';
import {drawOrb, orbStep} from '../../../../shared/pixel/cast/orb-medium';
import {drawPlan4, PLAN4} from './plan4';
import {boardRoom, bullpenRoom, lobbyRoom, doorShake} from './backs';
import {RH, held, fallaway, blipCard, freezePrint, pt, pw, pwrap, bpt, bpw, putUI, ACCENT} from './lay';
import {talking5, mouth5, roomMouth5, boardMouths5, silentMouth5, v4Track5, lipOn5, room3Mouth5} from './lipsync5';
import {soft, softMask, keepRect, vignette, shoulder, drawBust, MCU_X, rackStep, RACK, doorFrame, platePx, shiftRoom} from './framing';
import {G5, G4, ui, wifi, board4, masTileState, dialog26, DLG, sui, putSCR, SCR_W, SCR_H, keycapRain, HG, monitor} from './shots';
import {DRAW4} from './shots4';
import type {ShotOut4} from './shots4';
import {SHOTS as SHOTS_V4} from './data-v4';
import type {ShotV4, LineV4} from './data-v4';
import {SHOTS, V4_IDS, D6} from './data-v5';
import type {ShotV5, LineV5} from './data-v5';

// ================================================================== switches (the lead's calls; see shotlist-v5 / report-v5)
export const OPT5 = {
  /** STYLE-1G-NEON: his tile's Vegas neon on 1.G's guardrail (<= 1 step per 8 f) on HIS side too (art-needs §1.7). On. */
  neonGuard: true,
  /** STYLE-1G-SOFT: the far end's tiles one grid-true step softer (P3). OFF by default: the prep read found Neleh's
   *  softened face losing its eyes ("reads as our own low quality", style-range 1.G's drop condition); blind-read it first */
  soft1G: false,
  /** FIX-FOOTNOTES (a4p5 r2, cast/neleh.ts): Neleh's footnotes as numbered paper slips that never cross her face, in
   *  every v5 frame (drawShot5 wraps each layout, v4's reused ones included, in withFootnoteStyle). 'digits' = v4's */
  footnotes: 'slips' as FootnoteStyle,
};
/** the Cancel click (act frame): a J1 host counts t from here (art-v5/j1/timing.ts) */
export const CANCEL_CLICK = D6[0];
/** J1's pixel options for this cut (art-v5/j1/pixel.ts J1PixelOpts): the same neon clock as S1.09 draws */
export const J1_PIXEL_OPTS = {fClick: D6[0], neonGuard: OPT5.neonGuard};

// ================================================================== the registry
export interface ShotOut5 extends ShotOut4 { fallback?: boolean }
type Draw5 = (fb: Buf, k: number, sh: ShotV5, f: number) => ShotOut5 | void;
export interface ShotDef5 { draw: Draw5; st: string; standin: boolean; kind: 'R' | 'C' | 'N' }
export const DRAW5: Record<string, ShotDef5> = {};
/** register a v5 layout. `st` = what it is built from (the margin prints it); `standin` = it still holds a stand-in */
const S5 = (ids: string | string[], kind: 'R' | 'C' | 'N', st: string, draw: Draw5, standin = false) => {
  for (const id of ([] as string[]).concat(ids)) DRAW5[id] = {draw, st, standin, kind};
};
const on2 = (k: number) => k - (k % 2);
const mk = (sh: ShotV5, name: string, dflt: number) => sh.marks[name] ?? dflt;
const len5 = (sh: ShotV5) => sh.e - sh.s;
const blink = (k: number, seed: number): 0 | 1 | 2 => { const p = (k + seed * 37) % 97; return p === 0 || p === 2 ? 1 : p === 1 ? 2 : 0; };

// ================================================================== lines (mouths: lipsync5.ts, the framing decides)
const lineOf5 = (sh: ShotV5, id: string) => sh.lines.find((l) => l.id === id) ?? null;
const textOf = (sh: ShotV5, kind: string, sub = '') => sh.texts.find((t) => t.kind === kind && t.text.includes(sub)) ?? null;
/** a post's card, in the LOCK's words (the stick's in-world text), with POSTS' poster and time stamp */
const POST_KEY: Record<string, keyof typeof POSTS> = {
  'a5-27-P1': 'gergQuit', 'a5-27-P2': 'masEulogy', 'a5-27-P3': 'masBadge', 'a5-29-P1': 'rimaPeople', 'a5-30-P1': 'alyiRegret',
  'a5-30-P2': 'gergReturn', 'a5-30-P3': 'ttemmeResult',
};
const postSpec = (sh: ShotV5, id: string): PostSpec => {
  const base = POSTS[POST_KEY[id]];
  const l = lineOf5(sh, id);
  return {...base, who: (l ? l.who.toLowerCase() : base.who) as PostWho, text: l ? l.text : base.text};
};

// ================================================================== the v4 adapter: a v4 layout on a v5 shot's clock
const V4REC = new Map(SHOTS_V4.map((s) => [s.id, s]));
/** v5 line id -> the v4 id a v4 layout looks it up by (lock V4_IDS, inverted) */
const V4_BACK: Record<string, string> = Object.fromEntries(Object.entries(V4_IDS).map(([a4, a5]) => [a5, a4]));
const toV4Line = (l: LineV5): LineV4 => ({
  id: V4_BACK[l.id] ?? l.id, kind: l.kind, mode: l.mode, who: l.who, text: l.text, s: l.s, e: l.e, side: null, os: l.os, via: l.via,
  lip: !!l.face, words: l.words,
  // lipsync5 v4Track5: a faced line's drawn track (the hold fix, the lead); a line whose face is null in this framing keeps
  // its timing but draws no mouth (a one-entry 'rest' track: an EMPTY track would make the v4/v3 mouth() helpers flap)
  mouth: v4Track5(l),
});
const asV4 = (sh: ShotV5, id: string): ShotV4 => {
  const b = V4REC.get(id) as ShotV4;
  return {...b, id, s: sh.s, e: sh.e, plan: sh.plan, lines: sh.lines.map(toV4Line), texts: sh.texts.map((t) => ({...t})), marks: {...sh.marks}};
};
/** run v4's layout `id` at shot frame k of the v5 shot (f4 = v4's act frame of the same shot position) */
const v4 = (fb: Buf, id: string, k: number, sh: ShotV5): ShotOut5 => {
  const d = DRAW4[id];
  const b = V4REC.get(id) as ShotV4;
  return (d.draw(fb, k, asV4(sh, id), b.s + k) ?? {}) as ShotOut5;
};
/** register an R shot: v4's layout as is (its stand-in flag carried) */
const R5 = (id: string, v4id: string, note = '') => {
  const d = DRAW4[v4id];
  S5(id, 'R', `v4 ${v4id}${note ? ` (${note})` : ''}: ${d.st}`, (fb, k, sh) => v4(fb, v4id, k, sh), d.standin);
};

// ================================================================== small shared drawings (copied from shots4.ts, which keeps them private)
const IDS5 = [{id: 'mas', name: 'MAS MANALT'}, {id: 'alyi', name: 'ALYI'}, {id: 'neleh', name: 'NELEH'}, {id: 'mada', name: 'MADA'}, {id: 'off', name: undefined}];
/** a collaborator cursor's tag in the display face (v4.2's): name + role; name '' = the empty tag */
const cursorTagBig = (b: Buf, x: number, y: number, name: string, col: number, role = '') => {
  const w = Math.max(name ? bpw(name) : 40, role ? pw(role) : 0) + 14, h = role ? 29 : 20;
  rect(x + 8, y + 12, w + 2, h + 2, b.ink(PAL.N0)); rect(x + 9, y + 13, w, h, b.ink(col));
  if (!name) { rect(x + 11, y + 15, w - 4, h - 4, b.ink(PAL.N1)); return; }
  bpt(b, name, x + 16, y + 16, PAL.N0);
  if (role) pt(b, role, x + 16, y + 33, PAL.N0);
};
const hoverRing = (b: Buf, bx: number, by: number, bw: number, bh: number, col: number) => {
  for (const t of [2, 3]) {
    rect(bx - t, by - t, bw + t * 2, 1, b.ink(col)); rect(bx - t, by + bh - 1 + t, bw + t * 2, 1, b.ink(col));
    rect(bx - t, by - t, 1, bh + t * 2, b.ink(col)); rect(bx + bw - 1 + t, by - t, 1, bh + t * 2, b.ink(col));
  }
};
const callNotice = (b: Buf, s: string, k: number, y = RH - 34) => {
  if (k < 0) return;
  const w = bpw(s) + 40, x = Math.round(240 - w / 2), rise = k < 3 ? [8, 4, 1][k] : 0;
  const yy = y + rise;
  rect(x, yy, w, 24, b.ink(PAL.N0)); rect(x + 1, yy + 1, w - 2, 22, b.ink(PAL.N3)); rect(x + 1, yy + 1, w - 2, 1, b.ink(PAL.N5));
  rect(x + 8, yy + 6, 8, 12, b.ink(PAL.G5)); rect(x + 9, yy + 7, 6, 11, b.ink(PAL.N1)); b.set(x + 13, yy + 12, PAL.G5);
  bpt(b, s, x + 24, yy + 5, PAL.P2);
};
/** a plate with a name and one line (v4's plate4) or two lines (plate3), typed on; k from its landing */
const plateN = (b: Buf, x: number, y: number, name: string, lines: string[], k: number, accent: number) => {
  if (k < 0) return;
  const w = Math.max(pw(name), ...lines.map(pw)) + 16;
  const full = 16 + lines.length * 10, open = Math.min(1, (k + 1) / 3), hh = Math.max(2, Math.round(full * open));
  rect(x - 1, y - 1, w + 2, hh + 2, b.ink(PAL.N0)); rect(x, y, w, hh, b.ink(PAL.N1)); rect(x, y, w, 1, b.ink(accent));
  if (open < 1) return;
  pt(b, name.slice(0, Math.max(0, (k - 2) * 3)), x + 8, y + 5, accent);
  lines.forEach((l, i) => pt(b, l.slice(0, Math.max(0, (k - 5 - i * 4) * 3)), x + 8, y + 15 + i * 10, i ? PAL.P0 : PAL.P1));
};
/** a lock plate text 'NAME · A · B' -> name + lines */
const plateOf = (text: string, maxLines = 2): [string, string[]] => {
  const parts = text.split(' · ');
  const name = parts.shift() ?? '';
  if (parts.length <= maxLines) return [name, parts];
  return [name, [parts.slice(0, parts.length - maxLines + 1).join(' · '), ...parts.slice(parts.length - maxLines + 1)]];
};
const boardBg = (o: BoardPlateOpts = {}) => (b: Buf) => { const opt: BoardPlateOpts = {laptop: true, rolodex: true, blueprint: 0, ...o}; drawBoardPlate(b, 0, opt); drawBoardPlateTable(b, 0, opt); drawBoardPlateFront(b, 0, opt); };
const darkBg = (o: DarkPlateOpts = {}) => (b: Buf) => { const opt: DarkPlateOpts = {tally: 3, glass: true, lanyard: true, ...o}; drawDarkPlate(b, 0, opt); drawDarkPlateDesk(b, 0, opt); drawDarkPlateFront(b, 0, opt); };
const dimRectL = (b: Buf, x: number, y: number, w: number, h: number, k: number) => {
  for (let j = y; j < Math.min(RH, y + h); j++) for (let i = Math.max(0, x); i < Math.min(480, x + w); i++) b.set(i, j, stepColor(b.get(i, j), -k));
};
const mas = (s: Partial<MasPortraitState> = {}) => masPortrait({...MAS_PORTRAIT_DEFAULT, look: -1, ...s});
const silentMouth = silentMouth5; // his side's silent talking mouth (lipsync5)
/** the board's side of the call: who holds the speaking ring now, and every tile's mouth */
const boardSpeaker = (sh: ShotV5, k: number): 'alyi' | 'neleh' | 'rima' | null => {
  for (const w of ['RIMA', 'ALYI', 'NELEH']) if (talking5(sh, k, w)) return w.toLowerCase() as 'alyi' | 'neleh' | 'rima';
  return null;
};
const boardMouths = boardMouths5;
const clockAt = (sh: ShotV5, k: number, dflt: string) => sh.texts.filter((t) => t.kind === 'clock' && k >= t.s && k < t.e).pop()?.text ?? dflt;

// ================================================================== THE STICK FALLBACK (never a text label)
const SLUG_WHO: Record<string, string> = {mas: 'MAS', neleh: 'NELEH', alyi: 'ALYI', mada: 'MADA', gerg: 'GERG', rima: 'RIMA', employee: 'EMPLOYEE',
  mario: 'MARIO', adelina: 'ADELINA', ttemme: 'TTEMME', tasya: 'TASYA', terb: 'TERB'};
const ringPx = (b: Buf, cx: number, cy: number, r: number, c: number) => { for (let a = 0; a < 360; a += 4) b.set(Math.round(cx + Math.cos(a * Math.PI / 180) * r), Math.round(cy + Math.sin(a * Math.PI / 180) * r), c); };
const linePx = (b: Buf, x0: number, y0: number, x1: number, y1: number, c: number) => {
  const n = Math.max(Math.abs(x1 - x0), Math.abs(y1 - y0), 1);
  for (let i = 0; i <= n; i++) { const x = Math.round(x0 + ((x1 - x0) * i) / n), y = Math.round(y0 + ((y1 - y0) * i) / n); b.set(x, y, c); b.set(x + 1, y, c); }
};
/** drawn stick figures for the shot's cast on a plain set (the side's light), mouths open while they speak */
export const stickFallback = (fb: Buf, k: number, sh: ShotV5) => {
  const board = sh.side === 'BOARD';
  rect(0, 0, 480, RH, fb.ink(board ? PAL.D1 : PAL.N1));
  rect(0, 150, 480, RH - 150, fb.ink(board ? PAL.D2 : PAL.N2)); rect(0, 150, 480, 1, fb.ink(board ? PAL.D4 : PAL.N4));
  const who = sh.chars.map((c) => SLUG_WHO[c] ?? c.toUpperCase()).filter((w, i, a) => a.indexOf(w) === i);
  const order = who.includes('MAS') ? ['MAS', ...who.filter((w) => w !== 'MAS')] : who; // Mas in the left third
  order.slice(0, 5).forEach((w, i, a) => {
    const x = Math.round(((i + 1) * 480) / (a.length + 1)), col = ACCENT[w] ?? PAL.P1;
    ringPx(fb, x, 70, 11, col); ringPx(fb, x, 70, 10, col);
    const talk = talking5(sh, k, w) && ((k >> 2) % 2 === 0);
    rect(x - 3, 75, 7, talk ? 3 : 1, fb.ink(col));
    linePx(fb, x, 82, x, 120, col); linePx(fb, x, 92, x - 16, 110, col); linePx(fb, x, 92, x + 16, 110, col);
    linePx(fb, x, 120, x - 12, 150, col); linePx(fb, x, 120, x + 12, 150, col);
  });
};
export const DRAW5_FAILED = new Map<string, string>();
/** draw shot `sh` at shot frame k (act frame f), falling back to the stick figures if it has no layout or throws */
export const drawShot5 = (fb: Buf, k: number, sh: ShotV5, f: number): ShotOut5 & {st: string; standin: boolean} => {
  const def = DRAW5[sh.id];
  if (def) {
    try {
      const out = withFootnoteStyle(OPT5.footnotes, () => def.draw(fb, k, sh, f)) ?? {};
      return {...out, st: def.st, standin: def.standin};
    } catch (e) {
      if (!DRAW5_FAILED.has(sh.id)) DRAW5_FAILED.set(sh.id, String((e as Error)?.stack ?? e).split('\n').slice(0, 3).join(' | '));
    }
  }
  fb.c.fill(PAL.N0, 0, 480 * RH);
  stickFallback(fb, k, sh);
  return {fallback: true, st: `STICK FALLBACK (${def ? 'the layout threw' : 'no layout'})`, standin: true};
};

// ================================================================== S1 · NOON, LAS VEGAS
R5('S1.01', 'S1.01');
S5('S1.02', 'C', 'UI-JOIN-CORNER join-corner drawNudgeJoin (the laptop corner under his hand, JOIN, his arrow beside it; its halo in 2 held steps) over v4\'s nudge; the glow floods in held steps, then BLUEPRINT_PRINT', (fb, k, sh) => {
  const nudge = mk(sh, 'nudge', 10), o1 = mk(sh, 'out1', 24), o2 = mk(sh, 'out2', 32), g = mk(sh, 'glow', 44), p = mk(sh, 'print', 52);
  const step = k < nudge ? 'set' : k < o1 ? 'nudge' : k < o2 ? 'out1' : k < g ? 'out2' : 'gone';
  drawNudgeJoin(fb, step, {pointer: 'beside', glow: k < o2 ? 0 : k < o2 + 6 ? 1 : 2});
  if (k >= g && k < p) { // the laptop's glow floods the frame in held steps (a lighting move), then the print
    const n = 1 + Math.floor((k - g) / 2);
    for (let y = 0; y < RH; y++) for (let x = 0; x < 480; x++) if (((x + y) & 3) < n) fb.set(x, y, stepColor(fb.get(x, y), 1));
  }
  return {print: k >= p ? 'blueprint' : undefined};
});
// ---- THE PLAN with her pointer (BP-NELEH-POINTER): v4's one sheet (plan4.ts) + her figure inked over it
const NX = 458; // her foot x, inside the sheet's double border (art-v5 demos r3)
const BRACKET: [number, number, number, number] = [176, PLAN4.FOOT + 3, 96, 24]; // MAS / CEO + GERG / CO-FOUNDER plates
const THREE: [number, number] = [96, PLAN4.FOOT - 14], PLATES: [number, number] = [224, PLAN4.FOOT + 14], FOUR: [number, number] = [360, PLAN4.FOOT - 40];
const ARROW: [number, number] = [PLAN4.arrow.x, PLAN4.arrow.y0 + 14], COMPANY: [number, number] = [PLAN4.company.x + 150, PLAN4.company.y + 40];
S5('S1.03', 'C', 'v4 plan4.ts THE PLAN (one sheet, the tilt) + BP-NELEH-POINTER bp-pointer bpNeleh at the sheet\'s right edge from the stamp: points at the three, taps the MAS / GERG plates (a drafting callout to them; bpBracket lights), sweeps to the four (her page glows on "us"), the arrow, the company; rides the tilt', (fb, k, sh) => {
  drawPlan4(fb, asV4(sh, 'S1.03'), k);
  const stamp = mk(sh, 'stamp', 7);
  if (k < stamp) return {full: true};
  const nine = mk(sh, 'nine', 33), plates = mk(sh, 'plates', 100), four = mk(sh, 'four', 128), us = mk(sh, 'us', 136), box = mk(sh, 'box', 166);
  const arrow = mk(sh, 'arrow', 187), company = mk(sh, 'company', 216), t0 = mk(sh, 'tilt', 189);
  const oy = Math.max(0, Math.min(60, k - t0)); // plan4's tilt: 1 px a frame, the figure rides the sheet
  const up = (p: [number, number]): [number, number] => [p[0], p[1] - oy];
  const L3 = lineOf5(sh, 'a5-25-03');
  let pose: BpNelehPose = {kind: 'rest'};
  if (k >= nine && k < plates) pose = {kind: 'point', at: up(THREE)};
  else if (k >= plates && k < four) pose = {kind: 'point', at: up(PLATES), tap: k >= plates + 2 && k < plates + 5 ? 1 : 0,
    // a4p5 r2's drafting callout: routed under the labels to a hot arrow at the MAS / GERG bracket (a dotted leader across
    // the row of chairs read as ending on any of them)
    callout: {box: [BRACKET[0], BRACKET[1] - oy, BRACKET[2], BRACKET[3]], rail: PLAN4.FOOT + 41 - oy}};
  else if (k >= four && k < box) pose = sweep(k, four, 12, up([216, PLAN4.FOOT - 10]), up(FOUR));
  else if (k >= box && k < arrow) pose = {kind: 'point', at: up([PLAN4.six.x + 40, PLAN4.six.y + PLAN4.six.h - 6])};
  else if (k >= arrow && k < company + 12) pose = {kind: 'point', at: up(k < t0 + 30 ? ARROW : COMPANY)};
  else if (L3 && k >= L3.e) pose = {kind: 'rest'};
  inkOver(fb, (b) => {
    if (k >= plates && k < four) bpBracket(b, BRACKET[0], BRACKET[1] - oy, BRACKET[2], BRACKET[3], k - plates);
    bpNeleh(b, NX, PLAN4.FOOT - oy, pose, k, {glow: k >= us && k < us + 14, knock: true});
  });
  return {full: true};
});
S5('S1.04', 'C', 'v4 plan4.ts the 2x zeros detail + BP-NELEH-POINTER bpTipIn: the pointer\'s tip on the key ring, then on the CEO box ("And the CEO?"); bpVoice: MADA\'s spinner icon, turning while he speaks', (fb, k, sh, f) => {
  drawPlan4(fb, asV4(sh, 'S1.04'), k);
  const tipCeo = mk(sh, 'tipCeo', 124), jangle = mk(sh, 'jangle', 7);
  inkOver(fb, (b) => {
    if (k >= jangle && k < tipCeo) bpTipIn(b, [446, 104], [0.55, -1], 120, k >= jangle + 2 && k < jangle + 5 ? 1 : 0);
    else if (k >= tipCeo) bpTipIn(b, [150, 126], [0.55, -1], 150, k >= tipCeo && k < tipCeo + 3 ? 1 : 0);
    if (k >= tipCeo) bpVoice(b, 34, 44, f, talking5(sh, k, 'MADA'));
  });
  return {full: true};
});
S5('S1.05', 'C', 'v4 plan4.ts the path, the curl, the tear, re-clocked on the v5 marks; her figure is the paper walker in the row (the set-down pose is not drawn: the fold covers the sheet\'s right edge)', (fb, k, sh) => {
  drawPlan4(fb, asV4(sh, 'S1.05'), k);
  return {full: true};
});
R5('S1.06', 'S1.06');
S5('S1.07', 'C', 'v4 S1.07 (callgrid G5 on ONE clock, the NELEH card, the dialog on the beat) + STATE-SMALL 5: ALYI\'s tile takes the speaking ring and a silent mouth (callgrid TileState.mouth) + STYLE-1G-NEON: his own tile\'s neon on the 8-frame guardrail', (fb, k, sh, f) => {
  const b = ui();
  const card = mk(sh, 'card', 9), cardEnd = mk(sh, 'cardEnd', 84), dlg = mk(sh, 'dialog', 110), sp0 = mk(sh, 'speak', 84), sp1 = mk(sh, 'speakEnd', 132);
  callChrome(b, {title: 'board sync', clock: null, controls: false});
  const talk = k >= sp0 && k < sp1;
  IDS5.forEach((t, i) => {
    const r = G5[i];
    if (t.id === 'mas') { drawTile(b, {...masTileState(k < 14 ? k - 2 : undefined), ...r, neonGuard: OPT5.neonGuard}, f); return; }
    const st = {...r, id: t.id, name: t.name, vote: 3 as const, muted: t.id === 'off' ? true : undefined, open: k < 14 ? k - i * 2 : undefined,
      ...(t.id === 'alyi' && talk ? {speaking: true, mouth: silentMouth(k - sp0)} : {})};
    if (OPT5.soft1G && k >= 14) drawTileSoft(b, st, f); else drawTile(b, st, f);
  });
  wifi(b);
  if (k >= dlg) dialog26(b, k, {k0: dlg});
  putUI(fb, b, false);
  if (k >= card && k < Math.min(cardEnd, dlg)) blipCard(fb, k - card, 'NELEH', 'NELEH', 'READ THE CHARTER. LITERALLY.', 'FOOTNOTES: ∞', {f}, 'R');
});
R5('S1.08', 'S1.08');
S5('S1.09', 'C', 'v4 S1.09 as it was (G5 + dialog; the ALYI / CO-FOUNDER arrow stepping onto Cancel, Cancel lit under it; the click; the masked GLYPH dissolve (its layers, drawn by the host) + G5 -> G4; the notice) with his tile\'s neon on the 1.G guardrail (STYLE-1G-NEON)', (fb, k, sh, f) => {
  const b = ui();
  const c = mk(sh, 'click', 57), s1 = mk(sh, 'step1', 19), s2 = mk(sh, 'step2', 38);
  const layers: GlyphLayer[] = [];
  const masT = {...masTileState(), neonGuard: OPT5.neonGuard};
  if (k < c + 2) {
    callChrome(b, {title: 'board sync', clock: null, controls: false});
    board4(b, f, G5.slice(1));
    drawTile(b, masT, f);
    wifi(b);
    dialog26(b, 99, {cancelDown: k >= c});
    const [cbx, cby, cbw, cbh] = dialogButton(DLG.x, DLG.y, 'cancel', DLG.w);
    const P: Array<[number, number]> = [[G5[1].x + 60, G5[1].y + 44], [G5[1].x + 20, G5[1].y + 70], [cbx + cbw - 10, cby + 11], [cbx + 30, cby + 9]];
    const i = k < s1 ? 0 : k < s2 ? 1 : k < c - 6 ? 2 : 3;
    const [px, py] = P[i];
    if (i >= 2) hoverRing(b, cbx, cby, cbw, cbh, ACCENT.ALYI ?? PAL.W5);
    drawPointer(b, px, py, k >= c);
    cursorTagBig(b, px, py, 'ALYI', ACCENT.ALYI ?? PAL.W5, 'CO-FOUNDER');
  } else {
    const kk = k - c;
    const rects = kk < 22 ? G5.slice(1) : slideTiles(G5.slice(1), G4, kk, 22, 8);
    callChrome(b, {title: 'board sync', clock: null, controls: false});
    board4(b, f, rects);
    wifi(b);
    const img = captureTile({...masT, open: undefined}, f - kk);
    const kd = kk - 2;
    if (kd >= 8) tilePlate(b, G5[0].x, G5[0].y + dropY(kd));
    layers.push(tileDrop(b, img, G5[0].x, G5[0].y, kd, {grey: true}));
    const n = textOf(sh, 'toast');
    if (n) callNotice(b, "You've been removed from the meeting.", k - n.s);
  }
  putUI(fb, b, false);
  return {layers};
});
R5('S1.10', 'S1.10');
R5('S1.11', 'S1.11');
R5('S1.12', 'S1.12');

// ================================================================== S2 · THAT NIGHT (all reused)
R5('S2.01', 'S2.01');
R5('S2.02', 'S2.02');
R5('S2.03', 'S2.03');
R5('S2.04', 'S2.04');
R5('S2.05', 'S2.05');

// ================================================================== S3 · FRIDAY, THE BOARD'S SIDE (Neleh's desk)
const otsScreen = () => new Buf(NDESK.screen.w, NDESK.screen.h, PAL.N1);
S5('S3.00a', 'N', 'ROOM-NELEH-DESK neleh-desk drawNelehDeskOTS (day, the slow whole-px push, her pen on step 1) + CAST-NELEH-OTS-R (she leans in on "Is his feed frozen?") + UI-CALL-V5 call-boardside drawBoardCall at 1:1 on her laptop (the empty fifth tile, the clock 11:59 -> 12:00, his tile connecting, perfectly still, the neon chasing behind him: STYLE-1G-NEON); ALYI lip-synced in his tile, NELEH in hers', (fb, k, sh, f) => {
  const con = mk(sh, 'connect', 33), lean = mk(sh, 'lean', 328);
  const s = otsScreen();
  drawBoardCall(s, {f, clock: clockAt(sh, k, '11:59'), fifth: k < con ? {kind: 'waiting', k} : {kind: 'mas', k: k - con}, speaking: boardSpeaker(sh, k), mouths: boardMouths(sh, k), softMas: OPT5.soft1G});
  const push = Math.min(NDESK.pushMax, Math.floor((k * (NDESK.pushMax + 1)) / Math.max(1, len5(sh))));
  drawNelehDeskOTS(fb, f, {time: 'day', push, pen: 'step1', neleh: {turn: k >= lean ? 1 : 0}, screen: s});
});
S5('S3.01', 'C', 'UI-CALL-V5 drawBoardCall in ROOM-NELEH-DESK drawNelehBezel (day): his tile simply goes, the four close ranks, the notice MAS MANALT was removed from the meeting., the MAS MANALT · audio chip lit while "super." plays, then greyed (v4\'s live caption is gone)', (fb, k, sh, f) => {
  const rm = mk(sh, 'removed', 1), sOn = mk(sh, 'superOn', 37), sEnd = mk(sh, 'superEnd', 56), grey = mk(sh, 'grey', 68);
  const n = textOf(sh, 'toast');
  const s = sui();
  const level = k >= sOn && k < sEnd ? 1 + ((k >> 2) % 3) : 0;
  drawBoardCall(s, {f, clock: '12:00', removed: k >= rm ? k - rm : undefined, fifth: {kind: 'mas', k: 99}, audio: {level, greyed: k >= grey},
    notice: n ? {text: n.text || BOARD_NOTICE.removed, k: k - n.s} : null, speaking: boardSpeaker(sh, k), mouths: boardMouths(sh, k), softMas: OPT5.soft1G});
  drawNelehBezel(fb, s, {time: 'day'});
});
R5('S3.02', 'S3.02');
S5('S3.03', 'C', 'UI-BLOG-DRAFT blog-draft drawBlogDraft in drawNelehBezel (day): the post in its editor, both sentences, Post; her pointer onto Post, the click on the tick, PUBLISHED; the call small in the corner', (fb, k, sh, f) => {
  const ptr = mk(sh, 'point', 334), post = mk(sh, 'post', 358);
  const s = sui();
  drawBlogDraft(s, {f, k, pointer: k < ptr ? 'rest' : 'post', click: k >= post ? k - post : undefined});
  drawNelehBezel(fb, s, {time: 'day'});
});
S5('S3.04', 'N', 'ROOM-NELEH-DESK drawNelehDeskOTS (day, held, pen gone) + UI-CALL-V5: Rima\'s join (the ring, the hard spotlight searching, landing on her slot), STATE-SMALL 8 her jacket smoothed (rima-v5), the speaking ring passing between RIMA, ALYI and NELEH (all lip-synced in their tiles); platePx RIMA TAMURI · HIS CTO', (fb, k, sh, f) => {
  const j = mk(sh, 'join', 4), sm = mk(sh, 'smooth', 134);
  const s = otsScreen();
  const hand = k >= sm && k < sm + 16 ? ((k - sm) >> 3) % 2 ? 'smooth1' : 'smooth0' : 'none';
  drawBoardCall(s, {f, clock: '12:04', removed: 999, fifth: k < j ? null : {kind: 'rima', k: k - j, mouth: mouth5(sh, k, 'RIMA'), lid: blink(k, 5), hand},
    speaking: boardSpeaker(sh, k), mouths: boardMouths(sh, k)});
  drawNelehDeskOTS(fb, f, {time: 'day', push: 4, pen: 'gone', neleh: {turn: 0}, screen: s});
  const t = textOf(sh, 'plate');
  if (t && k < t.e) { const [name, lines] = plateOf(t.text, 1); platePx(fb, 22, 150, name, lines.join(' · '), k - t.s, PAL.P2, pt, pw); }
});
S5('S3.04b', 'N', '[MCU] NELEH right third, brow query (cast/neleh nelehPortrait, lip-sync) over ROOM-NELEH-DESK drawNelehDeskWall (the soft shelf wall, day); Rima\'s "More. Soon." plays on her face', (fb, k, sh) => {
  held(fb, 's5:s304b-wall', (b) => drawNelehDeskWall(b, {time: 'day', soft: 2}));
  drawBust(fb, nelehPortrait({...NELEH_PORTRAIT_DEFAULT, brow: 'query', mouth: mouth5(sh, k, 'NELEH'), lid: blink(k, 3), look: -1}), {third: 'R'});
});
S5('S3.06', 'C', 'v4 S3.06 (the all-hands from the back, framed for the match cut; Alyi in the doorway) + CAST-EMP-STAND employee-stand drawEmployeeStanding: tile 22 already standing, hand up, then down, still standing; her mouth in her tile while she asks (the room flap)', (fb, k, sh) => {
  v4(fb, 'S3.06', k, sh);
  drawEmployeeStanding(fb, EMP_STAND_WHO, {rise: 3, hand: k < mk(sh, 'handDown', 89), mouth: roomMouth5(sh, k, 'EMPLOYEE')}, {dx: 30});
});
S5('S3.07', 'C', 'v3 27.08\'s [MCU·door] (the all-hands soft 1, the jamb and leaf) with CAST-ALYI-LOOK alyi-v5 alyiLook (lip-sync; his eyes to the employee at the pause, back); then he steps back into the dark doorway in 3 held steps (the rack) and it holds empty; no plate (v5 drops v4.1\'s)', (fb, k, sh) => {
  const lk = mk(sh, 'look', 44), back = mk(sh, 'lookBack', 61), step = mk(sh, 'step', 211);
  held(fb, 's5:s307-bg', (b) => { bullpenRoom(b, 0, {variant: 'allhands', door: 'open', handsUp: [22]}, {alyiDoor: false}); soft(b, 1); vignette(b, 318, 2); });
  const dir = k >= lk && k < back ? 'left' : 'ahead';
  const gone = k >= step ? Math.floor((k - step) / 4) + 1 : 0; // 1, 2 = stepping back (face steps down), 3 = gone
  if (gone < 3) drawBust(fb, alyiLook({mouth: mouth5(sh, k, 'ALYI'), eyes: 'open', t: 0, dir}), {third: 'R', dx: 6, faceK: gone * 2});
  dimRectL(fb, 318, 0, 162, RH, 2);
  doorFrame(fb, 282, 140, {leaf: 'right'});
});
S5('S3.05', 'C', 'UI-CALL-V5 drawBoardCall in drawNelehBezel (EVENING: her lamp on the bezel) + UI-POST post-card \'notify\' (Gerg\'s "…I quit.", his green glow, the lock\'s words) + keycapRain; ALYI and NELEH lip-synced in their tiles', (fb, k, sh, f) => {
  const post = mk(sh, 'post', 7), keys = mk(sh, 'keys', 16);
  const s = sui();
  drawBoardCall(s, {f, clock: '6:12', removed: 999, fifth: {kind: 'rima', k: 99, mouth: 'rest'}, speaking: boardSpeaker(sh, k), mouths: boardMouths(sh, k)});
  if (k >= post) drawPost(s, 4, 142, postSpec(sh, 'a5-27-P1'), {size: 'notify', w: 156, glow: true, k: k - post});
  if (k >= keys) keycapRain(s, k - keys);
  drawNelehBezel(fb, s, {time: 'evening'});
});

// ================================================================== S4 · THE WEEKEND, THE BOARDROOM
// ---- the hearts on the wall screen, the blue one landing on RIMA's tile (STATE-SMALL 1; shots.ts hearts() lands it on Mada)
const RIMA_X = HG[4].x + Math.round(HG[4].w / 2), SPIN_X5 = HG[2].x + 75;
let HEART_PLAN5: PileHeart[] | null = null;
const heartPlan5 = () => (HEART_PLAN5 ??= (() => {
  const base = planPile({x0: 0, x1: SCR_W, count: 99999, t0: 30, ceiling: 20, floor: () => SCR_H, spawnAt: (i) => Math.pow(i, 0.62) * 1.0});
  const top = pileTopAt(base, RIMA_X, 1e9, SCR_H);
  return withBlueHeart(base, RIMA_X - 4, top - 11 - 9, 18);
})());
const hearts5 = (b: Buf, T: number) => {
  callChrome(b, {title: 'board sync', clock: null, controls: false});
  board4(b, T, HG.slice(0, 4));
  drawTile(b, {...HG[4], id: 'rima', name: 'RIMA TAMURI'}, T);
  const plan = heartPlan5();
  reactionBurst(b, HG[1].x + HG[1].w - 3, HG[1].y + HG[1].h - 3, T);
  drawPile(b, plan, T, {blue: 'skip'});
  const sy = Math.min(HG[2].y + 4, pileTopAt(plan, SPIN_X5, T, SCR_H) - 7);
  spinner(b, SPIN_X5, sy, T, {size: 'r3', dot: 2});
  const blue = plan[plan.length - 1];
  const ry = Math.min(HG[4].y + 10, pileTopAt(plan, RIMA_X, T, SCR_H) - 7);
  if (T >= blue.land) drawHeart(b, RIMA_X - 4, ry - 13, 4, BLUE);
  else { const p = pileHeartAt(blue, T); if (p) drawHeart(b, p[0], Math.min(p[1], ry - 13), 4, BLUE); }
  heartCounter(b, SCR_W - 40, 1, T < 0 ? 0 : Math.min(9999, plan.filter((h) => T >= h.land).length));
};
S5('S4.01', 'C', 'v4 S4.01 (avalanche planPile / drawPile over the board\'s grid on the wall screen, [SCR] bezel, re-clocked to the shot) with the one BLUE heart landing on RIMA\'s tile (STATE-SMALL 1) + UI-POST \'notify\' (his eulogy post scrolling in, the lock\'s words) in place of v4\'s postChip', (fb, k, sh) => {
  const bk = mk(sh, 'blue', 103), post = mk(sh, 'post', 21);
  const plan = heartPlan5(), blue = plan[plan.length - 1];
  const T = Math.round(28 + (k * (blue.land - 28 + 4)) / Math.max(1, bk));
  const b = sui(); hearts5(b, T);
  if (k >= post) drawPost(b, Math.max(24, SCR_W - Math.floor((k - post) * 44)), 82, postSpec(sh, 'a5-27-P2'), {size: 'notify', w: 210});
  putSCR(fb, b);
});
/** the boardroom's wall screen, small in the wide: the call buried in hearts; `rima` lights her tile (the spot's source) */
const wallScreen = (b: Buf, x: number, y: number, f: number, rima = false) => {
  rect(x - 3, y - 3, 70, 44, b.ink(PAL.N0)); rect(x - 2, y - 2, 68, 42, b.ink(PAL.G1));
  rect(x, y, 64, 38, b.ink(PAL.N2));
  for (let i = 0; i < 4; i++) { const tx = x + 2 + (i % 2) * 31, ty = y + 2 + Math.floor(i / 2) * 18; rect(tx, ty, 29, 16, b.ink(i === 3 ? (rima ? PAL.P1 : PAL.N1) : PAL.N4)); }
  for (let j = 0; j < 60; j++) { const hx = x + 1 + ((j * 29 + (j >> 2) * 7) % 62), hy = y + 38 - 1 - ((j * 13) % 22); b.set(hx, hy, (j + (f >> 3)) % 5 ? PAL.R2 : PAL.R3); b.set(hx + 1, hy, PAL.R2); }
  b.set(x + 48, y + 30, PAL.C6); // the blue one, on Rima's tile
};
const PHONE_IDS = ['STAFF', 'STAFF', 'INVESTORS', 'STAFF'];
S5('S4.02', 'C', 'v4 S4.02 (the boardroom wide at night, held: phones buzzing with caller IDs, blueprint, the QV laptop, the reflection, the wall screen small) + Neleh\'s room-scale mouth (open / rest) + STATE-SMALL 2: the phones step toward the edge on each buzz (0 -> 3; the first goes over in S4.06)', (fb, k, sh, f) => {
  const bz = mk(sh, 'buzz', 7), bz2 = mk(sh, 'buzz2', 203);
  const step = Math.min(3, (k >= bz ? 1 : 0) + (k >= bz + 15 ? 1 : 0) + (k >= bz2 ? 1 : 0));
  const buzz = (k >= bz && k < bz + 30) || (k >= bz2 && k < bz2 + 30);
  const m = roomMouth5(sh, k, 'NELEH');
  held(fb, `s5:s402-${step}-${buzz ? 1 : 0}-${m}`, (b) => boardRoom(b, 0, {blueprint: {word: false}, laptop: true, phones: {lit: true, buzz, step}, phoneSeats: ['A', 'C', 'D', 'R']}, {neleh: {mouth: m}, mada: true, alyi: true}));
  wallScreen(fb, 222, 30, f);
  if (k >= bz) { // each ringing phone's caller ID, lit on its own screen and hung just above it (the phones are 8 px at this size)
    const P: Array<[number, number]> = [[120, 153], [224, 151], [282, 153], [390, 160]];
    PHONE_IDS.forEach((s, i) => { const [px, py] = P[i]; const x = px + 4 - Math.round(pw(s) / 2), y = py + step * 3 - 13; rect(x - 2, y - 1, pw(s) + 4, 9, fb.ink(PAL.N0)); rect(x - 2, y + 8, pw(s) + 4, 1, fb.ink(PAL.C4)); pt(fb, s, x, y, PAL.C7); });
  }
});
S5('S4.04', 'C', 'v3 27.14\'s [OTS] onto the dark window (the boardroom plate, ALYI\'s reflection lip-synced, the phones step 3) NOT mirrored: CAST-NELEH-OTS-R drawNelehShoulderR (\'window\' rim) is her own right-shoulder drawing (art-needs §1.8)', (fb, k, sh) => {
  const bz = mk(sh, 'buzz', 2);
  const bg = new Buf(480, 270, PAL.N0);
  const o: BoardPlateOpts = {laptop: false, rolodex: true, blueprint: 0, phones: {lit: true, buzz: k >= bz && k < bz + 6, step: 3},
    reflection: {img: alyiReflection({mouth: mouth5(sh, k, 'ALYI'), eyes: 'open', t: k, mirror: true}), x: 60, y: 8, k: 1}};
  drawBoardPlate(bg, k, o); drawBoardPlateTable(bg, k, o); drawBoardPlateFront(bg, k, o);
  const DX = 40; // the window and his reflection sit left of centre, clear of her shoulder
  for (let y = 0; y < RH; y++) for (let x = 0; x < 480; x++) { const sx = x - DX; fb.c[y * 480 + x] = sx >= 0 ? bg.c[y * 480 + sx] : PAL.N1; }
  drawNelehShoulderR(fb, 480, RH, {light: 'window', turn: 0});
});
R5('S4.06', 'S4.06');
S5('S4.07', 'C', 'v4 S4.07\'s [MCU·PF] (NELEH right third, the boardroom stepping down behind her) with her line lip-synced + PROP-SPEAKERPHONE-MCU speakerphone drawSpeakerphoneMCU: she pulls the pod in (3 held steps) and dials four tones, one LED per seat, on the stick\'s DTMF spots', (fb, k, sh) => {
  const pull = mk(sh, 'pull', 72), tones = [mk(sh, 'tone1', 81), mk(sh, 'tone2', 90), mk(sh, 'tone3', 98), mk(sh, 'tone4', 106)];
  held(fb, 's5:s407bg', (b) => { boardBg({phones: {lit: true, buzz: false, step: 2}, reflection: null})(b); vignette(b, MCU_X.R + 56, 2); });
  soft(fb, 2 + Math.min(2, Math.floor(k / 6)));
  const talking = talking5(sh, k, 'NELEH');
  drawBust(fb, nelehPortrait({...NELEH_PORTRAIT_DEFAULT, lid: 0, look: -1, mouth: mouth5(sh, k, 'NELEH'), gaze: talking ? undefined : 'down'}), {third: 'R'});
  if (k >= pull) {
    const slide = Math.min(3, 1 + ((k - pull) >> 2)) as 1 | 2 | 3;
    const leds = tones.filter((t) => k >= t).length;
    const last = [...tones].reverse().find((t) => k >= t);
    const down = last !== undefined && k - last < 3;
    drawSpeakerphoneMCU(fb, {slide, leds, press: down ? tones.indexOf(last as number) : -1, down, hand: k < tones[0] - 4 ? 'pull' : 'dial'});
  }
});
// ---- THE SPLIT (v4 S4.08): the boardroom | the lighthouse, both calls in one held shot
const pane = (fb: Buf, src: Buf, sx: number, dx: number) => { for (let y = 0; y < RH; y++) for (let x = 0; x < 238; x++) fb.set(dx + x, y, src.get(sx + x, y)); };
const meterTag = (b: Buf, x: number, y: number, name: string, amt: string) => {
  const w = Math.max(pw(name), pw(amt)) + 10;
  rect(x, y, w, 30, b.ink(PAL.N0)); rect(x + 1, y + 1, w - 2, 28, b.ink(PAL.N2)); rect(x + 1, y + 1, w - 2, 1, b.ink(PAL.C5));
  pt(b, name, x + 5, y + 4, PAL.P1); rect(x + 5, y + 13, w - 10, 3, b.ink(PAL.L3)); pt(b, amt, x + 5, y + 19, PAL.W7);
  rect(x + Math.round(w / 2), y - 12, 1, 12, b.ink(PAL.G3));
};
const marioMouth = (v: Viseme): 0 | 1 | 2 => (v === 'rest' || v === 'M' || v === 'smile' ? 0 : v === 'A' || v === 'O' ? 2 : 1);
S5('S4.08', 'C', 'v4 S4.08\'s [SPLIT] (two 238 x 203 panes: the boardroom with the speakerphone lit | the lighthouse: the throne, the phones, the meters, the ELGOOG tag, NOZAMA\'s caller ID) + room-scale mouths for NELEH, MARIO and ADELINA; Mario\'s finger rise on "hypothetically"; Adelina crossing in, taking phone 1 ("no."), then phone 2 and handing it over; the v5 plates MARIO · RUNS THE RIVAL LAB · (REPORTED) and ADELINA · MARIO\'S CO-FOUNDER', (fb, k, sh) => {
  const click = mk(sh, 'click', 500), ring = mk(sh, 'ring', 4), ring2 = mk(sh, 'ring2', 514), grab = mk(sh, 'grab', 529);
  const raise = mk(sh, 'raise', 445), hand = mk(sh, 'handover', 586), ad0 = mk(sh, 'adelina', 442);
  const ad = lineOf5(sh, 'a5-27-32');
  const adS = ad ? ad.s : ad0 + 14;
  const nm = roomMouth5(sh, k, 'NELEH');
  const L = new Buf(480, 270, PAL.N0);
  held(L, `s5:split-L-${nm}`, (b) => boardRoom(b, 0, {blueprint: {word: false}, laptop: true, phones: {lit: false, step: 4}, speaker: 4}, {neleh: {mouth: nm}, mada: true, alyi: false}));
  const R = new Buf(480, 270, PAL.N0);
  const room = drawLighthouse(R, k, {meters: 2, ring1: k >= ring && k < adS ? ring : null, ring2: k >= ring2 && k < grab ? ring2 : null,
    throne: k < click ? 'on' : 'fallen', phone1: k >= adS - 4 && k < click ? 'off' : 'cradle', phone2: k >= grab ? 'off' : 'cradle'});
  const A = room.anchors as unknown as Record<string, [number, number]>;
  const marm: MarioArm = k >= raise && k < raise + 4 ? 'raise' : k >= raise + 4 && k < click ? 'raise2' : k >= hand ? 'chest' : 'down';
  const [mx, my] = A.marioDesk;
  blitImg(R, marioImg({...MARIO_BASE, arm: marm, mouth: room3Mouth5(sh, k, 'MARIO'), blink: blink(k, 4) > 0}), mx - MARIO_FOOT[0], my - MARIO_FOOT[1]);
  if (k >= ad0) { // she crosses into the pane from the right (whole px on 2s) and takes the phone on her line
    const ax = Math.max(196, 300 - Math.floor(on2(k - ad0) * 8));
    const arm: AdelinaArm = (k >= adS - 4 && k < adS) || (k >= grab && k < grab + 4) || (k >= hand && k < hand + 6) ? 'reach'
      : (k >= adS && k < click) || (k >= grab + 4 && k < hand) ? 'phone' : 'down';
    const am = lipOn5(sh, k, 'ADELINA') ? roomMouth5(sh, k, 'ADELINA') : 'smile';
    drawAdelinaRoom(R, ax, 199, {...ADELINA_ROOM_DEFAULT, arm, mouth: am});
  }
  pane(fb, L, 110, 0);
  pane(fb, R, 64, 242);
  rect(238, 0, 4, RH, fb.ink(PAL.N0));
  meterTag(fb, 404, 56, 'ELGOOG', 'UP TO $2B');
  for (const t of sh.texts.filter((x) => x.kind === 'plate')) {
    if (k < t.s || k >= t.e) continue;
    const [name, lines] = plateOf(t.text, 2);
    plateN(fb, 248, 8, name, lines, k - t.s, name === 'MARIO' ? PAL.F5 : PAL.W5);
  }
  if (k >= ring2 && k < grab + 30) { const s = 'NOZAMA', w = pw(s) + 6, x = 440 - Math.round(w / 2), y = 132; rect(x, y, w, 10, fb.ink(PAL.N0)); rect(x, y + 9, w, 1, fb.ink(PAL.C4)); pt(fb, s, x + 3, y + 2, PAL.C7); }
});
const feedPhase = (k: number, turn: number, walk: number): [LobbyFeedPhase, number] => (k < turn ? ['stand', k] : k < walk ? ['turn', k - turn] : ['walk', k - walk]);
S5('S4.09', 'C', 'PLATE-BOARD-SCREEN board-screen drawBoardScreenOTS (Sunday by day; CAST-NELEH-OTS-R her shoulder) with ROOM-LOBBY-CCTV-DESK lobby-feed drawLobbyFeed at 1:1 in the glass (1.K: his GUEST card in the feed\'s ZOOM; on "here" he turns and walks out through the drum) + UI-POST \'notify\' (his badge post) in the feed\'s corner; ALYI\'s reflection lip-synced', (fb, k, sh, f) => {
  const turn = mk(sh, 'turn', 330), walk = mk(sh, 'walk', 336), post = mk(sh, 'post', 19);
  const feed = new Buf(FEED_W, FEED_H, PAL.N0);
  const [phase, kk] = feedPhase(k, turn, walk);
  drawLobbyFeed(feed, {f, phase, k: kk});
  if (k >= post) drawPost(feed, 6, FEED_H - 44, postSpec(sh, 'a5-27-P3'), {size: 'notify', w: 150, k: k - post});
  drawBoardScreenOTS(fb, f, {feed, alyi: {mouth: mouth5(sh, k, 'ALYI')}, neleh: {turn: 0}});
});
S5('S4.10', 'C', 'v4 S4.10 (the boardroom wide, now night: the spot swings in 3 held positions onto TTEMME in the CEO chair, the blank sticky note) with the spot starting from RIMA\'s tile on the small wall screen (STATE-SMALL 3), the plate TTEMME · RAN A STREAMING SITE, and UI-CHAT-ROOM chat-panel \'room\' at his elbow', (fb, k, sh, f) => {
  const step = Math.max(0, Math.min(2, Math.floor((k - mk(sh, 'swing', 0)) / 8)));
  const spots = [{x: 254, y: 56, r: 20}, {x: 254, y: 82, r: 26}, {x: 254, y: 100, r: 30}];
  held(fb, `s5:s410-${step}`, (b) => boardRoom(b, 0, {sticky: {seat: 'C', text: ''}, spot: spots[step], laptop: true, blueprint: {word: false}, phones: {step: 4}}, {neleh: {}, mada: true, alyi: true, ttemme: step >= 1 ? {} : null}));
  wallScreen(fb, 222, 30, f, step === 0);
  const chat = textOf(sh, 'label', 'LIVE');
  if (chat && k >= chat.s && step >= 1) drawChatPanel(fb, BR.SEATS.C.x + 30, BR.WALL_FLOOR_Y - 44, 'room', f);
  const t = textOf(sh, 'plate');
  if (t) { const [name, lines] = plateOf(t.text, 1); platePx(fb, 22, 150, name, lines.join(' · '), k - t.s, PAL.U5, pt, pw); }
});
S5('S4.10b', 'N', 'PLATE-BOARD-HEAD boardroom-head drawBoardHead2S: NELEH standing at the table\'s side (neleh-medium, lip-sync), TTEMME in the CEO chair (CAST-TTEMME-MEDIUM, lip-sync), MADA soft beyond with his spinner, UI-CHAT-ROOM at his elbow; PROP-FOLDER: the sealed folder slides across in held steps, he breaks the seal and reads it turned away, closes it; nothing inside is ever shown', (fb, k, sh, f) => {
  const slide = mk(sh, 'slide', 276), up = mk(sh, 'up', 296), seal = mk(sh, 'seal', 304), open = mk(sh, 'open', 310), close = mk(sh, 'close', 325);
  let folder: FolderState | null = null;
  if (k >= slide && k < up) folder = {kind: 'table', slide: Math.min(3, Math.floor(((k - slide) * 4) / Math.max(1, up - slide))) / 3};
  else if (k >= up && k < seal) folder = {kind: 'up', seal: 'whole', open: 0};
  else if (k >= seal && k < open) folder = {kind: 'up', seal: 'broken', open: 0};
  else if (k >= open && k < close) folder = {kind: 'up', seal: 'broken', open: k < open + 3 ? 1 : 2};
  else if (k >= close) folder = {kind: 'up', seal: 'broken', open: 0};
  const reading = k >= open && k < close;
  drawBoardHead2S(fb, f, {
    ttemme: {mouth: mouth5(sh, k, 'TTEMME'), lid: blink(k, 6), head: reading ? 'down' : '34', brow: k >= close ? 'unsure' : 'level'},
    neleh: {mouth: mouth5(sh, k, 'NELEH'), lid: blink(k, 2)},
    mada: {spin: f}, folder, chat: f,
  });
});
S5('S4.11', 'C', 'v4 S4.11\'s [LOW·desk] (the boardroom soft behind, TTEMME right third lip-synced (ttemmePortrait), his LIVE · CHAT overlay, the table edge) with PROP-HOURGLASS-INSERT hourglass-insert drawHourglassXL at insert scale in place of v4\'s 2x blow-up: the flip in its held drawings (hgxFlip), the sand starting', (fb, k, sh) => {
  const st = rackStep(k, 10);
  const [, kB] = RACK[st];
  held(fb, `s5:s411:${kB}`, (b) => { boardBg({laptop: false, rolodex: 'still', blueprint: false})(b); soft(b, 2 + Math.max(0, kB - 1)); vignette(b, 330, 2); });
  drawBust(fb, ttemmePortrait({...TTEMME_PORTRAIT_DEFAULT, mouth: mouth5(sh, k, 'TTEMME'), gaze: k < 14 ? 'sand' : 'cam', look: -1, brow: 'hype'}), {third: 'R', y: 22, faceK: RACK[st][0]});
  rect(378, 0, 102, 16, fb.ink(PAL.N0)); rect(378, 16, 102, 1, fb.ink(PAL.U3));
  rect(384, 5, 6, 6, fb.ink(PAL.R3)); pt(fb, 'LIVE · CHAT', 394, 4, PAL.P2);
  drawChatOverlay(fb, 378, 17, 102, RH - 17, k);
  rect(377, 0, 1, RH, fb.ink(PAL.N0));
  rect(0, 176, 480, 27, fb.ink(PAL.D1)); rect(0, 176, 480, 1, fb.ink(PAL.D3)); rect(0, 177, 480, 1, fb.ink(PAL.C2));
  const fl = hgxFlip(k - mk(sh, 'flip', 2));
  drawHourglassXL(fb, 96, 176 - HGX.h + 4 + fl.dy, {moved: fl.flipped ? Math.floor(Math.max(0, k - 20) / 15) : 0, running: fl.flipped && !fl.hand, f: k, pose: fl.pose, hand: fl.hand});
});
R5('S4.12', 'S4.12');
S5('S4.13', 'C', 'v4 S4.13\'s [MCU·door] (the boardroom plate with the slate door, soft 2; the new doorway) with CAST-TASYA-PHONE tasya-phone tasyaPhonePortrait: pleased, the key ring jangling, then reading his statement off his phone (lip-sync); the plate TASYA · THE LANDLORD · MACROSOFT · NOPEAI RUNS ON ITS SERVERS; the sign moves to S4.13e', (fb, k, sh) => {
  const rd = mk(sh, 'read', 122), jg = mk(sh, 'jangle', 9);
  held(fb, 's5:s413', (b) => { boardBg({slate: true, door: 5, laptop: false, rolodex: 'still'})(b); soft(b, 2); vignette(b, 318, 2); });
  const talking = lipOn5(sh, k, 'TASYA');
  const reading = k >= rd;
  drawBust(fb, tasyaPhonePortrait({mouth: talking ? mouth5(sh, k, 'TASYA') : 'smile', lid: blink(k, 9), brow: 'warm', arms: reading ? 'none' : 'ring',
    jangle: (!reading && k >= jg && k < jg + 12 ? (k >> 1) % 2 : 0) as 0 | 1, read: reading}), {third: 'R', dx: 4});
  doorFrame(fb, 246, 172, {leaf: 'left', leafW: 58, light: PAL.N5});
  const t = textOf(sh, 'plate');
  if (t && k < t.e) { const [name, lines] = plateOf(t.text, 2); plateN(fb, 22, 142, name, lines, k - t.s, PAL.C6); }
});
S5('S4.13c', 'N', 'PLATE-BOARD-HEAD boardroom-head drawBoardHeadM: TTEMME at the head turned to the open slate door (CAST-TTEMME-MEDIUM, pleased and slightly lost: he nods back on his name), TASYA small in the door reading (room-scale mouth), UI-CHAT-ROOM', (fb, k, sh, f) => {
  const nod = mk(sh, 'nod', 6);
  const n = k - (nod + 4);
  const tn = (n < 0 ? 0 : n < 2 ? 1 : n < 4 ? 2 : n < 6 ? 1 : 0) as 0 | 1 | 2;
  drawBoardHeadM(fb, f, {ttemme: {nod: tn, mouth: 'smile', brow: 'unsure', lid: blink(k, 6)}, tasya: {arm: 'clasp', mouth: lipOn5(sh, k, 'TASYA') ? roomMouth5(sh, k, 'TASYA') : 'smile'},
    tasyaNod: k >= nod && k < nod + 6 ? 1 : 0, chat: f});
});
S5('S4.13d', 'N', 'PLATE-BOARD-SCREEN board-screen drawBoardScreen2S at night: NELEH medium at the right, her pen stopped mid-air; the wall screen with ALYI\'s reflection turning to look at the open slate door (CAST-ALYI-LOOK \'door\') as the names land', (fb, k, sh, f) => {
  const look = mk(sh, 'look', 15);
  drawBoardScreen2S(fb, f, {alyi: {look: k >= look ? 'door' : 'ahead', mouth: 'rest'}, neleh: {arm: 'marker', head: '34', mouth: 'rest', lid: blink(k, 2)}, door: 'open'});
});
R5('S4.13e', 'S4.13', 'the sign beat split out: the lock\'s sign text from f4');
R5('S4.14', 'S4.14');
R5('S4.15', 'S4.15');

// ================================================================== CARD + S5 · HIS SIDE, 2 AM
R5('S5.01', 'S5.01');
R5('S5.02', 'S5.02');
const PHONE_S = {x0: 124, y0: 36, x1: 194, y1: 174}; // kits/inserts-mas PHONE29.screen (71 x 139)
const HEART5 = ['.#.#.', '#####', '#####', '.###.', '..#..'];
/** UI-POST's card grammar (its 9 px avatar chip, the poster's name, the words in the record's casing, the heart row)
 *  re-laid for the 71 px screen of v4's S5.03 phone: the kit's own 'phone' size is 216 px wide and can't fit (at 67 px
 *  its name and handle collide). Returns the card's height. k = frames since it landed (3 held open steps). */
const phoneCard = (b: Buf, x: number, y: number, w: number, spec: PostSpec, o: {hearted: boolean; hearts: number; k?: number}) => {
  const lines = pwrap(spec.text, w - 8);
  const h = 15 + lines.length * 10 + 11;
  const k = o.k ?? 99;
  if (k < 0) return h;
  const open = k >= 3 ? 1 : [0.2, 0.5, 0.8][k];
  const hh = Math.max(3, Math.round(h * open)), yy = y + Math.round((h - hh) / 2);
  rect(x, yy, w, hh, b.ink(PAL.N2)); rect(x, yy, w, 1, b.ink(PAL.N4));
  if (open < 1) return h;
  drawAvatar9(b, x + 3, y + 3, spec.who);
  let name = spec.who === 'staff' ? POSTERS.staff.handle : POSTERS[spec.who].name; // the flood: staff accounts
  while (pw(name) > w - 18 && name.includes(' ')) name = name.slice(0, name.lastIndexOf(' ')); // whole words that fit
  pt(b, name, x + 15, y + 4, PAL.P2);
  lines.forEach((l, i) => pt(b, l, x + 4, y + 15 + i * 10, PAL.P1));
  const fy = y + h - 9, col = o.hearted ? PAL.R3 : PAL.N6;
  HEART5.forEach((r, j) => { for (let i = 0; i < 5; i++) if (r[i] === '#') b.set(x + 4 + i, fy + j, col); });
  if (o.hearts > 0) pt(b, String(o.hearts), x + 12, fy - 1, col);
  return h;
};
S5('S5.03', 'C', 'v4 S5.03\'s inserts-mas drawPhoneInsert29 (the true shot: the dark desk, his thumb, the Orb) with post cards in UI-POST\'s grammar on its screen (re-laid here for the 71 px phone: phoneCard): Rima\'s post, then the same words from everyone, newest at the bottom under his thumb, each hearted on the stick\'s tap spots, the counts climbing (the flood)', (fb, k, sh) => {
  const taps = [mk(sh, 'tap1', 28), mk(sh, 'tap2', 43), mk(sh, 'tap3', 58), mk(sh, 'tap4', 73), mk(sh, 'tap5', 88)];
  const base = postSpec(sh, 'a5-29-P1');
  const HEARTS = [1, 2, 4, 16, 99];
  // the thumb runs on the insert's own 15-frame beat (inserts-mas heartTapAt): aligned so its taps land on the stick's
  // tap spots, hovering before the first
  const fThumb = k < taps[0] - 2 ? 4 : k - taps[0] + 30;
  drawPhoneInsert29(fb, {mode: 'true', f: fThumb, screen: (bb) => {
    const W = PHONE_S.x1 - PHONE_S.x0 + 1, H = PHONE_S.y1 - PHONE_S.y0 + 1;
    const scr = new Buf(W, H, PAL.N1);
    const n = 1 + taps.filter((t) => k >= t + 8).length; // Rima's card, then one more 8 f after each heart
    let y = H - 1;
    for (let i = n - 1; i >= 0 && y > 0; i--) {
      const spec: PostSpec = i === 0 ? base : {...base, who: 'staff'};
      const lit = i < taps.length && k >= taps[i];
      const h = phoneCard(new Buf(1, 1, 0), 0, 0, W - 2, spec, {hearted: lit, hearts: 0}); // measure
      y -= h + 2;
      phoneCard(scr, 1, y, W - 2, spec, {hearted: lit, hearts: lit ? HEARTS[i] : 0, k: i > 0 && i === n - 1 ? k - (taps[i - 1] + 8) : undefined});
    }
    for (let yy = 0; yy < H; yy++) for (let xx = 0; xx < W; xx++) bb.set(PHONE_S.x0 + xx, PHONE_S.y0 + yy, scr.get(xx, yy));
  }});
});
S5('S5.04', 'C', 'v4 S5.04\'s twoshots drawDark2S + orbToLanyard (the iris steps off the phone onto the GUEST lanyard) with STATE-SMALL 7: Mas turns his head to the Orb and answers aloud, lip-synced ("the badge was a joke.")', (fb, k, sh) => {
  const m = mk(sh, 'lanyard', 11), turn = mk(sh, 'turn', 18);
  const look = orbStep(k, m - 30, [DPLATE_LOOK.phone, DPLATE_LOOK.phone, DPLATE_LOOK.lanyard], 15);
  drawDark2S(fb, k, {mas: {arm: 'phone', head: k < turn ? 'down' : '34', look: k < turn ? -1 : 1, mouth: mouth5(sh, k, 'MAS'), lid: blink(k, 7)}, orb: {look},
    plate: {tally: 3, lanyard: true, phone: 'up', boardGrid: true}});
});
R5('S5.05', 'S5.05');
// ---- his monitor across the dark room (v4 S5.09's [OTS]): the letter open behind, Gerg's tile ringing, opening, full
const T509 = {x: 110, y: 22, w: 258, h: 138};
let LETTER_BEHIND: Buf | null = null;
const letterBehind = (f: number) => (LETTER_BEHIND ??= (() => { const b = new Buf(480, 270, PAL.N0); drawStaffLetter(b, {k: 0, f, count: 505, quotes: [9999, 9999, 9999], window: 0}); return b; })());
const s509 = (fb: Buf, k: number, sh: ShotV5, f: number, opened: boolean) => {
  const ring = mk(sh, 'ring', 4), click = mk(sh, 'click', 24), g = mk(sh, 'glance', 9999);
  const talk = talking5(sh, k, 'GERG');
  held(fb, 's5:s509bg', (b) => { darkBg({tally: 3, glass: true, lanyard: true, phone: 'up'})(b); shiftRoom(b, -60); soft(b, 3); vignette(b, 240, 2); });
  const T = T509;
  rect(T.x - 8, T.y - 8, T.w + 16, T.h + 16, fb.ink(PAL.G1)); rect(T.x - 8, T.y - 8, T.w + 16, 1, fb.ink(PAL.G3)); rect(T.x - 1, T.y - 1, T.w + 2, T.h + 2, fb.ink(PAL.N0));
  const pov = new Buf(480, 270, PAL.N0);
  const openK = opened ? 99 : k - click;
  if (openK >= 0) {
    const open = openK >= 6 ? 1 : [0.1, 0.33, 0.66][Math.min(2, openK >> 1)];
    if (open < 1) { const L = letterBehind(f); for (let y = 0; y < T.h; y++) for (let x = 0; x < T.w; x++) pov.set(T.x + x, T.y + y, L.get(20 + x, 10 + y)); }
    const gb = new Buf(480, 270, PAL.N0);
    drawGergMediumPOV(gb, 0, 0, {head: talk ? 'talk' : k >= g ? 'up' : 'type', mouth: mouth5(sh, k, 'GERG')}, {f: k, speaking: talk, typing: !talk && k < g - 4, open});
    const hh = open >= 1 ? T.h : Math.max(3, Math.round(144 * open)) + 4, y0 = T.y + Math.round((T.h - hh) / 2);
    for (let y = open >= 1 ? T.y : y0; y < (open >= 1 ? T.y + T.h : y0 + hh); y++) for (let x = T.x; x < T.x + T.w; x++) pov.set(x, y, gb.get(x, y));
  } else {
    const L = letterBehind(f);
    for (let y = 0; y < T.h; y++) for (let x = 0; x < T.w; x++) pov.set(T.x + x, T.y + y, L.get(20 + x, 10 + y));
    if (k >= ring) { // his tile ringing in the monitor's corner: a small green-rimmed tile, its ring pulsing on 6s
      const cx = T.x + T.w - 70, cy = T.y + T.h - 44;
      rect(cx - 1, cy - 1, 66, 40, pov.ink(PAL.N0)); rect(cx, cy, 64, 38, pov.ink(PAL.L0));
      pt(pov, 'GERG', cx + 4, cy + 26, PAL.L3);
      if (Math.floor((k - ring) / 6) % 2 === 0) for (const d of [2, 3]) { rect(cx - d, cy - d, 64 + 2 * d, 1, pov.ink(PAL.L3)); rect(cx - d, cy + 37 + d, 64 + 2 * d, 1, pov.ink(PAL.L3)); rect(cx - d, cy - d, 1, 38 + 2 * d, pov.ink(PAL.L3)); rect(cx + 63 + d, cy - d, 1, 38 + 2 * d, pov.ink(PAL.L3)); }
    }
  }
  for (let y = 0; y < T.h; y++) for (let x = 0; x < T.w; x++) fb.set(T.x + x, T.y + y, pov.get(T.x + x, T.y + y));
  rect(T.x + T.w / 2 - 12, T.y + T.h + 8, 24, 20, fb.ink(PAL.G1));
  for (let y = T.y + T.h + 8; y < RH; y++) for (let x = T.x - 30; x < T.x + T.w + 30; x++) if (((x + y) & 3) === 0) fb.set(x, y, stepColor(fb.get(x, y), 1));
  blitImg(fb, shoulder(mas({head: '34'}), 70, PAL.L3, 1, true), -38, 30);
};
S5('S5.09', 'C', 'v4 S5.09\'s [OTS] (his monitor across the dark room, soft 3; shoulder(masPortrait) in front with the monitor\'s green rim) with the letter already open on it (UI-LETTER-V5\'s page at 1:1) and STATE-SMALL 6: Gerg\'s corner tile rings, Mas clicks, it opens in 3 held steps (drawGergMediumPOV open), then Gerg full, typing, lip-synced', (fb, k, sh, f) => { s509(fb, k, sh, f, false); });
let LETTER_L: ReturnType<typeof letterLayout> | null = null;
S5('S5.06', 'C', 'UI-LETTER-V5 staff-letter drawStaffLetter: the page with its bezel and the window; the three quotes land as Gerg reads them (the lock\'s texts), SIGNED 505 -> 650 -> 700 -> 745 / 770 rolling on the odometer with its clunk, a slow whole-px scroll (1 px / 2 f) that follows the quotes and stops on ALYI (REPORTED), lit; Gerg\'s small tile lip-synced; the window one step greyer from 700', (fb, k, sh, f) => {
  const q: [number, number, number] = [mk(sh, 'q1', 40), mk(sh, 'q2', 207), mk(sh, 'q3', 344)];
  const sc = mk(sh, 'scroll', 457), alyi = mk(sh, 'alyi', 493), clunk = mk(sh, 'clunk', 450), c700 = mk(sh, 'c700', 310);
  const counts = sh.texts.filter((t) => t.kind === 'label' && /^SIGNED \d+/.test(t.text)).map((t) => ({s: t.s, v: parseInt(t.text.slice(7), 10)})).sort((a, b) => a.s - b.s);
  let count = counts.length ? counts[0].v : 505;
  for (let i = 1; i < counts.length; i++) {
    if (k < counts[i].s) break;
    const from = counts[i - 1].v, to = counts[i].v, n = Math.min(12, k - counts[i].s);
    count = from + Math.round(((to - from) * n) / 12); // the roll: whole numbers over half a second
  }
  const L = (LETTER_L ??= letterLayout());
  const stops: Array<[number, number]> = [[q[1], Math.max(0, L.quoteY[1] - 60)], [q[2], Math.max(0, L.quoteY[2] - 60)], [sc, Math.min(LETTER_SCROLL_MAX, Math.max(0, L.alyiY - 70))]];
  let scroll = 0;
  for (let t = 0; t <= k; t++) { const target = stops.filter(([at]) => t >= at).map(([, v]) => v).pop() ?? 0; if (scroll < target && t % 2 === 0) scroll += 1; }
  const talk = talking5(sh, k, 'GERG');
  drawStaffLetter(fb, {k, f, quotes: q, count, clunk: k >= clunk && k < clunk + 2, scroll: Math.min(LETTER_SCROLL_MAX, scroll), alyi: k >= alyi,
    gerg: {mouth: mouth5(sh, k, 'GERG'), head: talk ? 'talk' : 'type', typing: !talk}, window: k >= c700 ? 1 : 0});
});
S5('S5.07b', 'N', 'v3 29.15\'s [MCU·PF] (the QUIET BEAT: the dark room fallen away to the monitor\'s green and his cyan, Gerg\'s typing flickering on him; v4\'s unused S5.10) with Mas lip-synced ("alyi voted."); "He did both." off picture; the hold is his', (fb, k, sh) => {
  held(fb, 's5:s507b', (b) => { darkBg({phone: 'up', screen: undefined})(b); soft(b, 3); vignette(b, MCU_X.L + 56, 3); });
  if (k % 4 < 2) for (let y = 30; y < 150; y++) for (let x = 0; x < 60; x++) if (((x + y + k) & 3) === 0) fb.set(x, y, PAL.L1);
  drawBust(fb, mas({look: 0, mouth: mouth5(sh, k, 'MAS'), lid: blink(k, 8)}), {third: 'L'});
});
R5('S5.08', 'S5.08');
S5('S5.09-back', 'C', 'the S5.09 [OTS] again (the same setup, Gerg\'s tile open from the cut): Gerg typing, sunny, lip-synced; his keys stop and he looks up after "case" (the glance)', (fb, k, sh, f) => { s509(fb, k, sh, f, true); });
S5('S5.09b', 'C', 'v4 S5.09b\'s swaps-act4 drawGergTileWide (his tile fills the frame): the glance into his camera, at Mas, held, with his line lip-synced (STATE-SMALL 9); then his eyes drop and he types', (fb, k, sh) => {
  drawGergTileWide(fb, {eyes: k < mk(sh, 'type', 140) ? 'lens' : 'screen', f: k, mouth: mouth5(sh, k, 'GERG')});
});
S5('S5.11', 'C', 'twoshots drawDark2S (Mas lip-synced on "everyone."; the Orb turning to the door): the slate door steps up out of the shadow in held steps on the thunks, Tasya\'s sign taped to it (slateDoorSign), then ROOM-SLATE-DESKS slate-desks drawSlateDoorOpen: the key turns in 3 held drawings, the door opens a crack, and on "desk" wider: the labelled desks beyond in slate light', (fb, k, sh) => {
  const d = [mk(sh, 'door1', 4), mk(sh, 'door2', 12), mk(sh, 'door3', 19), mk(sh, 'door4', 26)];
  const key = mk(sh, 'key', 30), crack = mk(sh, 'crack', 50), open = mk(sh, 'open', 227);
  const door = d.filter((t) => k >= t).length as 0 | 1 | 2 | 3 | 4;
  drawDark2S(fb, k, {mas: {arm: 'rest', mouth: mouth5(sh, k, 'MAS'), lid: blink(k, 7)}, orb: {look: door >= 1 ? DPLATE_LOOK.door : DPLATE_LOOK.face}, plate: {tally: 3, lanyard: true, phone: 'up', door}});
  if (door >= 4) { drawSlateDoorOpen(fb, k, {key: keyTurnAt(k, key), gap: k >= open ? SLATE_GAP.open : k >= crack ? SLATE_GAP.crack : 0}); slateDoorSign(fb, 0); }
  else if (door >= 2) slateDoorSign(fb, 4 - door);
});
S5('S5.12', 'C', 'v3 29.17\'s [MCU] (MAS left third, not turning, lip-synced; the dark room soft; RACK Mas -> the door after the line) with the slate door ajar on the desks (ROOM-SLATE-DESKS drawSlateDoorOpen open, slateDoorSign), drawn into the held plate before the softening so the rack steps it', (fb, k, sh) => {
  const st = rackStep(k, mk(sh, 'rack', 41));
  const [kA, kB] = RACK[st];
  const doorMask = new Uint8Array(480 * 270);
  keepRect(doorMask, DPLATE.door.x0 - 2, DPLATE.door.y0 - 2, DPLATE.door.x1 - DPLATE.door.x0 + 4, DPLATE.deskY - DPLATE.door.y0 + 4);
  held(fb, `s5:s512:${kB}`, (b) => {
    const plate: DarkPlateOpts = {tally: 3, glass: true, lanyard: true, phone: 'up', door: 4};
    drawDarkPlate(b, 0, plate); drawSlateDoorOpen(b, 0, {gap: SLATE_GAP.open}); slateDoorSign(b, 0);
    drawDarkPlateDesk(b, 0, plate); drawDarkPlateFront(b, 0, plate);
    soft(b, 2, doorMask); softMask(b, kB, doorMask); vignette(b, MCU_X.L + 56, 2);
  });
  drawBust(fb, mas({mouth: mouth5(sh, k, 'MAS'), look: -1}), {third: 'L', faceK: kA});
});

// ================================================================== S6 · THE AVALANCHE (all reused, on v4's sequence clock)
R5('S6.01', 'S6.01');
R5('S6.02', 'S6.02');
R5('S6.03', 'S6.03');
R5('S6.04', 'S6.04');
R5('S6.06', 'S6.06');

// ================================================================== S7 · THE RETURN
/** the GUEST lanyard lying on his desk inside his window (v4's lanyardOnDesk) */
const lanyardOnDesk = (b: Buf, x: number, y: number) => {
  for (let i = 0; i < 44; i++) b.set(x - 18 + i, y + 6 + Math.round(Math.sin(i / 7) * 2), PAL.C5);
  rect(x + 24, y, 30, 16, b.ink(PAL.N0)); rect(x + 25, y + 1, 28, 14, b.ink(PAL.P2)); rect(x + 25, y + 1, 28, 3, b.ink(PAL.R2));
  pt(b, 'GUEST', x + 27, y + 6, PAL.N2);
};
S5('S7.01', 'C', '[P2] BOX (the act\'s one deliberate box): CAST-ALYI-PHONE alyi-v5 drawAlyiDoorPhone (twoshots drawDoorwayP2: Alyi reading his post on his phone, then looking up at the three hearts; both men lip-synced; the IOU) + UI-POST \'popup\' (his regret, the lock\'s words) + the GUEST lanyard and PROP-MACROSOFT-BADGE \'p2\' lying on Mas\'s desk', (fb, k, sh) => {
  const h1 = mk(sh, 'heart1', 165), h2 = mk(sh, 'heart2', 177), h3 = mk(sh, 'heart3', 189), up = mk(sh, 'up', 193), iou = mk(sh, 'iou', 408), post = mk(sh, 'post', 24), postEnd = mk(sh, 'postEnd', 163);
  const open = Math.min(1, (k + 1) / 3);
  drawAlyiDoorPhone(fb, k, {phone: k < up, alyi: {mouth: mouth5(sh, k, 'ALYI'), up: k >= up}, mas: {mouth: mouth5(sh, k, 'MAS'), lid: blink(k, 7)}, hearts: [h1, h2, h3],
    iou: (k < iou ? 0 : Math.floor(k / 4) % 2 ? 1 : 2) as 0 | 1 | 2, openL: open, openR: open});
  if (k >= 3) { rect(14, 140, 108, 20, fb.ink(PAL.D2)); rect(14, 140, 108, 1, fb.ink(PAL.D4)); lanyardOnDesk(fb, 40, 142); macrosoftBadge(fb, 22, 143, 'p2', {strap: false}); }
  if (k >= post && k < postEnd) drawPost(fb, 140, 24, postSpec(sh, 'a5-30-P1'), {size: 'popup', w: 200, k: k - post});
});
S5('S7.02', 'C', 'v4 S7.02 (rooms-b bullpen walkout wide, held: coats, packed boxes, Mas small at his end desk, Tasya mid-floor) + PROP-MACROSOFT-BADGE badgesOnDeskRoom on his desk + his room-scale mouth for the question', (fb, k, sh) => {
  const m = roomMouth5(sh, k, 'MAS');
  held(fb, `s5:s702-${m}`, (b) => {
    const A = bullpenRoom(b, 0, {variant: 'walkout'}, {mas: {mouth: m}, tasya: {arm: 'clasp'}, landlord: {floor: 0, ceiling: 0, walls: 0}});
    badgesOnDeskRoom(b, A.masDesk[0] + BADGES_ROOM_AT[0], A.masDesk[1] + BADGES_ROOM_AT[1]);
  });
});
R5('S7.02b', 'S7.02b', 'lip-synced on the v5 take; the slate steps on below / above / around');
R5('S7.03', 'S7.03');
R5('S7.05', 'S7.05');
const FIRE_PLATES = {A: null, B: 'ALYI', C: null, D: 'NELEH', E: 'THE QUIET VOTE'} as const;
S5('S7.06', 'C', 'v4 S7.06 as it was (the boardroom wide with the fires, ONE held setup with S7.06-cont merged: the door bangs, TERB in, the helmet -> the FULL FREEZE with the TERB card, Mas walking through in colour and pocketing the pin -> unfreeze, the look-around) + TERB\'s room-scale mouth on "Which room is on fire?" and "…Ah."', (fb, k, sh, f) => {
  const bang = mk(sh, 'bang', 0), helmet = mk(sh, 'helmet', 3), fz = mk(sh, 'freeze', 6), un = mk(sh, 'unfreeze', 65), look = mk(sh, 'look', 121);
  if (k < fz) {
    const open = k >= bang;
    boardRoom(fb, k, {fires: FIRES_SC30, door: open ? 'open' : 'closed', doorFlash: k === bang ? 1 : 0, rolodex: 'still', plates: {...FIRE_PLATES}},
      {mada: true, terb: open ? {x: 394 - Math.floor(on2(k - bang) * 1.5), pose: {legs: terbWalkAt(k), helmet: k >= helmet, arm: 'carry'}} : null, shake: doorShake(k, bang)});
    return;
  }
  const tx = 394 - Math.floor(on2(fz - bang) * 1.5);
  if (k < un) {
    const kk = k - fz;
    held(fb, `s5:s706-freeze-${tx}`, (b) => { boardRoom(b, 0, {fires: FIRES_SC30, door: 'open', rolodex: 'still', plates: {...FIRE_PLATES}}, {mada: true, terb: {x: tx, pose: {legs: 'stand', helmet: true, arm: 'carry', pin: true}}}); freezePrint(b); });
    const pin = mk(sh, 'pin', 45) - fz;
    const x = Math.min(tx - 38, 150 + on2(Math.max(0, kk - 4)) * 4);
    drawMasStand(fb, x, 196, {...MAS_STAND_DEFAULT, legs: x < tx - 38 ? masWalkAt(kk) : 'stand', arm: kk < pin - 6 ? 'down' : kk < pin + 4 ? 'reach' : 'pocket', light: 'room'});
    blipCard(fb, kk, 'TERB', 'TERB', 'THE NEW CHAIR', 'EXTINGUISHERS: 1', {f, x: {helmet: true}}, 'L');
    return;
  }
  const around = k >= look && k < look + 18 ? 1 + (Math.floor((k - look) / 5) % 2) : 0;
  const m = roomMouth5(sh, k, 'TERB');
  held(fb, `s5:s706-after-${tx}-${around}-${m}`, (b) => boardRoom(b, 0, {fires: FIRES_SC30, door: 'open', rolodex: 'still', plates: {...FIRE_PLATES}},
    {mada: true, terb: {x: tx + (around === 1 ? 2 : 0), pose: {legs: 'stand', helmet: true, arm: 'carry', pin: false, mouth: m}}, mas: {x: tx - 38, pose: {legs: 'stand', arm: 'pocket', light: 'room'}}}));
}, true);
S5('S7.07', 'C', 'CAST-TERB-SHEET calmoff-terms drawCalmOffTerms2S (the calm-off: MAS left, MADA right, TERB in depth between them reading the single sheet, room-scale mouth; between sentences he sprays the chair fire, the sheet under his arm); Mada\'s spinner turning', (fb, k, sh, f) => {
  const sp = mk(sh, 'spray', 120), spE = mk(sh, 'sprayEnd', 130);
  const spraying = k >= sp && k < spE;
  drawCalmOffTerms2S(fb, f, {terb: {pose: {mouth: spraying ? 'rest' : roomMouth5(sh, k, 'TERB'), read: !spraying, blink: blink(k, 11) > 0}, spray: spraying ? k - sp : null}, spin: f});
});
S5('S7.07b', 'N', 'CAST-OTHER-YRRAL calmoff-terms drawOtherYrralM: the seated silhouette at the table\'s far end among the fires, the nameplate YRRAL (NOT THAT YRRAL), one two-drawing nod on "other"', (fb, k, sh, f) => {
  const nod = mk(sh, 'nod', 12);
  drawOtherYrralM(fb, f, {nod: k >= nod && k < nod + 6 ? 1 : 0});
});
S5('S7.07-cont', 'C', 'the S7.07 setup again (drawCalmOffTerms2S): Terb reading on, then looking up to Mada ("He stays."); MAS lip-synced ("of what?"); MADA lip-synced on "Good question." (his face is in the 2S, as v4 drew it), his spinner turning', (fb, k, sh, f) => {
  const lk = mk(sh, 'look', 60);
  drawCalmOffTerms2S(fb, f, {terb: {pose: {mouth: roomMouth5(sh, k, 'TERB'), read: k < lk, blink: blink(k, 11) > 0}}, mas: {mouth: mouth5(sh, k, 'MAS'), lid: blink(k, 7)}, mada: {mouth: mouth5(sh, k, 'MADA')}, spin: f});
});
R5('S7.08', 'S7.08');
S5('S7.09', 'C', 'the calm-off, the long hold (drawCalmOffTerms2S): the spinner stops, Mada nods, Terb stamps and hands the sheet over (the term sheet on the table, stamped); PROP-PHONE-TABLE Mas\'s phone lights green on the table, keycaps; UI-POST \'notify\' (Gerg\'s return, the lock\'s words) (merges v4\'s S7.11)', (fb, k, sh, f) => {
  const stop = mk(sh, 'stop', 38), nd = mk(sh, 'nod', 43), stp = mk(sh, 'stamp', 52), hand = mk(sh, 'hand', 68), ph = mk(sh, 'phone', 67), post = mk(sh, 'post', 67);
  const n = k - nd;
  const nod = (n < 0 ? 0 : n < 2 ? 1 : n < 4 ? 2 : n < 6 ? 1 : 0) as 0 | 1 | 2;
  const arm = k < stp - 6 ? 'sheet' : k < hand ? 'stamp' : k < hand + 24 ? 'hand' : 'none';
  const f0 = f - k;
  drawCalmOffTerms2S(fb, f, {terb: {pose: {arm, read: false}}, mada: {nod}, spin: f0 + Math.min(k, stop), stopped: k >= stop, phone: k >= ph ? k - ph : null,
    plate: {fires: FIRES_CALMOFF(-40), termSheet: k < stp - 6 ? 'none' : k < stp ? 'blank' : 'stamped'}} as Parameters<typeof drawCalmOffTerms2S>[2]);
  if (k >= post) drawPost(fb, 150, 12, postSpec(sh, 'a5-30-P2'), {size: 'notify', w: 184, glow: true, k: k - post});
});
S5('S7.13', 'C', '[HIGH] v4 S7.13\'s table from above (rooms/boardroom drawTableInsert \'prop\') + PROP-HOURGLASS-INSERT hourglass-insert drawHourglassXL (view \'high\'): the last grain, the shatter, the sand holding its shape, then falling; UI-POST \'popup\' (Ttemme\'s result, the lock\'s words); UI-CHAT-ROOM \'corner\' entering', (fb, k, sh, f) => {
  const g = mk(sh, 'grain', 7), post = mk(sh, 'post', 21), postEnd = mk(sh, 'postEnd', 127), sht = mk(sh, 'shatter', 173);
  // v4 S7.13's own table plate from above (rooms/boardroom drawTableInsert 'prop'), the hourglass standing on its prop spot
  // (art-built-v5 §5a, host item 2: a flat wood field read as a wall)
  drawTableInsert(fb, {f: k, focus: 'prop'});
  const [px, py] = TABLE_INSERT.prop;
  drawHourglassXL(fb, px - HGX_HIGH.foot[0], py + 3 - HGX_HIGH.foot[1], {view: 'high', moved: k < g ? HGX_GRAINS - 1 : HGX_GRAINS, running: k < g, f: k, shatter: k >= sht ? k - sht : undefined});
  drawChatPanel(fb, 470, 160, 'corner', f);
  if (k >= post && k < postEnd) drawPost(fb, 20, 20, postSpec(sh, 'a5-30-P3'), {size: 'popup', w: 200, k: k - post});
});

// ================================================================== S8 · THE LOBBY, AND AFTER
S5('S8.01', 'C', 'v3 30.19 (rooms-a lobby at night cropped on the sign, the sign igniting 1,2,1,2,3 on the stab; Mas small at the desk, no badge) with the box of spare 0 plates in the room (lobby zeroBox: v4\'s S8.02 merged in; no hand); the crop is still the stand-in for a true low angle (ROOM-LOBBY-LOW, P4)', (fb, k, sh) => {
  const ig = mk(sh, 'ignite', 2);
  const IG = [1, 2, 1, 2, 3] as const;
  const sign = (k < ig ? 0 : IG[Math.min(4, Math.floor((k - ig) / 3))]) as 0 | 1 | 2 | 3;
  held(fb, `s5:s801-${sign}`, (b) => {
    const room = new Buf(480, 270, PAL.N0);
    lobbyRoom(room, 0, {sign, zeroBox: true}, {});
    const dx = 240 - Math.round((LOBBY.SIGN.x0 + LOBBY.SIGN.x1) / 2), dy = 24;
    for (let y = 0; y < RH; y++) for (let x = 0; x < 480; x++) b.set(x, y, room.get(clamp(x - dx, 0, 479), clamp(y - dy, 0, RH - 1)));
  });
}, true);
R5('S8.03', 'S8.03');
R5('S8.04', 'S8.04');
R5('S8.05', 'S8.05');
R5('S8.06', 'S8.06');
S5('S8.07', 'C', 'CAST-MAS-TURNAWAY mas-turnaway: the frameless 50/50 over the bullpen by day soft 1 (v4\'s recipe): MAS turned away, already past (no mouth), GERG right lip-synced (gergGlow) with his hand on the Q* vault (drawVaultMid, its note DO NOT OPEN. DO NOT EXPLAIN.); RACK to the vault after his line (the note sharp), Mas walking off, then Gerg walks out', (fb, k, sh) => {
  const rk = mk(sh, 'rack', 119), wk = mk(sh, 'walk', 139);
  const st = rackStep(k, rk);
  const [kA, kB] = RACK[st];
  const racked = k >= rk + 6;
  const VX = 198, VY = 92;
  held(fb, `s5:s807:${racked ? 1 : 0}`, (b) => {
    drawBullpen(b, 0, {door: 'shut'});
    const keep = new Uint8Array(480 * 270); keepRect(keep, 196, 88, 100, 104);
    soft(b, 1, keep); vignette(b, 158, 1); vignette(b, 330, 1);
    drawVaultMid(b, VX, VY, {soft: racked ? 0 : 1, noteSharp: racked});
  });
  const mdx = k < rk ? 0 : -Math.floor((k - rk) / 4) * 4, mstep = (k >= rk ? (k >> 2) % 2 : 0) as 0 | 1;
  if (mdx > -140) drawBust(fb, masTurnedAway({light: 'warm', step: mstep}), {third: 'L', dx: -8 + mdx, y: 24, faceK: kA});
  drawOrb(fb, 186 + Math.max(-60, mdx), 44, 9, {look: [0.9, 0.5], aperture: 0.5} as Parameters<typeof drawOrb>[4]);
  const gx = k < wk ? 0 : Math.floor((k - wk) / 2) * 6;
  if (gx < 200) drawBust(fb, gergGlow({mouth: mouth5(sh, k, 'GERG'), lid: k >= rk + 12 ? 0 : 1, look: -1}), {third: 'R', dx: 14 + gx, y: 26, faceK: kA});
  if (k < wk) gergHandOnVault(fb, VX + VAULT_MID.hand.x, VY + VAULT_MID.hand.y, kA > 0 ? 1 : 0);
});
S5('S8.08', 'N', 'ROOM-BULLPEN-UNPACK bullpen-unpack drawBullpenUnpack (Nov 29: coats off, boxes open, the staff turned toward his end desk), Mas reading his memo at room scale (open / rest), the slow whole-px drift (8 px over the shot)', (fb, k, sh, f) => {
  drawBullpenUnpack(fb, f, {mas: {mouth: roomMouth5(sh, k, 'MAS')}, drift: Math.min(8, Math.floor((k * 9) / Math.max(1, len5(sh))))});
});
R5('S8.09', 'S8.09', 'the memo carries over it');
S5('S8.09b', 'N', 'kits/inserts-props drawShutDoorInsert (existing art): the conference-room door, shut, its ALYI nameplate still on', (fb) => { drawShutDoorInsert(fb, {name: 'ALYI'}); });
R5('S8.10', 'S8.10');

// ================================================================== checks and the ledger
export const missingShots5 = (ids: string[] = SHOTS.map((s) => s.id)) => ids.filter((id) => !DRAW5[id]);
/** what every shot is built from (the shot list and the report print it) */
export const ledger5 = () => SHOTS.map((s) => ({id: s.id, verdict: s.verdict, kind: DRAW5[s.id]?.kind ?? null, st: DRAW5[s.id]?.st ?? 'STICK FALLBACK (no layout)', standin: DRAW5[s.id]?.standin ?? true}));
/** the in-world texts the new art hard-codes, against the lock (the facts owner re-checks a mismatch) */
export const textChecks5 = () => {
  const out: string[] = [];
  const norm = (s: string) => s.replace(/[“”"…]/g, '').replace(/\s+/g, ' ').trim().toLowerCase();
  for (const [id, key] of Object.entries(POST_KEY)) {
    const sh = SHOTS.find((s) => s.lines.some((l) => l.id === id));
    const l = sh?.lines.find((x) => x.id === id);
    if (l && norm(l.text) !== norm(POSTS[key].text)) out.push(`post ${id}: lock "${l.text}" vs POSTS.${key} "${POSTS[key].text}" (the picture draws the lock's words)`);
  }
  const s303 = SHOTS.find((s) => s.id === 'S3.03');
  const blog = (BLOG as unknown as {lines?: string[]}).lines ?? [];
  for (const t of s303?.texts ?? []) if (t.text.length > 30 && !blog.some((b) => norm(b).includes(norm(t.text).slice(0, 30)))) out.push(`blog S3.03: lock text "${t.text}" not found in BLOG.lines`);
  return out;
};
void inPalette; void BLUEPRINT_PRINT; void fallaway; void monitor; void lineOf5; void drawBoardPlate;
