"""report_v3.py - writes show/episodes/ep01/production/act4/timing-v3.md (THE EDITOR's timing lock v3, readable) from
shots-locked-v3.json (lock_v3.py), out/ep01/act4/animatic/act4-mix-v3.cues.json (mix_v3.py) and layout-v3.json (the
renderer's ledger). Run after lock_v3.py -> mix_v3.py -> render (ledger).
Run:  python3 studio/src/episodes/ep01/act4/animatic/tools/report_v3.py
"""
import os  # noqa: E402  (phase 1: the project root is found at run time, docs/ORGANIZATION-PLAN.md §4)
import sys  # noqa: E402


def _repo():
    for start in (os.path.dirname(os.path.abspath(__file__)), os.getcwd()):
        d = start
        while True:
            if os.path.exists(os.path.join(d, '.mrmas-root')):
                return d
            if d == os.path.dirname(d):
                break
            d = os.path.dirname(d)
    sys.exit('MR. MAS: no .mrmas-root above this script or the cwd; set MRMAS_ROOT')


REPO = os.environ.get('MRMAS_ROOT') or _repo()
import json
import os
import statistics
from collections import OrderedDict, Counter

P = lambda *a: os.path.join(REPO, *a)  # noqa: E731
FPS, BEAT, BAR = 24, 15, 60
L = json.load(open(P("show/episodes/ep01/production/act4/shots-locked-v3.json")))
MX = json.load(open(P("out/ep01/act4/animatic/act4-mix-v3.cues.json")))
LED = {r["id"]: r for r in json.load(open(P("out/ep01/act4/animatic/layout-v3.json")))}
S = L["summary"]
M = MX["measurements"]
TOTAL = S["act_frames"]
shots = L["shots"]


def length(fr):
    s = fr / FPS
    return f"{int(s // 60)}:{s % 60:05.2f}"


def pct(n):
    return f"{100 * n / TOTAL:.1f}%"


voiced = sorted([l for r in shots for l in r["lines"] if l["kind"] != "post"], key=lambda l: l["abs_in"])
gaps = [(b["abs_in"] - a["abs_out"]) / FPS for a, b in zip(voiced, voiced[1:])]
chained = [(b["abs_in"] - a["abs_out"]) / FPS for a, b in zip(voiced, voiced[1:]) if b["chained_to"] == a["id"]]
near = [g for g in gaps if g < 2.0]

CLS = OrderedDict([("W", "Wide (incl. the lobby low angle)"), ("M", "Medium / two-shot"), ("OTS", "Over-the-shoulder (incl. OTS-W)"),
                   ("MCU", "Frameless close-up (incl. ·PF, doorway, desk-level, 50/50)"), ("CU", "Mas full-frame close-up"),
                   ("ECU", "Extreme close-up (hands, eyes, the Orb's iris, props, table overheads)"), ("SW", "Screen, wide"), ("SC", "Screen, close (pinned, two-up, half tile, macro, floor POV)"),
                   ("GS", "Blueprint sheet"), ("GM", "Blueprint section"), ("GD", "Blueprint detail"), ("GFX", "Full-screen card"), ("BOX", "Deliberate box")])
cls = Counter()
clsf = Counter()
for r in shots:
    cls[r["size_class"]] += 1
    clsf[r["size_class"]] += r["frames"]
close = clsf["MCU"] + clsf["CU"]
mid = clsf["M"] + clsf["OTS"]
runs3 = S["runs_of_3"]
longest_run = 1
cur = 1
for a, b in zip(shots, shots[1:]):
    cur = cur + 1 if a["size_class"] == b["size_class"] else 1
    longest_run = max(longest_run, cur)

nm = M["longest_no_voice_no_music_no_sfx"][0]
ds = M["longest_digital_silence"][0]
lines = []
w = lines.append
w("# Ep1 · Act Four · Timing lock v3 (THE EDITOR)")
w("")
w("Board 3 (`shots-v3.json`, draft 3.2) re-sat on the 3.2 re-record (`lines.json`), cut with temp sound. Generated by "
  "`studio/src/episodes/ep01/act4/animatic/tools/lock_v3.py` → `mix_v3.py` → `render.ts` → `report_v3.py`; re-run them after any "
  "re-record, ruling or re-board, and don't hand-edit this file, `shots-locked-v3.json` or `data-v3.ts`.")
w("")
w("**Deliverables**")
w("")
w("- `out/ep01/act4/animatic/act4-animatic-v3.mp4`: composition `ep01-act4-animatic`, 1280 × 720, 24 fps, H.264 + AAC 48 kHz stereo (the v3 mix muxed).")
w("- `out/ep01/act4/animatic/act4-v3-contact.png`: one still per shot (its middle frame), size class and template under each.")
w("- `out/ep01/act4/animatic/act4-mix-v3.wav` (+ `act4-mix-v3.cues.json`, the sound EDL) and `act4-dialogue-premix-v3.wav`.")
w("- `show/episodes/ep01/production/act4/shots-locked-v3.json`: every shot and line on the act clock.")
w("")
w("## 1. The numbers")
w("")
w("| | v2 animatic | **v3 (this lock)** |")
w("|---|---|---|")
w(f"| Act runtime | 7:33.8 (453.8 s) | **{length(TOTAL)} ({TOTAL} f)**, episode {S['episode_in']}–{S['episode_out']} |")
w(f"| Against board 3 | — | {S['delta_vs_board']:+d} f ({S['delta_vs_board'] / FPS:+.2f} s): the takes, see §3 |")
w(f"| Dialogue coverage | 20% | **{S['dialogue_coverage_pct']}%** of the act by take span; {M['dialogue_audible_pct']}% by audible speech |")
w(f"| Median gap between lines inside an exchange | 1.14 s | **{statistics.median(chained):.3f} s** over {len(chained)} replies (max {max(chained):.3f} s, the scripted 1-beat gaps) |")
w(f"| Median gap between consecutive lines under 2 s | — | {statistics.median(near):.2f} s ({len(near)} gaps) |")
w(f"| Stretches > 6 s with no voice | 18 (≈ 304 s), all dead air | {M['stretches_over_6s_without_voice']} ({sum(x['frames'] for x in S['stretches_over_6s_without_voice']) / FPS:.1f} s): the set-pieces, every one scored or sounded |")
w(f"| Stretches > 6 s with no voice, no music and no SFX | 18 | **{M['stretches_over_6s_without_voice_music_sfx']}** |")
w(f"| Longest stretch with no voice, no music and no SFX | 42 s | **{nm['seconds']} s** ({nm['tc']}, {nm['shot']}: the dry record card; room tone under it) |")
w(f"| Longest digital silence | whole set-pieces | **{ds['seconds']} s** ({ds['tc']}, {ds['shot']}–{ds['end_shot']}: D6, the drop-out, by design) |")
w(f"| Music audible | 0% | {M['music_audible_pct']}% of the act (dry by rule under the record, the quiet beat, the calm-off and the memo) |")
w(f"| Mix loudness | dialogue only | {M['integrated_lufs_mix']} LUFS integrated (dialogue alone {M['integrated_lufs_dialogue']}); dialogue over music: median {M['dialogue_over_music_db_median']} dB |")
w(f"| Close-ups ([MCU] + [CU]) | ≈ 1% | **{pct(close)}** of screen time ({cls['MCU'] + cls['CU']} shots) |")
w(f"| Boxed portraits | 42 shots, 29 of 45 lines | **{cls['BOX']}** (30.01, the deliberate doorway [P2]) |")
w(f"| Runs of 3+ shots of one size | 7 | {len(runs3)} (longest run {longest_run}) |")
w("")
w("### 1.1 Shot-size distribution (share of screen time)")
w("")
w("| Size class | Shots | Frames | Share |")
w("|---|---|---|---|")
for c, name in CLS.items():
    if cls[c]:
        w(f"| {name} (`{c}`) | {cls[c]} | {clsf[c]} | {pct(clsf[c])} |")
w(f"| **Total** | **{len(shots)}** | **{TOTAL}** | 100% |")
w("")
w(f"Close-ups [MCU] + [CU] {pct(close)} (bible §4.7.4 GREEN 20–30%) · [M] + [2S] + [OTS] {pct(mid)} (GREEN 12–20%) · wides {pct(clsf['W'])} (≤ 15%) · "
  f"the deliberate box {pct(clsf['BOX'])} (≤ 5%). The re-record moved the shares by a few tenths against board 3; the board's own reading "
  "(close-ups just under the green line because THE PLAN, the record and the screens are about 40% of the act by design) stands.")
w("")
w("## 2. The lock rules")
w("")
w("1. **Every line takes its length from its take** (`frames_24`). Nothing is lengthened for a window, a box or typing.")
w("2. **A reply is chained to the line it answers:** it starts where that line ends, minus the cue sheet's overlap (`overlap_prev_frames`), "
  "plus the dialogue editor's marked gap (`gap_prev_s`: the scripted pauses, all ≤ 1 s: \"good question.\" exactly 1 beat late, TASYA 1 beat "
  "after the D8 line), or plus the default 3–7 f (0.125–0.29 s). A line is chained when `lines.json` names the relation or the board put it "
  "≤ 8 f after the previous line.")
w("3. **Conversation cuts land on the turn:** a cut-on-the-turn shot starts at its first line minus the board's lead; a negative lead is "
  "the board's L-cut pre-lap, kept frame-accurate.")
w("4. **A line-carrying shot inside a conversation block keeps the board's tail** after its last line (the listener's hold, a read floor, "
  "a rack), so its length follows the take.")
w("5. **Everything else keeps the board's length:** set-pieces, inserts, cards, posts and holds are cut to their music and staged action. "
  "A take that overruns its shot grows it by exactly the overrun, never to the grid. A line may L-cut ≤ 8 f into a shot that continues the read.")
w("6. **V.O.** ends ≥ 1 beat before its cut and the next spoken line (pov-and-framing §5.1).")
w("7. **No padding.** No conversation block is closed back onto the beat grid; each set-piece's music is cut from its own first frame (§6).")
w("")
w("## 3. What moved against board 3")
w("")
w("| Sc | Board | Lock | Δ |")
w("|---|---|---|---|")
for s in L["scenes"]:
    w(f"| {s['scene']} | {s['board_frames']} f | {s['frames']} f ({s['length']}) | {s['frames'] - s['board_frames']:+d} f |")
w("")
w("- **Conversation blocks** re-sat on the takes (most read 0.1–0.2 s longer than the 3.2 targets): every cut still lands on its turn, the gaps inside exchanges are 3–7 f.")
w("- **29.16 (+3 f) and the Gerg block:** \"gerg never waits to be asked.\" delivered at 62 f against a 48 f target (the V.O. pace ruling, see §8), so TASYA's \"Everyone is welcome.\", 1 beat after it, lands 14 f later than the board placed it; "
  "the door's three held steps follow the word frame of \"asked\" (f44). \"One sec. Compiling—\" / \"what are you building?\" overlap by the dialogue editor's 4 f (the board had 10 f), which lengthens 29.11a to 30 f.")
w("- **31.02 (+9 f):** GERG's \"What's in there?\" is 21 f against 17 and the answer sits 4 f after it (the board had 1 f); the rack to the vault and Gerg's exit follow the answer.")
for d in L["decisions"]:
    w(f"- **{d.split(':')[0]}:**{d.split(':', 1)[1]}")
w("- **25.02b:** \"This board controls the company.\" (44 f against 41) L-cuts 1 f into 25.02c instead of growing the shot, so THE PLAN stays 7 bars on its waltz; \"The investor gets—\" starts 4 f after it and the `VOTES: 0` stamp lands on the recorded \"t\" of \"gets\".")
w("- **27.22a (−10 f):** MARIO's \"thoughts—\" is 1.25 s against 1.60 s (the dialogue report's one span miss); the shot is cut to the take, not padded.")
w("")
w("## 4. The lines")
w("")
w("| Line | Shot | TC | In (act f) | Frames | Gap to previous | Placed by |")
w("|---|---|---|---|---|---|---|")
prev = None
for l in voiced:
    r = next(x for x in shots if any(y["id"] == l["id"] for y in x["lines"]))
    gp = "" if prev is None else f"{(l['abs_in'] - prev['abs_out']) / FPS:+.2f} s"
    w(f"| `{l['id']}` {l['speaker']} ({l['kind']}) | {r['id']} | {l['tc_in']} | {l['abs_in']} | {l['frames']} | {gp} | {l['placed_by']} |")
    prev = l
w("")
w(f"Posts (unvoiced pop-ups, house rule): {', '.join(p['id'] + ' (' + p['shot'] + ', ' + str(p['frames']) + ' f)' for p in L['posts'])}.")
w("")
w("## 5. The shots")
w("")
w("| Shot | Tag | Class | Template · move | In | Frames | Board | Length rule | Built from (animatic v3) |")
w("|---|---|---|---|---|---|---|---|---|")
for r in shots:
    led = LED.get(r["id"], {})
    st = led.get("st", "")
    mark = " **(stand-in / box)**" if led.get("standin") else ""
    w(f"| {r['id']} | {r['tag']} | {r['size_class']} | {r['framing']} · {r['move_type']} | {r['tc_in']} | {r['frames']} | {r['board_frames']} | {r['length_rule']} | {st}{mark} |")
w("")
w("## 6. Temp sound (so the set-pieces don't play as silence)")
w("")
w("Everything below is **TEMP**, for the animatic; the music owners' and the SFX editor's finals replace it. The EDL is `act4-mix-v3.cues.json`; "
  "the margin of every animatic frame prints the cue and the SFX under it.")
w("")
w("- **Dialogue:** every voiced cue as delivered (−16 LUFS lines; V.O. +2 dB to dialogue level; the laptop \"super.\" at −22).")
w("- **Music:** the finished OST to-picture cues (their underscore mixes), cut to the v3 picture in whole bars or beats of their own 96 BPM grid, "
  "each set-piece from its own cut; hard stops are the cues' own. **Ducks 3 dB under dialogue** (OST §6.6 rule 7), 60 ms / 300 ms; −9 dB under the laptop \"super.\".")
w("- **Dry by rule:** no music under a real [V] line, a card (1 bar each side of the candor card), the posts the script calls dry, the quiet beat, "
  "the D8 line, \"Everyone is welcome.\", the calm-off or the memo. Room tone plays under them.")
w("- **D6:** from the Cancel click every bus is muted for 5 beats; only the click's transient is heard.")
w("")
w("| In | Out | Cue | Source (s) | What |")
w("|---|---|---|---|---|")
for m in MX["music"]:
    w(f"| {m['tc_in']} | {m['tc_out']} | {m['cue_title']} | {m['src']:.3f} | {m['label']} |")
w("")
w("**Dry windows:** " + " · ".join(f"{d['tc_in']} {d['why']}" for d in MX["dry"]) + ".")
w("")
syn = sorted(set(x["name"].split(":")[1] for x in MX["sfx"] if x["synth"]))
w(f"**SFX:** {len(MX['sfx'])} events from the board (`audio/sfx/manifest.json`) at their picture frames, at the board's mixDb unless noted. "
  f"The board's *(build)* sounds that don't exist yet are synthesised stand-ins, logged `TEMP-SYNTH` in the EDL: {', '.join(syn)} "
  "(the crane truck, the glass tings, the phone buzz and clack, the key ring, the throne thunk, pencil and pen, the speakerphone tones, the rack slot's whir, the pin, the screws, the fires, the crowd).")
w("")
w("**Beds:** " + " · ".join(f"{b['label']} ({b['name']}, {b['gain_db']} dB)" for b in MX["beds"]) + ".")
w("")
w("**Where the act has no voice, no music and no SFX** (room tone only), longest first:")
w("")
for x in M["longest_no_voice_no_music_no_sfx"][:6]:
    w(f"- {x['seconds']} s at {x['tc']} ({x['shot']}{'–' + x['end_shot'] if x['end_shot'] != x['shot'] else ''})")
w("")
w("These are the dry record items (the letter card, his 9:32 post, Ttemme's post under the hourglass, the lobby camera, the candor card) and D6. "
  "They are dry by the OST bible's rule, not by omission; each carries room tone and its own small sound (a card thud, a phone buzz, the last grain).")
w("")
w("## 7. The animatic v3")
w("")
w("`studio/src/episodes/ep01/act4/animatic/`: `frame.ts` (the composer), `shots3.ts` (one layout per locked shot), `framing.ts` (the v3 templates), "
  "`plan25v3.ts` (THE PLAN at 7 bars), `data-v3.ts` / `sound-v3.ts` (generated). v2's layouts (`shots.ts`) are reused through an adapter where a shot carries over, "
  "re-timed to this lock and fed the v3 takes' mouth cues.")
w("")
w("- **The picture** is the 480 × 270 show frame at 2× (960 × 540); the editor's notes (shot, size class, template and move, side, clock, beats, "
  "the lock's delta, what the layout is built from, the temp sound under the frame) sit in the right margin, the subtitles and the act timeline below. Nothing is written into the picture that the show wouldn't show.")
w("- **Templates, all on existing art:** [MCU] = the approved portrait composed straight into the frame, the torso extended to the frame edge in hard shadow bands, "
  "over its room stepped down 2 rungs with negative fill (Mas left third, others right third, eyes on the upper third); [MCU·door] adds the jamb and leaf as flat shapes; "
  "[MCU-2] is two frameless busts with the vault between; [OTS] = the listener's portrait as a silhouette with a 1 px rim over the medium rig, the call on the laptop, the monitor or the lobby; "
  "[ECU·Orb] = the procedural Orb at r 84; [ECU] = the built hand and prop inserts; [HIGH] = the table insert and its props; the two screen macros are integer 2× crops of the screen's own pixels; "
  "the two whips are 2 frames out + 2 in (row runs + highlight smear); the four racks step in 3 held steps of 2 f; the one drift is 1 px / 8 f; THE PLAN's pan is whole pixels on 2 f.")
w("- **The typed dialogue box** stays only where v3 keeps it: a wide, a voice off picture and the voice through a speaker (§4.7.3 rule 4). Close coverage carries the line on the voice and the subtitle.")
w(f"- **Stand-ins and boxes ({sum(1 for r in LED.values() if r['standin'])} shots, pink in the margin and the contact sheet):** THE PLAN's detail sizes (2× crops, MARKED), NELEH's pen hand (Mas's hand kit, MARKED), "
  "the phones overhead and the floor POV (flat shapes), the post-ui pop-ups, the cards, the lighthouse desk plate, the insert-scale hourglass (2×, MARKED), the lobby 'low angle' (a crop), "
  "the observer chair, the Q* vault at room scale, and the fingers / maintenance / worker hands (labelled boxes). No face is a box except 30.01.")
w("")
w("## 8. Open items")
w("")
w("- **Nobody has listened yet.** The takes, the ducking and the temp score were all placed by measurement; an ear pass on the mp4 comes first.")
w("- **V.O. pace (the POV owner's ruling 7):** the lock uses the wpm-paced V.O. takes. The ×1.08 takes in `audio/ep01/act4/dialogue/takes/<id>-x108/` "
  "drop in without moving a cut except 29.16 (\"gerg never waits to be asked.\" sets TASYA's line 1 beat after it) and 29.04 (\"the badge was a joke.\" already needed +1 f for its 1-beat clearance).")
w("- **Temp synths** (§6) are placeholders for the SFX board's *(build)* list; the vault's hum is `server_hum` standing in for MM-12.")
w("- **Scripted silences to confirm by ear:** D6 (3.1 s of digital silence) and F1.2 (silent by C39; the dark room's drone now pre-laps its last 2 beats).")
w("")
open(P("show/episodes/ep01/production/act4/timing-v3.md"), "w").write("\n".join(lines))
print("wrote timing-v3.md", len(lines), "lines")
