"""shotlist_v4.py - writes show/episodes/ep01/production/act4/shotlist-v4.md from the lock (shots-locked-v4.json) and the
board (shots-v4.json): one table per sequence, every shot with its locked length and timecode, what it does, its
lines as placed, its must-read text with the read floor, its story marks, and what the animatic draws it from.
Generated: re-run after lock_v4.py. Run:  python3 studio/src/episodes/ep01/act4/animatic/tools/shotlist_v4.py
"""
import os  # noqa: E402  (phase 1: the project root is found at run time, docs/ORGANIZATION-PLAN.md §4)
import sys  # noqa: E402


def _repo():
    for start in (os.path.dirname(os.path.abspath(__file__)), os.getcwd()):
        d = start
        while True:
            if os.path.exists(os.path.join(d, '.mrmas-root')):
                return d
            if d == os.path.dirname(d):
                break
            d = os.path.dirname(d)
    sys.exit('MR. MAS: no .mrmas-root above this script or the cwd; set MRMAS_ROOT')


REPO = os.environ.get('MRMAS_ROOT') or _repo()
import json
import os

PROD = os.path.join(REPO, "show/episodes/ep01/production/act4")
L = json.load(open(os.path.join(PROD, "shots-locked-v4.json")))
LED = {r["id"]: r for r in json.load(open(os.path.join(REPO, "out/ep01/act4/animatic/layout-v4.json")))}
FPS = 24


def s(fr):
    return f"{fr / FPS:.2f}"


def esc(t):
    return str(t).replace("|", "\\|").replace("\n", " ")


out = []
S = L["summary"]
out.append("# Ep1 · Act Four · Shot list v4 (lock v4.2)\n")
out.append("| | |\n|---|---|")
out.append(f"| **What** | Every v4 shot as the lock places it: {len(L['shots'])} shots in {len(L['sequences'])} sequences (lock v4.2, the closing pass: v4.0's IDs kept; v4.1 cut S4.05, S5.07, S6.05, S7.04 and S7.12 and added S5.09b and S7.02b; v4.2 cut S3.08 and S5.10). Generated by `tools/shotlist_v4.py` from [shots-locked-v4.json](shots-locked-v4.json) and [shots-v4.json](shots-v4.json); the plan is [edit-plan-v4](edit-plan-v4.md) §3, §10 and §11, the timing notes are [timing-v4](timing-v4.md). |")
out.append(f"| **Runtime** | {S['act_length']} ({S['act_frames']} f at 24 fps), episode {S['episode_in']} → {S['episode_out']}. {S['shots']} shots: mean {S['mean_s']:.2f} s, median {S['median_s']:.2f} s. |")
out.append("| **Honesty** | Built and checked from stills and numbers only. Nothing here has been watched in real time or listened to: how it flows and sounds needs a human (edit-plan-v4 §8, §10.6 and §11). |")
out.append("| **Reading the tables** | *Len* is the locked length (the plan's in brackets when they differ). *Lines* are `id @ in–out` in shot seconds; a negative in-point is an L-cut (the line starts under the previous shot). *Text* lists the must-read items with their read floor (0.25 s + 0.05 s a character). *Built from* is the layout in `shots4.ts`; **stand-in** marks a shot that still holds a drawn stand-in (never a label). |\n")
for q in L["sequences"]:
    ss = [r for r in L["shots"] if r["seq"] == q["id"]]
    out.append(f"## {q['id']} · {q['title']}\n")
    out.append(f"*{q['chapter']} · {q['place']} · {q['tc_in']}–{q['tc_out']} · **{q['seconds']:.2f} s** in {q['shots']} shots (plan {q['plan_s']} s; v3 {q['v3']})*\n")
    out.append(f"- **Question:** {q['question']}  **Turn:** {q['turn']}")
    out.append(f"- **Cue (planned; the sound pass mixes it):** {q['cue']}")
    out.append(f"- **Room:** {q['bed']}\n")
    out.append("| # | TC in | Len | Size · move | What it does | Lines | Text (floor) | Marks | Built from |")
    out.append("|---|---|---|---|---|---|---|---|---|")
    for r in ss:
        ln = f"{r['dur_s']:.2f}" + (f" ({r['plan_s']:.2f})" if abs(r['dur_s'] - r['plan_s']) > 0.02 else "")
        lines = "<br>".join(f"`{l['id']}` {l['speaker']}{' (post)' if l['kind'] == 'post' else ' (V.O.)' if l['kind'] == 'vo' else ' (O.S.)' if l['os'] else ''} @ {s(l['at'])}–{s(l['end'])}" for l in r["lines"]) or "—"
        texts = "<br>".join(f"{t['kind']}: `{esc(t['text'])}` ({s(t['floor_f'])})" for t in r["texts"] if t["must"]) or "—"
        marks = ", ".join(f"{k} {s(v)}" for k, v in sorted(r["marks"].items(), key=lambda kv: kv[1])) or "—"
        led = LED.get(r["id"], {})
        built = esc(led.get("st", r["build"]))[:220] + (" **stand-in**" if led.get("standin") else "")
        out.append(f"| **{r['id']}** | {r['tc_in']} | {ln} | {r['tag']} · {r['move']} | {esc(r['does'])} | {lines} | {texts} | {marks} | {built} |")
    out.append("")
out.append("## Rails (time and place only; they type, hold for the read + 0.75 s, and clear)\n")
out.append("| Shot | TC | Up | Floor | Rail |\n|---|---|---|---|---|")
for x in L["rails"]:
    tcx = next(r["tc_in"] for r in L["shots"] if r["id"] == x["shot"])
    out.append(f"| {x['shot']} | {tcx} | {s(x['e'] - x['s'])} s | {s(x['floor_f'])} s | `{esc(x['text'])}` |")
out.append("")
open(os.path.join(PROD, "shotlist-v4.md"), "w").write("\n".join(out) + "\n")
print("wrote", os.path.join(PROD, "shotlist-v4.md"), len(L["shots"]), "shots")
