"""shotlist_v5.py - writes show/episodes/ep01/production/act4/shotlist-v5.md from timing lock v5 (shots-locked-v5.json,
the approved stick timeline) and the v5 layout ledger (out/ep01/act4/animatic/layout-v5.json, written by
`tools/render5.ts ledger`): one table per sequence, every shot with its length and timecode, its verdict and how its
layout is built, what it does, its lines as placed (with who shows a mouth), its must-read text with the read floor, its
story marks and its sound spots (flagged where the temp mix lacks them).
Generated: re-run after lock_v5.py or a change to shots5.ts (ledger first). Run (repo root; stdlib only):
  node <scratch>/r5.cjs ledger out/ep01/act4/animatic/layout-v5.json      (from studio/, with the path made absolute)
  python3 studio/src/episodes/ep01/act4/animatic/tools/shotlist_v5.py
"""
import os  # noqa: E402  (phase 1: the project root is found at run time, docs/ORGANIZATION-PLAN.md §4)
import sys  # noqa: E402


def _repo():
    for start in (os.path.dirname(os.path.abspath(__file__)), os.getcwd()):
        d = start
        while True:
            if os.path.exists(os.path.join(d, '.mrmas-root')):
                return d
            if d == os.path.dirname(d):
                break
            d = os.path.dirname(d)
    sys.exit('MR. MAS: no .mrmas-root above this script or the cwd; set MRMAS_ROOT')


REPO = os.environ.get('MRMAS_ROOT') or _repo()
import json
import os
import re

PROD = os.path.join(REPO, "show/episodes/ep01/production/act4")
L = json.load(open(os.path.join(PROD, "shots-locked-v5.json")))
LEDGER = os.path.join(REPO, "out/ep01/act4/animatic/layout-v5.json")
LED = {r["id"]: r for r in json.load(open(LEDGER))} if os.path.exists(LEDGER) else {}
FPS = 24
# the six sound spots the approved timeline added after mix.wav was built (frame5.ts MIX_MISSING; render5 `check`)
F5 = open(os.path.join(REPO, "studio/src/episodes/ep01/act4/animatic/frame5.ts")).read()
MISSING = set(re.findall(r"'(S[\d.]+[a-z-]*(?:-cont|-back)? [^']+ @\d+)'", F5[F5.index("MIX_MISSING"):F5.index("]);", F5.index("MIX_MISSING"))]))
KIND = {"R": "R (v4 layout, re-timed)", "C": "C (v4 layout + v5 art)", "N": "N (new)"}


def s(fr):
    return f"{fr / FPS:.2f}"


def esc(t):
    return str(t).replace("|", "\\|").replace("\n", " ")


def floor_f(text):
    return round((0.25 + 0.05 * len(text)) * FPS)


S = L["summary"]
shots = sorted(L["shots"], key=lambda r: r["s"])
out = []
out.append("# Ep1 · Act Four · Shot list v5 (timing lock v5, the approved stick timing)\n")
out.append("| | |\n|---|---|")
out.append(f"| **What** | Every v5 shot as the lock places it: {len(shots)} shots in {len(L['sequences'])} sequences, cut shot for shot and line for line to the approved stick timeline (`show/reel/ep01-act4-v5.json`, 84 beats; S7.06-cont merges into S7.06). Generated by `tools/shotlist_v5.py` from [shots-locked-v5.json](shots-locked-v5.json) and the layout ledger (`out/ep01/act4/animatic/layout-v5.json`). The record of the lock and the layouts is [timing-v5](timing-v5.md); the render is [report-v5](report-v5.md). |")
out.append(f"| **Runtime** | {S['act_length']} ({S['act_frames']} f at 24 fps), episode {S['episode_in']} → {S['episode_out']}. {S['shots']} shots: mean {S['mean_s']:.2f} s, median {S['median_s']:.2f} s, shortest {S['min_s']:.2f} s, longest {S['max_s']:.2f} s. {S['lines']} voiced lines and {S['posts']} silent posts. |")
out.append("| **Honesty** | Built from the lock, the layouts' own ledger and stills. Nothing here has been watched in real time or listened to: how it flows and sounds needs a person. |")
out.append("| **Reading the tables** | *Len* is the locked length (= the stick's). *Verdict* is art-needs-v5's (R reuse, C change, N new) and, after the arrow, how the layout is actually built in `shots5.ts`. *Lines* are `id WHO @ in–out` in shot seconds; a negative in-point is a line carried over the cut; **lip** / **room** = this framing draws the speaker's mouth (a mouth track / room-scale open-rest), unmarked = no mouth in this framing (O.S., V.O., backs, POV). *Text* lists the must-read items with their read floor (0.25 s + 0.05 s a character) and how long they are up. *Sound* lists the stick's sound spots (shot seconds); **not in the temp mix** = the approved timeline added it after `mix.wav` was built. *Built from* is the layout's own note; **stand-in** marks a shot that still holds a drawn stand-in (never a label). |\n")
for q in L["sequences"]:
    ss = [r for r in shots if r["seq"] == q["id"]]
    out.append(f"## {q['id']} · {q['title']}\n")
    out.append(f"*{q['chapter']} · {q['place']} · {q['time']} · {q['tc_in']}–{q['tc_out']} · **{q['frames'] / FPS:.2f} s** in {len(ss)} shots*\n")
    out.append(f"- **Cue (the temp track is the stick mix):** {esc(q['cue'])}\n")
    out.append("| # | TC in | Len | Size · move | Verdict → built | What it does | Lines | Text (floor / up) | Marks | Sound | Built from |")
    out.append("|---|---|---|---|---|---|---|---|---|---|---|")
    for r in ss:
        led = LED.get(r["id"], {})
        lines = []
        for ln in r["lines"]:
            tag = " (post)" if ln["kind"] == "post" else " (V.O.)" if ln["kind"] == "vo" else " (O.S.)" if ln["os"] else ""
            face = f" **{ln['face']}**" if ln.get("face") else ""
            carry = " *(carried)*" if ln.get("carry") else ""
            lines.append(f"`{ln['id']}` {ln['who']}{tag}{face} @ {s(ln['s'])}–{s(ln['e'])}{carry}")
        texts = "<br>".join(f"{t['kind']}: `{esc(t['text'])}` ({s(floor_f(t['text']))} / {s(t['e'] - t['s'])})" for t in r["texts"] if t["must"]) or "—"
        marks = ", ".join(f"{k} {s(v)}" for k, v in sorted(r["marks"].items(), key=lambda kv: kv[1])) or "—"
        snd = []
        for x in r.get("sounds", []):
            m = re.match(r"^(.*) @(-?\d+)$", x.strip())
            if not m:
                continue
            key = f"{r['id']} {m.group(1)} @{m.group(2)}"
            snd.append(f"{m.group(1)} {s(int(m.group(2)))}" + (" **not in the temp mix**" if key in MISSING else ""))
        kind = led.get("kind")
        verdict = r["verdict"] + (f" → {kind}" if kind else "")
        built = esc(led.get("st", "(no ledger: run render5 ledger)"))[:260] + (" **stand-in**" if led.get("standin") else "")
        out.append(f"| **{r['id']}** | {r['tc_in']} | {s(r['frames'])} | {esc(r['frame'])} · {r['move']} | {verdict} | {esc(r['does'])} | {'<br>'.join(lines) or '—'} | {texts} | {marks} | {'<br>'.join(snd) or '—'} | {built} |")
    out.append("")
out.append("## Rails (time and place only; they type, hold for the read, and clear)\n")
out.append("| Shot | TC | Up | Floor | Rail |\n|---|---|---|---|---|")
for x in L["rails"]:
    tcx = next(r["tc_in"] for r in shots if r["id"] == x["shot"])
    out.append(f"| {x['shot']} | {tcx} | {s(x['e'] - x['s'])} s | {s(x['floor_f'])} s | `{esc(x['text'])}` |")
out.append("")
out.append("## Sound marks (the designed stops)\n")
out.append("| Kind | Name | Shot | Act frames |\n|---|---|---|---|")
for m in L["sound_marks"]:
    out.append(f"| {m['kind']} | {esc(m['name'])} | {m['shot']} | {m['s']}{'–' + str(m['e']) if m.get('e') is not None else ''} |")
out.append("")
dst = os.path.join(PROD, "shotlist-v5.md")
open(dst, "w").write("\n".join(out) + "\n")
print("wrote", dst, len(shots), "shots,", "ledger rows", len(LED), ", missing spots flagged", len(MISSING))
