#!/usr/bin/env python3
"""MR. MAS - Ep1 Act Four v5: the plain-text transcript of the v5 animatic (the a4p5-render pass).

Reads only data-v5.ts (the timing lock, generated by lock_v5.py) and writes, in time order:
  * every voiced line and silent post, with its start time, the speaker as the review transcript band names them
    (SUBS.shown: the lock names a speaker only from the frame the picture names them, e.g. NELEH is BLUEPRINT FIGURE
    until the S1.03 label; the same labels the band in frame5.ts draws: V.O., THROUGH THEIR LAPTOP, POST, O.S.);
  * every on-screen text of more than 3 words (the rails, the shots' in-world texts: labels, cards, toasts, plates,
    stamps, signs, UI), at the frame it first appears; a text that stays up across a cut is listed once.
Times: act time (0 = the act's first frame) and episode time (act frame 0 = EP_IN_FRAMES), 24 fps.
No audio or picture is read: this is the lock the render plays, which the render pass checked against the encoded files.

Run (repo root, light):  python3 studio/src/episodes/ep01/act4/animatic/tools/transcript_v5.py <out.txt>
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data-v5.ts")
src = open(DATA, encoding="utf-8").read()


def const(name):
    m = re.search(r"export const " + name + r"\s*(?::[^=]*)?=\s*", src)
    return json.JSONDecoder().raw_decode(src[m.end():])[0]


SHOTS, SUBS, RAILS = const("SHOTS"), const("SUBS"), const("RAILS")
ACT_FRAMES, EP_IN = const("ACT_FRAMES"), const("EP_IN_FRAMES")


def tc(f):
    s = f / 24
    return f"{int(s // 60)}:{s % 60:05.2f}"


def words(t):
    return len([w for w in t.split() if re.search(r"[0-9A-Za-z]", w)])


def shot_at(f):
    return next(s for s in SHOTS if s["s"] <= f < s["e"])


rows = []  # (frame, order, text)
for x in SUBS:
    vo, post = x["kind"] == "vo", x["kind"] == "post"
    who = "MAS (V.O.)" if vo else "MAS (THROUGH THEIR LAPTOP)" if x["mode"] == "speaker" else f"{x['shown']} (POST, ON SCREEN)" if post else x["shown"]
    if not vo and not post and x["os"]:
        who += " (O.S.)"
    rows.append((x["s"], 0, f"{who}: {x['text']}", shot_at(x["s"])["id"]))

posts = {re.sub(r"\W+", " ", x["text"]).strip().lower() for x in SUBS if x["kind"] == "post"}
ons = [(r["s"], r["e"], "rail", r["text"]) for r in RAILS]
for sh in SHOTS:
    for t in sh["texts"]:
        ons.append((sh["s"] + t["s"], sh["s"] + t["e"], t["kind"], t["text"]))
ons.sort()
last_end = {}
for s, e, kind, text in ons:
    if words(text) <= 3:
        continue
    if re.sub(r"\W+", " ", text).strip().lower() in posts:  # the post is already a transcript row
        continue
    prev = last_end.get(text)
    last_end[text] = max(e, prev or e)
    if prev is not None and s <= prev + 2:  # still up (continues across a cut): listed once
        continue
    rows.append((s, 1, f"[ON SCREEN, {kind}] {text}", shot_at(s)["id"]))

rows.sort(key=lambda r: (r[0], r[1]))
n_lines = sum(1 for r in rows if r[1] == 0)
n_text = len(rows) - n_lines
out = [
    "MR. MAS - Ep1 \"ACT FOUR\" v5 animatic: transcript (from the timing lock data-v5.ts; the film plays this lock frame for frame)",
    f"Act: {ACT_FRAMES} frames at 24 fps ({tc(ACT_FRAMES)}). Episode time = act time + {tc(EP_IN)}.",
    "Columns: act time, episode time, shot, then the line. Speakers are named as the picture has named them so far",
    "(before the S1.03 label names her, NELEH is BLUEPRINT FIGURE). [ON SCREEN] rows: on-screen text of more than 3 words,",
    "at the frame it first appears. The v.o. and the rails type on, so their full text lands a little after the time shown.",
    f"{n_lines} lines and posts, {n_text} on-screen texts.",
    "",
]
for f, _o, text, sid in rows:
    out.append(f"{tc(f):>8}  {tc(EP_IN + f):>9}  {sid:<7} {text}")
path = sys.argv[1] if len(sys.argv) > 1 else "-"
body = "\n".join(out) + "\n"
if path == "-":
    sys.stdout.write(body)
else:
    open(path, "w", encoding="utf-8").write(body)
    print(f"wrote {path}: {n_lines} lines and posts, {n_text} on-screen texts")
