"""Write the S5-S8 cue sheet (frame-exact in and out points) from the renders, their act logs, the QA and the
ducking map.

    ../../../.venv-theme/bin/python s5-s8_cuesheet.py        # -> s5-s8_cue-sheet.md (and s5-s8_cue-sheet.json)

Run it after s5-s8_render.py, s5-s8_ducking.py and s5-s8_qa.py.
"""
from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import importlib.util as _ilu   # noqa: E402
_sp = _ilu.spec_from_file_location('s5_s8_common', os.path.join(HERE, 's5-s8_common.py'))
C = _ilu.module_from_spec(_sp)
sys.modules['s5_s8_common'] = C
_sp.loader.exec_module(C)

R = os.path.join(HERE, 'render')
FPS = 24
CUES = [
    ('s5-s8_s5-two-am', 'S5 · HIS SIDE, 2 AM', 'S5.02', 'S6.01', 'DARK ROOM (MM-10 a)',
     "in under the card's felt F4 (S1-S4's, struck on 6985): the pedal bows in with a silent attack",
     "the pedal rings across S6.01's first frame (the avalanche's downbeat) and releases; overlap it with S6"),
    ('s5-s8_s6-avalanche', 'S6 · THE AVALANCHE', 'S6.01', 'S7.01', 'SET-PIECE SWING (MM-10 b), the one full band',
     "cut in on S6.01's first frame (the downbeat erupts out of S5's pedal; no pickup, no riser)",
     "DEAD STOP on MADA's label (act 9341, the swung 'and'); digital zero to 9376; the room carries it"),
    ('s5-s8_s7s8-the-return', 'S7 + S8 · THE RETURN, THE LOBBY, THE CODA', 'S7.01', None,
     'MM-11 relay -> the vault\'s F', "the violin enters under Alyi's post (act 9400), after the label's stop",
     "the act ends at 12443; the glass pedal's release rings ~4 s into the tag (crossfade the tag's cue over it)"),
]


def fr(sec):
    return round(sec * FPS, 1)


def main():
    qa = json.load(open(os.path.join(HERE, 's5-s8_qa.json')))
    duck = json.load(open(os.path.join(HERE, 's5-s8_ducking-map.json')))
    doc = dict(schema='mrmas-s5s8-cuesheet/1', cues=[])
    L = []
    L.append('# E01 · Act Four v5 · S5–S8 · cue sheet (frame-exact)\n')
    L.append('Generated by `s5-s8_cuesheet.py` from the renders (`render/<id>.cue.json`, `render/<id>.act-log.json`), '
             'the QA (`s5-s8_qa.json`) and the ducking map (`s5-s8_ducking-map.json`). **Nothing here was heard.**\n')
    L.append('**Clock.** Act frame 0 = episode 12:31:00, 24 fps, from the locked stick timeline '
             '`show/reel/ep01-act4-v5.json` (the pixel preview follows it shot for shot). Timecodes are episode '
             'MM:SS:FF. **Lay each underscore master with its file t = 0 on the act frame given**, at 0 dB against '
             'its master, and apply the ducking map to the music bus on top.\n')
    L.append('## The cues\n')
    L.append('| Cue (render/…-underscore.wav, stems in render/stems/) | Picture | File t = 0 (act frame) | Picture out '
             '(act frame) | File length | Master | In | Out |')
    L.append('|---|---|---|---|---|---|---|---|')
    for cid, title, b_in, b_out, fam, how_in, how_out in CUES:
        cs = json.load(open(os.path.join(R, f'{cid}.cue.json')))
        log = json.load(open(os.path.join(R, f'{cid}.act-log.json')))
        f0 = log['file_t0_act_frame']
        f_out = C.BEATS[b_out]['f0'] if b_out else C.ACT_FRAMES
        dur = cs['timing']['album_duration_s']
        u = cs['masters']['underscore']
        L.append(f"| `{cid}` · {title} · {fam} | {b_in} → {b_out or 'act end'} | **{f0}** ({C.tc(f0 / FPS)}) | "
                 f"**{f_out}** ({C.tc(f_out / FPS)}) | {dur:.3f} s = {dur * FPS:.1f} f (ends act "
                 f"{f0 + dur * FPS:.1f}) | {u['measured']['lufs']} LUFS-I, {u['measured']['true_peak_db']} dBTP "
                 f"(target {u['target_lufs']}) | {how_in} | {how_out} |")
        doc['cues'].append(dict(id=cid, title=title, family=fam, file_t0_act_frame=f0, picture_out_act_frame=f_out,
                                file_len_s=dur, file_end_act_frame=round(f0 + dur * FPS, 1),
                                underscore=u['measured'], target_lufs=u['target_lufs'], lay_in=how_in, lay_out=how_out,
                                files=cs['files'], events=log['events'],
                                mutes=[dict(file_s=[round(a, 4), round(b, 4)],
                                            act_f=[round(f0 + a * FPS, 1), round(f0 + b * FPS, 1)])
                                       for a, b in [(w['t0'], w.get('t1', w['t0'])) for w in cs['qa']['hard_stops']]]))
    L.append('')
    L.append('## Stops, the ring-out and the designed rests\n')
    L.append('| Act frames | Episode TC | Length | What | Cause on screen |')
    L.append('|---|---|---|---|---|')
    B, Lon, Lend, snd, txt = C.B, C.Lon, C.Lend, C.snd, C.txt
    rows = [
        (B('S5.09b'), None, 'RING-OUT (not a stop): the Build stops dead; the pedal holds', "Gerg's look up (S5.09b cut-in)"),
        (txt('S6.06', 'MADA'), txt('S7.01', 'POST: ALYI'), "DEAD STOP (tails cut, digital zero); re-entry: the violin "
         "under Alyi's post", "MADA · LAST FIRER STANDING (freeze_hit_F owns the onset)"),
        (Lend('a5-30-15'), snd('S7.09', 'rubber_stamp_C'), 'DEAD STOP (tails cut); re-entry: the low C pedal under the '
         "stamp's C", '"of what?"; Terb looks at Mada; Mada\'s pause; "Good question." / "good question."; the long hold'),
        (snd('S7.13', 'hourglass_shatter'), txt('S8.01', 'DAYS SINCE') - 0.625, "DESIGNED REST (0.49 s): the pedal rests "
         "on the sand's beat; the Build's pickup re-enters", 'the hourglass shatters; the sand holds its shape one beat'),
        (snd('S8.03', 'alert_bonk'), Lend('a5-30-19') + 1 / 24, 'DESIGNED REST: the flat line ends on the bonk; the '
         "lobby's neon buzz (on F) holds the CU and \"okay.\"; the felt re-enters after it",
         'the CU, "silent like the first" (the firing\'s drawing); "okay." lands dry'),
    ]
    for a, b, what, cause in rows:
        span = f'{fr(a)}' + (f' → {fr(b)}' if b else '')
        ln = f'{b - a:.2f} s' if b else '—'
        L.append(f'| {span} | {C.tc(a)} | {ln} | {what} | {cause} |')
    doc['stops'] = [dict(act_f_in=fr(a), act_f_out=fr(b) if b else None, what=w, cause=c) for a, b, w, c in rows]
    L.append('\nS1–S4 owns the act\'s one designed digital silence (D6, the Cancel click, act 997 → 1086).\n')
    for cid, title, b_in, b_out, fam, how_in, how_out in CUES:
        log = json.load(open(os.path.join(R, f'{cid}.act-log.json')))
        L.append(f'## {title}: sync points (`{cid}`)\n')
        L.append('| Act frame | Episode TC | File s | What |')
        L.append('|---|---|---|---|')
        for e in log['events']:
            L.append(f"| {e['act_frame']} | {e['tc']} | {e['file_s']:.3f} | {e['what']} |")
        L.append('')
    L.append('## The ducking map (`s5-s8_ducking-map.json`)\n')
    s = duck['summary']
    r = duck['rules']
    L.append(f"{s['keys']} keys (every placed take, every silent post and record text from S5.02 to the act end), "
             f"{s['breakpoints']} breakpoints in act frames, deepest {s['deepest_db']} dB. Pre-duck {r['pre_s']} s, "
             f"attack {r['attack_s']} s, release {r['release_s']} s, held across gaps under {r['hold_gap_s']} s. "
             f"Depths: {', '.join(f'{k} {v:g}' for k, v in r['depths_db'].items())} dB. The thinning is composed into "
             "the cues; the map is the mix duck on top, a guide for the re-recording mix.\n")
    L.append('## QA (measured; see `s5-s8_qa.json`)\n')
    L.append('| Cue | Underscore | Short-term p95 | 2–6 kHz | F-major (written / spectral) | Written thirds | '
             'Knee completion | Whole knee | Hard stops | Engine warnings |')
    L.append('|---|---|---|---|---|---|---|---|---|---|')
    for cid, r_ in qa['cues'].items():
        u = r_['underscore']
        fm = r_['f_major']
        hs = '; '.join(f"{float(h.get('peak_dbfs')):.1f} dBFS {'ok' if h.get('ok') else 'TAIL'}" for h in r_['hard_stops']) or '—'
        L.append(f"| `{cid}` | {u['lufs']} LUFS, {u['true_peak_db']} dBTP | {r_['short_term_p95']} | "
                 f"{r_['band_2_6k_db']} dB | {'OK' if fm['ok_written'] else 'FAIL'} / "
                 f"{'OK' if fm['ok_spectral'] else str(len(fm['fails'])) + ' window(s) over'} | {fm['written_third']} | "
                 f"{r_['knee_completion']} | {r_['knee_whole']} | {hs} | {len(r_['warnings'])} |")
    fl = qa['flow']
    L.append(f"\n**Music on the act clock** (the three masters laid, 50 ms windows, off below {fl['threshold_dbfs']} "
             f"dBFS): {fl['runs']} runs; {len(fl['off_windows'])} off-windows of 0.3 s or more, "
             f"{len(fl['unexplained'])} unexplained; {len(fl['fragments_under_2s'])} runs under 2 s.\n")
    for o in fl['off_windows']:
        L.append(f"- act {o['act_f'][0]} → {o['act_f'][1]} ({o['tc']}, {o['len_s']} s): {o['cause']}")
    for f_ in fl['fragments_under_2s']:
        L.append(f"- fragment: act {f_['act_f']}, {f_['len_s']} s")
    L.append(f"\n**Under the record:** {qa['record_melodic_onsets']} melodic onsets inside a quoted real line.\n")
    L.append('**The engine\'s warnings, verbatim, with their cause** (every one is a marker the onset QA could not pin '
             'within 10 ms; all are soft attacks, sync points for a chord or a pulse, not hits):\n')
    import re
    for cid, r_ in qa['cues'].items():
        ev = json.load(open(os.path.join(R, f'{cid}.act-log.json')))['events']
        for w in r_['warnings']:
            m = re.match(r'marker at ([0-9.]+) s', w)
            cause = ''
            if m:                                      # the marker's own label, from the act log (same file time)
                t = float(m.group(1))
                hit = [e['what'] for e in ev if abs(e['file_s'] - t) < 0.002]
                cause = f"the marker is: {hit[0]} (a soft attack; a sync point, not a hit)" if hit else ''
            L.append(f"- `{cid}`: {w}" + (f" -- {cause}" if cause else ''))
    L.append('')
    with open(os.path.join(HERE, 's5-s8_cue-sheet.md'), 'w') as fh:
        fh.write('\n'.join(L) + '\n')
    with open(os.path.join(HERE, 's5-s8_cue-sheet.json'), 'w') as fh:
        json.dump(doc, fh, indent=1, default=float)
    print('wrote s5-s8_cue-sheet.md and s5-s8_cue-sheet.json')


if __name__ == '__main__':
    main()
